# New ports collection makefile for:    font-misc-cyrillic
# Date created:		28 Aug 2005
# Whom:			Pawel Worach
#
# $FreeBSD: ports/x11-fonts/font-misc-cyrillic/Makefile,v 1.1 2007/05/19 20:29:15 flz Exp $
# $MidnightBSD$
#

PORTNAME=	font-misc-cyrillic
PORTVERSION=	1.0.0
CATEGORIES=	x11-fonts

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X.Org miscellaneous Cyrillic font
LICENSE=	unknown

XORG_CAT=	font

.include <bsd.port.mk>
