PORTNAME=	diffy
PORTVERSION=	3.4.4
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Convenient diffing in ruby
WWW=		https://github.com/samg/diffy

LICENSE=	mit
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		gem

NO_ARCH=	yes

.include <bsd.port.mk>
