# $MidnightBSD: mports/www/linux-seamonkey/Makefile,v 1.17 2009/01/04 20:42:19 laffer1 Exp $

PORTNAME=	seamonkey
PORTVERSION=	1.1.17
DISTVERSIONSUFFIX=	.en-US.linux-i686
CATEGORIES=	www
MASTER_SITE_SUBDIR=	${PORTNAME}/releases/${PORTVERSION}

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	The open source, standards compliant web browser
LICENSE=	mpl

USE_GCPIO=	yes

.include "${.CURDIR}/Makefile.common"
.include <bsd.port.mk>
