# New ports collection makefile for:	linux-seamonkey
# Date created:		1 February 2006
# Whom:			Andrew Pantyukhin <infofarmer@FreeBSD.org>
#
# $MidnightBSD: mports/www/linux-seamonkey/Makefile,v 1.11 2007/12/03 05:00:44 laffer1 Exp $
# $FreeBSD: ports/www/linux-seamonkey/Makefile,v 1.16 2007/02/27 21:19:22 sat Exp $
#

PORTNAME=	seamonkey
PORTVERSION=	1.1.8
DISTVERSIONSUFFIX=	.en-US.linux-i686
CATEGORIES=	www
MASTER_SITE_SUBDIR=	${PORTNAME}/releases/${PORTVERSION}

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	The open source, standards compliant web browser
LICENSE=	mpl

USE_GCPIO=	yes

.include "${.CURDIR}/Makefile.common"
.include <bsd.port.mk>
