# New ports collection makefile for:    font-xfree86-type1
# Date created:		28 Aug 2005
# Whom:			Pawel Worach
#
# $FreeBSD: ports/x11-fonts/font-xfree86-type1/Makefile,v 1.1 2007/05/19 20:29:21 flz Exp $
# $MidnightBSD$
#

PORTNAME=	font-xfree86-type1
PORTVERSION=	1.0.0
CATEGORIES=	x11-fonts

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X.Org XFree86 Type1 font
LICENSE=	x11

XORG_CAT=	font

.include <bsd.port.mk>
