# $FreeBSD: ports/x11-fonts/font-mutt-misc/Makefile,v 1.1 2007/05/19 20:29:18 flz Exp $
# $MidnightBSD$

PORTNAME=	font-mutt-misc
PORTVERSION=	1.0.3
PORTREVISION=	1
CATEGORIES=	x11-fonts

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X.Org miscellaneous Mutt fonts
LICENSE=	mit

XORG_CAT=	font

.include <bsd.port.mk>
