# $FreeBSD: ports/x11/scrnsaverproto/Makefile,v 1.1 2007/05/19 20:27:18 flz Exp $
# $MidnightBSD: mports/x11/scrnsaverproto/Makefile,v 1.1 2007/10/03 19:25:49 ctriv Exp $

PORTNAME=	scrnsaverproto
PORTVERSION=	1.2.0
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	ScrnSaver extension headers
LICENSE=	x11

XORG_CAT=	proto

.include <bsd.port.mk>
