# $MidnightBSD: mports/misc/Makefile,v 1.9 2006/11/04 19:11:16 wintellect Exp $
#

    COMMENT = Miscellaneous utilities

    SUBDIR += brs
    SUBDIR += compat4x
    SUBDIR += compat5x
    SUBIDR += gnomehier
    SUBDIR += gnustep-examples
    SUBIDR += help2man
    SUBDIR += hicolor-icon-theme
    SUBDIR += kdehier
    SUBDIR += ldconfig_compat
    SUBDIR += localedata
    SUBDIR += mime-support
    SUBDIR += shared-mime-info

.include <bsd.port.subdir.mk>
