# $MidnightBSD: mports/x11/dri2proto/Makefile,v 1.1 2009/03/15 18:27:19 laffer1 Exp $

PORTNAME=	dri2proto
PORTVERSION=	2.0
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	DRI2 prototype headers
LICENSE=	x11

XORG_CAT=	proto

.include <bsd.port.mk>
