PORTNAME=	xf86-video-chips
PORTVERSION=	1.4.0
PORTREVISION=	2
CATEGORIES=	x11-drivers

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X.Org chips display driver
WWW=		https://www.x.org/

LICENSE=	mit

USES=		xorg-cat:driver

.include <bsd.port.mk>
