PORTNAME=	xf86-video-chips
PORTVERSION=	1.4.0
CATEGORIES=	x11-drivers

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X.Org chips display driver

LICENSE=	mit

XORG_CAT=	driver
USE_XORG=	xorgproto

.include <bsd.port.mk>
