PORTNAME=	expression_parser
PORTVERSION=	0.9.0
CATEGORIES=	math rubygems
MASTER_SITES=	RG

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Mathematical expression parser for Ruby
WWW=		http://lukaszwrobel.pl/blog/math-parser-part-3-implementation

NO_ARCH=	yes

USES=		gem

.include <bsd.port.mk>
