# $FreeBSD: head/graphics/gstreamer1-plugins-openjpeg/Makefile 375225 2014-12-22 10:22:38Z kwm $

PORTREVISION=	0
CATEGORIES=	graphics

COMMENT=	Gstreamer jpeg2000 decoder plugin

GST_PLUGIN=	openjpeg
DIST=		bad

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
