# Created by: Palle Girgensohn <girgen@pingpong.net>
# $FreeBSD: head/databases/postgresql94-docs/Makefile 366197 2014-08-26 10:17:30Z crees $

WANT_PGSQL_VER=9.4

.include "${.CURDIR}/../postgresql91-docs/Makefile"
