# $MidnightBSD$

PORTNAME=	hicolor-icon-theme
PORTVERSION=	0.15
CATEGORIES=	misc gnome
MASTER_SITES=	http://icon-theme.freedesktop.org/releases/

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	High-color icon theme shell from the FreeDesktop project

LICENSE=	gpl2

USES=		tar:xz
GNU_CONFIGURE=	yes

.include <bsd.port.mk>
