# $MidnightBSD: mports/mail/Makefile,v 1.2 2006/09/25 04:45:40 archite Exp $
# $FreeBSD: ports/mail/Makefile,v 1.793 2006/08/25 12:54:08 sat Exp $
#

    COMMENT = Electronic mail utilities

    SUBDIR += dovecot
    SUBDIR += fetchmail
    SUBDIR += linux-thunderbird
    SUBDIR += mutt
    SUBDIR += pine-pgp-filters
    SUBDIR += pine4
    SUBDIR += wpop3d

.include <bsd.port.subdir.mk>
