PORTNAME=	png
PORTVERSION=	1.3.1
CATEGORIES=	graphics rubygems
MASTER_SITES=	RG

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Almost-pure-ruby PNG library
WWW=		https://www.zenspider.com/projects/png.html \
		https://github.com/seattlerb/png

LICENSE=	mit

RUN_DEPENDS=	rubygem-rubyinline>=3.9<4:devel/rubygem-rubyinline

USES=		gem

NO_ARCH=	yes

.include <bsd.port.mk>
