# $MidnightBSD$

PORTNAME=	libXprintUtil
PORTVERSION=	1.0.1
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	The XprintUtil library
LICENSE=	mit

XORG_CAT=	lib
USE_XORG=	printproto:both x11 xau xp xt
USE_AUTOTOOLS=	libtool

.include <bsd.port.mk>
