PORTNAME=	Tempita
PORTVERSION=	0.5.2
CATEGORIES=	textproc python
MASTER_SITES=	PYPI
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Small text templating language
WWW=		https://pythonpaste.org/tempita/

LICENSE=	mit

USES=			python
USE_PYTHON=		distutils autoplist

NO_ARCH=	yes

.include <bsd.port.mk>
