# $MidnightBSD: mports/x11-toolkits/Makefile,v 1.32 2007/11/24 03:14:23 laffer1 Exp $
#

    COMMENT = X11 toolkits
    
    SUBDIR += Xaw3d
    SUBDIR += eel
    SUBDIR += gdl
    SUBDIR += gnustep-art
    SUBDIR += gnustep-back
    SUBDIR += gnustep-cairo
    SUBDIR += gnustep-gui
    SUBDIR += gnustep-xdps
    SUBDIR += gstreamer-plugins-pango
    SUBDIR += gtk12
    SUBDIR += gtk20
    SUBDIR += gtkglext
    SUBDIR += gtkmm12
    SUBDIR += gtkmm20
    SUBDIR += gtkmm24
    SUBDIR += gtksourceview
    SUBDIR += gtoolkit
    SUBDIR += libbonoboui
    SUBDIR += libgnomeui
    SUBDIR += libgnomeprintui
    SUBDIR += libsexy
    SUBDIR += libwnck
    SUBDIR += libXaw
    SUBDIR += libXmu
    SUBDIR += libXt
    SUBDIR += linux-gtk
    SUBDIR += linux-gtk2
    SUBDIR += linux-pango
    SUBDIR += open-motif
    SUBDIR += pango
    SUBDIR += qt33
    SUBDIR += renaissance
    SUBDIR += tk82
    SUBDIR += tk83
    SUBDIR += tk84
    SUBDIR += tk84-thread
    SUBDIR += tk85
    SUBDIR += tk85-thread
    SUBDIR += tkdnd
    SUBDIR += tkshape
    SUBDIR += tkstep80
    SUBDIR += vte

.include <bsd.port.subdir.mk>
