# $MidnightBSD: mports/x11-fonts/xfsinfo/Makefile,v 1.1 2007/10/07 17:10:49 ctriv Exp $

PORTNAME=	xfsinfo
PORTVERSION=	1.0.2
CATEGORIES=	x11-fonts

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X font server information utility
LICENSE=	x11

XORG_CAT=	app
USE_XORG=	x11 libfs

PLIST_FILES=	bin/xfsinfo

MAN1=		xfsinfo.1

.include <bsd.port.mk>
