# $MidnightBSD: mports/x11/xwd/Makefile,v 1.1 2007/10/08 16:07:35 ctriv Exp $

PORTNAME=	xwd
PORTVERSION=	1.0.2
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Dump an image of an X window
LICENSE=	x11

XORG_CAT=	app
USE_XORG=	xmuu x11

PLIST_FILES=	bin/xwd

MAN1=		xwd.1

.include <bsd.port.mk>
