# $MidnightBSD: mports/x11/xwd/Makefile,v 1.4 2011/09/20 23:57:41 laffer1 Exp $

PORTNAME=	xwd
PORTVERSION=	1.0.5
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Dump an image of an X window
LICENSE=	mit

XORG_CAT=	app
USE_XORG=	xmuu x11

PLIST_FILES=	bin/xwd

MAN1=		xwd.1

.include <bsd.port.mk>
