# $FreeBSD: head/graphics/gstreamer1-plugins-zbar/Makefile 375225 2014-12-22 10:22:38Z kwm $

PORTREVISION=	0
CATEGORIES=	graphics

COMMENT=	Gstreamer ZBar barcode detector plugin

GST_PLUGIN=	zbar
DIST=		bad

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
