COMMENT = Shells

SUBDIR += 44bsd-csh
SUBDIR += bash
SUBDIR += bash-completion
SUBDIR += cvs-server
SUBDIR += dash
SUBDIR += elvish
SUBDIR += envy
SUBDIR += es
SUBDIR += fd
SUBDIR += fish
SUBDIR += ibsh
SUBDIR += ksh93
SUBDIR += ksh93-devel
SUBDIR += mksh
SUBDIR += nologinmsg
SUBDIR += osh
SUBDIR += p5-Term-ShellUI
SUBDIR += pdksh
SUBDIR += psh
SUBDIR += rc
SUBDIR += rssh
SUBDIR += rush
SUBDIR += sash
SUBDIR += scponly
SUBDIR += tcshrc
SUBDIR += v7sh
SUBDIR += yash
SUBDIR += zsh
SUBDIR += zsh-antigen
SUBDIR += zsh-autosuggestions
SUBDIR += zsh-completions
SUBDIR += zsh-navigation-tools

.include <bsd.port.subdir.mk>
