
PORTNAME=	xedit
PORTVERSION=	1.2.2
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Simple text editor for X

LICENSE=	mit

USES=		xorg xorg-cat:app
USE_XORG=	x11 xmu xt xaw7

.include <bsd.port.mk>
