# Created by: Palle Girgensohn <girgen@partitur.se>
# $FreeBSD: head/databases/postgresql95-plperl/Makefile 405482 2016-01-07 19:58:47Z girgen $

WANT_PGSQL_VER=	9.5

.include "${.CURDIR}/../postgresql90-plperl/Makefile"
