PORTNAME=	dm-validations
PORTVERSION=	1.2.0
CATEGORIES=	databases rubygems
MASTER_SITES=	RG

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Library for performing validations on DM models and pure Ruby object
WWW=		https://github.com/datamapper/dm-validations

LICENSE=	mit

BUILD_DEPENDS=	${RUN_DEPENDS}
RUN_DEPENDS=	rubygem-dm-core>=${PORTVERSION}:databases/rubygem-dm-core

NO_ARCH=	yes

USES=		gem

.include <bsd.port.mk>
