# $FreeBSD: head/security/php72-hash/Makefile 483821 2018-11-02 16:12:05Z joneum $

CATEGORIES=	security

MASTERDIR=	${.CURDIR}/../../lang/php72

PKGNAMESUFFIX=	-hash

TEST_TARGET=    test

.include "${MASTERDIR}/Makefile"
