PORTNAME=	maxmind-db
PORTVERSION=	1.2.0
CATEGORIES=	net rubygems
MASTER_SITES=	RG

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	MaxMind DB Reader Ruby API
WWW=		https://github.com/maxmind/MaxMind-DB-Reader-ruby

LICENSE=	Apache-2.0 mit
LICENSE_COMB=	dual
LICENSE_FILE_Apache-2.0=	${WRKSRC}/LICENSE-APACHE
LICENSE_FILE_mit=	${WRKSRC}/LICENSE-MIT

USES=		gem

NO_ARCH=	yes

.include <bsd.port.mk>
