# $FreeBSD: head/multimedia/gstreamer1-plugins-hls/Makefile 392902 2015-07-25 19:59:35Z tijl $

PORTREVISION=	0
CATEGORIES=	multimedia

COMMENT=	Gstreamer HLS plugin

GST_PLUGIN=	hls
DIST=		bad

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
