# $MidnightBSD: mports/x11-drivers/xf86-video-siliconmotion/Makefile,v 1.2 2009/03/16 15:33:33 laffer1 Exp $

PORTNAME=	xf86-video-siliconmotion
PORTVERSION=	1.7.3
CATEGORIES=	x11-drivers

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X.Org siliconmotion display driver
LICENSE=	x11

XORG_CAT=	driver
USE_XORG=	videoproto xextproto
MAN4=		siliconmotion.4x

.include <bsd.port.mk>
