PORTNAME=	fs
DISTVERSION=	1.6.6
PORTREVISION=	1
CATEGORIES=	filesystems sysutils
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Cross-Platform File System Operations Based on 'libuv'
WWW=		https://fs.r-lib.org

LICENSE=	mit
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		cran:auto-plist,compiles

NO_TEST=	yes

.include <bsd.port.mk>
