# $MidnightBSD$

PORTNAME=	aspell
DISTVERSION=	6-de-20030222-1
CATEGORIES=	textproc german
PKGNAMEPREFIX=	de-

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Aspell German dictionary

LICENSE=	gpl2

DICT=	 	de

USES+=		tar:bzip2

.include "${.CURDIR}/../../textproc/aspell/Makefile.inc"
.include <bsd.port.post.mk>
