# New ports collection makefile for:	gstreamer-plugins-vorbis
# Date created:			23 Nov 2007
# Whom:				Lucas Holt <luke@Midnightbsd.org>
#
# $MidnightBSD$

CATEGORIES=	audio

COMMENT=	Gstreamer vorbis encoder/decoder plugin
LICENSE=	lgpl

GST_PLUGIN=	vorbis

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
