PORTNAME=	xcmsdb
PORTVERSION=	1.0.5
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Device Color Characterization utility for X

LICENSE=	mit

USES=		xorg xorg-cat:app
USE_XORG=	x11

PLIST_FILES=	bin/xcmsdb man/man1/xcmsdb.1.gz

.include <bsd.port.mk>
