# $MidnightBSD: mports/comms/Makefile,v 1.13 2008/08/17 21:32:53 laffer1 Exp $
#

    COMMENT = Communication utilities

    SUBDIR += acfax
    SUBDIR += aldo
    SUBDIR += asmodem
    SUBDIR += atslog
    SUBDIR += bforce
    SUBDIR += bforce-kst
    SUBDIR += efax
    SUBDIR += libirman
    SUBDIR += libticables
    SUBDIR += lirc
    SUBDIR += lrzsz
    SUBDIR += ltmdm
    SUBDIR += minicom
    SUBDIR += pr
    SUBDIR += tits

.include <bsd.port.subdir.mk>
