PORTNAME=	rlang
PORTVERSION=	1.1.6
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Functions for Base Types and Core R and 'Tidyverse' Features
WWW=		https://cran.r-project.org/web/packages/rlang/

LICENSE=	mit

USES=		cran:auto-plist,compiles

NO_TEST=	yes

.include <bsd.port.mk>
