PORTNAME=	protocol-http
PORTVERSION=	0.62.2
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Provides abstractions to handle HTTP protocols
WWW=		https://socketry.github.io/protocol-http/ \
		https://github.com/socketry/protocol-http

LICENSE=	mit
LICENSE_FILE=	${WRKSRC}/license.md

RUBY_VER=	3.3

USES=		gem

NO_ARCH=	yes

.include <bsd.port.mk>
