# $MidnightBSD$
# $FreeBSD: ports/devel/p5-Hook-LexWrap/Makefile,v 1.2 2007/09/08 00:57:29 linimon Exp $

PORTNAME=	Hook-LexWrap
PORTVERSION=	0.20
CATEGORIES=	devel perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	Hook
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Lexically scoped subroutine wrappers for Perl
LICENSE=	perl

PERL_CONFIGURE=	yes

.include <bsd.port.mk>
