# $MidnightBSD$

PORTNAME=	Crypt-OpenSSL-Bignum
PORTVERSION=	0.04
CATEGORIES=	security perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	OpenSSL's multiprecision integer arithmetic
LICENSE=	perl

PERL_CONFIGURE=	yes

.include <bsd.port.mk>
