# Created by: Pawel Worach

PORTNAME=	font-bh-100dpi
PORTVERSION=	1.0.3
PORTREVISION=	4
CATEGORIES=	x11-fonts

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X.Org Bigelow Holmes 100dpi font

LICENSE=	unknown

USES=		xorg xorg-cat:font
USE_XORG=	fontutil

.include <bsd.port.mk>
