# New ports collection makefile for:	xf86-video-siliconmotion
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11-drivers/xf86-video-siliconmotion/Makefile,v 1.2 2007/09/13 19:44:50 flz Exp $
# $MidnightBSD$
#

PORTNAME=	xf86-video-siliconmotion
PORTVERSION=	1.5.1
CATEGORIES=	x11-drivers

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X.Org siliconmotion display driver
LICENSE=	x11

XORG_CAT=	driver
USE_XORG=	videoproto xextproto
MAN4=		siliconmotion.4x

.include <bsd.port.mk>
