# $FreeBSD: ports/converters/p5-MIME-Base64/Makefile,v 1.41 2005/12/21 12:48:13 leeym Exp $
# $MidnightBSD$

PORTNAME=	MIME-Base64
PORTVERSION=	3.15
CATEGORIES=	converters perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Perl5 module for Base64 and Quoted-Printable encodings

LICENSE=	artistic gpl
LICENSE_COMB=	dual

USES=		perl5
PERL_CONFIGURE=	YES

.include <bsd.port.mk>
