# $MidnightBSD$

PORTNAME=	libogg
DISTVERSION=	1.1.2-2
PORTREVISION=	4
CATEGORIES=	audio linux

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Ogg bitstream library (Linux version)
LICENSE=	bsd3

CONFLICTS=	linux-f10-libogg-[0-9]*

USE_LINUX_RPM=	yes
LINUX_DIST_VER=	4
USE_LDCONFIG=	yes

.include <bsd.port.mk>
