PORTNAME=	oclock
PORTVERSION=	1.0.4
CATEGORIES=	x11-clocks

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Round clock application for X

LICENSE=	mit

USES=		xorg xorg-cat:app
USE_XORG=	x11 xmu xext xt xkbfile

.include <bsd.port.mk>
