# $FreeBSD: head/audio/gstreamer1-plugins-lame/Makefile 375225 2014-12-22 10:22:38Z kwm $

PORTREVISION=	0
CATEGORIES=	audio

COMMENT=	Gstreamer mp3 encode plugin

GST_PLUGIN=	lame
DIST=		ugly

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
