# $MidnightBSD$

PORTNAME=	Socket
PORTVERSION=	2.021
CATEGORIES=	net perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:PEVANS
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Networking constants and support functions

LICENSE=	artistic gpl
LICENSE_COMB=	dual

PERL_CONFIGURE=	yes
USES=		perl5

.include <bsd.port.mk>
