PORTNAME=	xf86-video-scfb
PORTVERSION=	0.0.7
PORTREVISION=	1
CATEGORIES=	x11-drivers

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X.Org syscons display driver
WWW=		https://github.com/rayddteam/xf86-video-scfb

LICENSE=       mit bsd2
LICENSE_COMB=  multi

USES=		xorg-cat:driver

IGNORE_MASTER_SITE_XORG=yes
USE_GITHUB=	yes
GH_ACCOUNT=	rayddteam

.include <bsd.port.mk>
