# $MidnightBSD: mports/graphics/Makefile,v 1.29 2007/01/24 16:44:30 laffer1 Exp $
#

    COMMENT = Graphics tools and libraries

    SUBDIR += ImageMagick
    SUBDIR += OpenEXR
    SUBDIR += aalib
    SUBDIR += cairo
    SUBDIR += dri
    SUBDIR += feh
    SUBDIR += gd
    SUBDIR += giblib
    SUBDIR += gle
    SUBDIR += glitz
    SUBDIR += imlib
    SUBDIR += imlib2
    SUBDIR += jasper
    SUBDIR += jbigkit
    SUBDIR += jpeg
    SUBDIR += kdegraphics3
    SUBDIR += lcms
    SUBDIR += libart_lgpl
    SUBDIR += libdrm
    SUBDIR += libexif
    SUBDIR += libfpx
    SUBDIR += libglut
    SUBDIR += libgphoto2
    SUBDIR += libmng
    SUBDIR += libungif
    SUBDIR += linux-ac3d
    SUBDIR += linux-adobesvg
    SUBDIR += linux-gdk-pixbuf
    SUBDIR += linux-imlib
    SUBDIR += linux-jpeg
    SUBDIR += linux-libmng
    SUBDIR += linux-panorama-tools
    SUBDIR += linux-png
    SUBDIR += linux-png10
    SUBDIR += linux-sdl_image
    SUBDIR += linux-tiff
    SUBDIR += linux-ungif
    SUBDIR += linux_dri
    SUBDIR += ming
    SUBDIR += netpbm
    SUBDIR += php5-exif
    SUBDIR += php5-gd
    SUBDIR += php5-ming
    SUBDIR += png
    SUBDIR += poppler
    SUBDIR += poppler-qt
    SUBDIR += scr2png
    SUBDIR += sdl_image
    SUBDIR += svgalib
    SUBDIR += tiff
    SUBDIR += wmicons
    SUBDIR += xli

.include <bsd.port.subdir.mk>
