# New ports collection makefile for:	php5-pdo_pgsql
# Date created:			12 Oct 2007
# Whom:				<luke@MidnightBSD.org>
#
# $MidnightBSD$
#

CATEGORIES=	databases

MASTERDIR=	${.CURDIR}/../../lang/php5

PKGNAMESUFFIX=	-pdo_pgsql

.include "${MASTERDIR}/Makefile"
