PORTNAME=	Archive-Extract
PORTVERSION=	0.80
CATEGORIES=	archivers perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Generic archive extracting mechanism
WWW=		https://metacpan.org/release/Archive-Extract

LICENSE=	artistic gpl+
LICENSE_COMB=	dual

NO_ARCH=	yes
# magus
NO_TEST=	yes
USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
