# $MidnightBSD$

PORTNAME=	List-MoreUtils
DISTVERSION=	0.33
CATEGORIES=	lang perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:ADAMK
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Provide the stuff missing in List::Util
LICENSE=	perl

PERL_CONFIGURE=	yes

MAN3=	List::MoreUtils.3

.include <bsd.port.mk>
