# New ports collection makefile for:	p5-Email-Simple
# Date created:				August 31 2003
# Whom:					Lars Thegler <lars@thegler.dk>
#
# $FreeBSD: ports/mail/p5-Email-Simple/Makefile,v 1.22 2008/06/29 02:24:28 leeym Exp $
#

PORTNAME=	Email-Simple
PORTVERSION=	2.00.4
CATEGORIES=	mail perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-
DISTNAME=	${PORTNAME}-${PORTVERSION:C|\.([0-9])$|\1|}

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Simple parsing of RFC2822 message format and headers
LICENSE= gpl2
PERL_CONFIGURE=	yes

MAN3=		Email::Simple.3 Email::Simple::Header.3

.include <bsd.port.mk>
