# $MidnightBSD$

PORTNAME=	FreezeThaw
PORTVERSION=	0.50.01
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-
DISTNAME=	${PORTNAME}-${PORTVERSION:C/\.(..)$/\1/}

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Module for converting Perl structures to strings and back

LICENSE=	artistic gpl
LICENSE_COMB=	dual

USES=		perl5
PERL_CONFIGURE=	yes

.include <bsd.port.mk>
