# $MidnightBSD: mports/x11-servers/Makefile,v 1.5 2006/12/11 05:29:43 laffer1 Exp $
#

    COMMENT = X11 servers

    SUBDIR += mga_hal
    SUBDIR += x2vnc
    SUBDIR += x2x
    SUBDIR += xorg-dmx
    SUBDIR += xorg-fontserver
    SUBDIR += xorg-nestserver
    SUBDIR += xorg-printserver
    SUBDIR += xorg-server
    SUBDIR += xorg-vfbserver

.include <bsd.port.subdir.mk>
