# $MidnightBSD: mports/x11-servers/Makefile,v 1.6 2007/10/23 03:39:05 ctriv Exp $
#

    COMMENT = X11 servers

    SUBDIR += mga_hal
    SUBDIR += x2vnc
    SUBDIR += x2x
    SUBDIR += xorg-dmx
    SUBDIR += xorg-nestserver
    SUBDIR += xorg-printserver
    SUBDIR += xorg-server
    SUBDIR += xorg-vfbserver

.include <bsd.port.subdir.mk>
