# $MidnightBSD: mports/x11/xrefresh/Makefile,v 1.1 2007/10/08 15:48:28 ctriv Exp $

PORTNAME=	xrefresh
PORTVERSION=	1.0.2
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Refresh all or part of an X screen
LICENSE=	x11

XORG_CAT=	app
USE_XORG=	x11

PLIST_FILES=	bin/xrefresh

MAN1=		xrefresh.1

.include <bsd.port.mk>
