PORTNAME=	drb
PORTVERSION=	2.2.1
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Distributed object system for Ruby
WWW=		https://github.com/ruby/drb

LICENSE=	bsd2 ruby
LICENSE_COMB=	dual
LICENSE_FILE_BSD2CLAUSE=${WRKSRC}/LICENSE.txt

USES=		gem

NO_ARCH=	yes

.include <bsd.port.mk>
