# $FreeBSD: ports/x11/xload/Makefile,v 1.2 2007/07/02 17:20:56 lesi Exp $
# $MidnightBSD: mports/x11/xload/Makefile,v 1.2 2011/09/20 23:51:30 laffer1 Exp $

PORTNAME=	xload
PORTVERSION=	1.1.0
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	System load average display for X
LICENSE=	mit

XORG_CAT=	app
USE_XORG=	xt xaw

MAN1=		xload.1

.include <bsd.port.mk>
