# $MidnightBSD: mports/textproc/p5-YAML/Makefile,v 1.5 2011/05/31 00:19:18 laffer1 Exp $

PORTNAME=	YAML
PORTVERSION=	0.77
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	YAML implementation in Perl
LICENSE=	perl

PERL_CONFIGURE=	yes

MAN3=	\
	Test::YAML.3 \
	YAML.3 \
	YAML::Any.3 \
	YAML::Dumper.3 \
	YAML::Dumper::Base.3 \
	YAML::Error.3 \
	YAML::Loader.3 \
	YAML::Loader::Base.3 \
	YAML::Marshall.3 \
	YAML::Mo.3 \
	YAML::Node.3 \
	YAML::Tag.3 \
	YAML::Types.3

.include <bsd.port.mk>
