PORTNAME=	timeliness
PORTVERSION=	0.5.3
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Fast date/time parser with customisable formats, timezone and I18n support
WWW=		https://github.com/adzap/timeliness

LICENSE=	mit
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		gem

NO_ARCH=	yes

.include <bsd.port.mk>
