# $MidnightBSD$

PORTNAME=	libXv
PORTVERSION=	1.0.10
PORTREVISION=	2
PORTEPOCH=	1
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X Video Extension library
LICENSE=	mit

XORG_CAT=	lib
USE_XORG=	x11 xext xextproto videoproto:both xproto:both

.include <bsd.port.mk>
