# $MidnightBSD: mports/x11/editres/Makefile,v 1.2 2011/05/02 23:18:00 laffer1 Exp $

PORTNAME=	editres
PORTVERSION=	1.0.6
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Dynamic resource editor for X Toolkit Applications
LICENSE=	mit

XORG_CAT=	app
USE_XORG=	x11 xt xmu xaw

MAN1=		editres.1

.include <bsd.port.mk>
