# $MidnightBSD$
# $FreeBSD: head/x11-drivers/xf86-video-nv/Makefile 433863 2017-02-11 14:17:58Z rezny $

PORTNAME=	xf86-video-nv
PORTVERSION=	2.1.21
CATEGORIES=	x11-drivers

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X.Org nv display driver

XORG_CAT=	driver

.include <bsd.port.mk>
