# $FreeBSD: ports/x11/xf86vidmodeproto/Makefile,v 1.1 2007/05/19 20:27:51 flz Exp $
# $MidnightBSD: mports/x11/xf86vidmodeproto/Makefile,v 1.1 2007/10/02 19:54:04 ctriv Exp $

PORTNAME=	xf86vidmodeproto
PORTVERSION=	2.3
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	XFree86-VidModeExtension extension headers
LICENSE=	x11

XORG_CAT=	proto

.include <bsd.port.mk>
