# $MidnightBSD: mports/x11-drivers/xf86-video-savage/Makefile,v 1.3 2011/05/07 21:42:45 laffer1 Exp $

PORTNAME=	xf86-video-savage
PORTVERSION=	2.3.2
CATEGORIES=	x11-drivers

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X.Org savage display driver
LICENSE=	mit

USE_GL=		gl

XORG_CAT=	driver
USE_XORG=	xf86driproto videoproto xextproto glproto
MAN4=		savage.4x

.include <bsd.port.mk>
