# $MidnightBSD: mports/converters/p5-Unicode-String/Makefile,v 1.2 2007/05/25 19:33:21 ctriv Exp $
# $FreeBSD: ports/converters/p5-Unicode-String/Makefile,v 1.10 2005/11/15 08:33:28 tobez Exp $

PORTNAME=	Unicode-String
PORTVERSION=	2.09
CATEGORIES=	converters perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	These are experimental Perl5 modules to handle various Unicode issues
LICENSE=	perl

PERL_CONFIGURE=	yes

.include <bsd.port.pre.mk>

MAN3=		Unicode::CharName.3 Unicode::String.3

.include <bsd.port.post.mk>
