# New ports collection makefile for:	xcmiscproto
# Date Created:				08 Aug 2005
# Whom:					Dejan Lesjak <lesi@FreeBSD.org>
#
# $FreeBSD: ports/x11/xcmiscproto/Makefile,v 1.1 2007/05/19 20:27:41 flz Exp $
# $MidnightBSD$
#

PORTNAME=	xcmiscproto
PORTVERSION=	1.1.2
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	XCMisc extension headers
LICENSE=	x11

XORG_CAT=	proto

.include <bsd.port.mk>
