# $MidnightBSD$
# $FreeBSD: head/audio/gstreamer1-plugins-vorbis/Makefile 375225 2014-12-22 10:22:38Z kwm $

PORTREVISION=	0
CATEGORIES=	audio

COMMENT=	Gstreamer vorbis encoder/decoder plugin

GST_PLUGIN=	vorbis
DIST=		base

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
