# New ports collection makefile for:	xf86bigfontproto
# Date Created:				06 Feb 2006
# Whom:					Eric Anholt <anholt@FreeBSD.org>
#
# $FreeBSD: ports/x11/xf86driproto/Makefile,v 1.1 2007/05/19 20:27:50 flz Exp $
# $MidnightBSD: mports/x11/xf86driproto/Makefile,v 1.1 2007/10/07 16:29:54 ctriv Exp $
#

PORTNAME=	xf86driproto
PORTVERSION=	2.0.4
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	XFree86-DRI extension headers
LICENSE=	x11

XORG_CAT=	proto

.include <bsd.port.mk>
