# $MidnightBSD: mports/x11-toolkits/libXmu/Makefile,v 1.2 2009/03/15 20:36:13 laffer1 Exp $

PORTNAME=	libXmu
PORTVERSION=	1.1.0
CATEGORIES=	x11-toolkits

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X Miscellaneous Utilities libraries
LICENSE=	x11

XORG_CAT=	lib
USE_XORG=	xproto:both x11 xt xext

.include <bsd.port.mk>
