PORTNAME=	optimist
PORTVERSION=	3.2.1
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Command-line option parser for Ruby
WWW=		https://www.manageiq.org/optimist/ \
		https://github.com/ManageIQ/optimist

LICENSE=	mit
LICENSE_FILE=	${WRKSRC}/LICENSE.txt

USES=		gem

NO_ARCH=	yes

.include <bsd.port.mk>
