PORTNAME=	xfun
DISTVERSION=	0.52
CATEGORIES=	misc
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Miscellaneous Functions by Yihui Xie
WWW=		https://cran.r-project.org/package=xfun

LICENSE=	mit
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		cran:auto-plist,compiles

# circular depends
NO_TEST=	yes

.include <bsd.port.mk>
