# Created by: Stephen Roznowski <sjr1@flash.net>

PORTNAME=	xmail
PORTVERSION=	1.6
PORTREVISION=	2
CATEGORIES=	mail
MASTER_SITES=	XCONTRIB/applications
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X-based interface to the Berkeley mail program

LICENSE=	mit

USES=		imake
USE_XORG=	xbitmaps xaw

.include <bsd.port.mk>
