# $MidnightBSD: mports/mbone/Makefile,v 1.3 2008/06/07 17:26:29 laffer1 Exp $
#

    COMMENT = MBone applications

SUBDIR += imm
SUBDIR += rat
SUBDIR += rtptools
SUBDIR += sdr
SUBDIR += speak_freely
SUBDIR += udpcast
SUBDIR += wb
SUBDIR += xspeakfree

.include <bsd.port.subdir.mk>
