# New ports collection makefile for:	openldap24-sasl-client
# Date created:				19 May 2006
# Whom:					Xin LI <delphij@FreeBSD.org>
#
# $MidnightBSD$
# $FreeBSD: ports/net/openldap24-sasl-client/Makefile,v 1.5 2006/05/26 02:44:24 delphij Exp $
#

CLIENT_ONLY=		sasl

MASTERDIR=		${.CURDIR}/../openldap24-server

.include "${MASTERDIR}/Makefile"
