PORTNAME=	hscolour
PORTVERSION=	1.25
PORTEPOCH=	1
CATEGORIES=	print haskell

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Colourise Haskell code
WWW=		http://code.haskell.org/~malcolm/hscolour/

LICENSE=	gpl2

USES=		cabal

CABAL_EXECUTABLES=	HsColour

.include <bsd.port.mk>
