# $MidnightBSD$

PORTNAME=	ilbc
DISTVERSION=	rfc3951
CATEGORIES=	net
MASTER_SITES=	http://simon.morlat.free.fr/download/1.2.x/source/

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Internet Low Bit Rate codec (RFC3951)

LICENSE=	unknown

CONFLICTS=	libilbc-[0-9]*

USES=	libtool
GNU_CONFIGURE=	yes
USE_LDCONFIG=	yes

.include <bsd.port.mk>
