# $MidnightBSD$
# $FreeBSD: head/devel/py-isort/Makefile 432169 2017-01-22 22:27:54Z rene $

PORTNAME=	isort
PORTVERSION=	4.2.5
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Python import sorter utility

LICENSE=	mit

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
