PORTNAME=	gdbm
PORTVERSION=	2.1.0
PORTEPOCH=	2
CATEGORIES=	databases rubygems
MASTER_SITES=	RG

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Ruby extension to GDBM library
WWW=		https://github.com/ruby/gdbm

LICENSE=	bsd2

LIB_DEPENDS=	libgdbm.so:databases/gdbm

USES=		gem

.include <bsd.port.mk>
