# $MidnightBSD: mports/x11/trapproto/Makefile,v 1.2 2012/03/03 01:52:54 laffer1 Exp $

PORTNAME=	trapproto
PORTVERSION=	3.4.3
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	DEC-XTRAP extension headers
LICENSE=	mit

XORG_CAT=	proto

USE_XORG=	xt:both

.include <bsd.port.mk>
