# $MidnightBSD: mports/graphics/poppler-utils/Makefile,v 1.3 2012/01/28 01:23:44 laffer1 Exp $

PORTREVISION=	0
PKGNAMESUFFIX=	-utils

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Poppler's xpdf-workalike command line utilities

MASTERDIR=	${.CURDIR}/../../graphics/poppler
SLAVEPORT=	utils
PLIST=	${.CURDIR}/pkg-plist

CONFLICTS=	xpdf-3.*

.include "${MASTERDIR}/Makefile"
