# Created by: Franco Fichtner <franco@opnsense.org>

PORTNAME=	em
PORTVERSION=	7.7.8
PORTREVISION=	0
PORTEPOCH=	0
MASTER_SITE_SUBDIR=	17509/eng

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Gigabit FreeBSD Base Drivers for Intel(R) Ethernet

MASTERDIR=	${.CURDIR}/../intel-ixl-kmod
PKGDIR=		${.CURDIR}
DISTINFO_FILE=	${.CURDIR}/distinfo
PATCHDIR=	${.CURDIR}/files

.include "${MASTERDIR}/Makefile"
