PORTNAME=	rubypants
PORTVERSION=	0.7.1
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Translates ASCII into smart typographic punctuation HTML entities
WWW=		https://github.com/jmcnevin/rubypants

LICENSE=	mit

USES=		gem

NO_ARCH=	yes

.include <bsd.port.mk>
