# $MidnightBSD: mports/games/Makefile,v 1.30 2008/12/14 03:33:33 ctriv Exp $
#

    COMMENT = Games

    SUBDIR += bass
    SUBDIR += battalion
    SUBDIR += cowsay
    SUBDIR += doom-data
    SUBDIR += doom-freedoom
    SUBDIR += doomlegacy
    SUBDIR += dopewars
    SUBDIR += fortunate
    SUBDIR += fotaq
    SUBDIR += ggz-client-libs
    SUBDIR += goonies
    SUBDIR += gtkpool
    SUBDIR += gtypist
    SUBDIR += kdegames3
    SUBDIR += libggz
    SUBDIR += lincity
    SUBDIR += linux-americasarmy
    SUBDIR += linux-enemyterritory
    SUBDIR += linux-enemyterritory-etpro
    SUBDIR += linux-enemyterritory-etpub
    SUBDIR += linux-enemyterritory-fortress
    SUBDIR += linux-enemyterritory-jaymod
    SUBDIR += linux-enemyterritory-omni-bot
    SUBDIR += linux-enemyterritory-shrub
    SUBDIR += linux-enemyterritory-tce
    SUBDIR += linux-quake3
    SUBDIR += linux-quake3-demo
    SUBDIR += moon-buggy
    SUBDIR += nextgo
    SUBDIR += oolite
    SUBDIR += pvpgn
    SUBDIR += qstat
    SUBDIR += quake3
    SUBDIR += quake3-data
    SUBDIR += scummvm
    SUBDIR += supertux
    SUBDIR += tuxracer
    SUBDIR += vitetris
    SUBDIR += wesnoth

.include <bsd.port.subdir.mk>
