# $MidnightBSD: mports/games/Makefile,v 1.21 2008/03/25 14:51:09 ctriv Exp $
#

    COMMENT = Games

    SUBDIR += bass
    SUBDIR += battalion
    SUBDIR += cowsay
    SUBDIR += doom-data
    SUBDIR += doom-freedoom
    SUBDIR += doomlegacy
    SUBDIR += dopewars
    SUBDIR += fortunate
    SUBDIR += fotaq
    SUBDIR += goonies
    SUBDIR += gtkpool
    SUBDIR += gtypist
    SUBDIR += kdegames3
    SUBDIR += lincity
    SUBDIR += linux-enemyterritory
    SUBDIR += linux-enemyterritory-etpro
    SUBDIR += linux-enemyterritory-etpub
    SUBDIR += linux-enemyterritory-fortress
    SUBDIR += linux-enemyterritory-jaymod
    SUBDIR += linux-enemyterritory-omni-bot
    SUBDIR += linux-enemyterritory-shrub
    SUBDIR += linux-enemyterritory-tce
    SUBDIR += nextgo
    SUBDIR += qstat
    SUBDIR += quake3
    SUBDIR += quake3-data
    SUBDIR += scummvm
    SUBDIR += tuxracer
    SUBDIR += vitetris
    SUBDIR += wesnoth

.include <bsd.port.subdir.mk>
