# New ports collection makefile for:	php5-bz2
# Date created:			7 Jul 2004
# Whom:				Alex Dupre <ale@FreeBSD.org>
#
# $FreeBSD: ports/archivers/php5-bz2/Makefile,v 1.1 2004/07/19 08:42:07 ale Exp $
# $MidnightBSD: mports/archivers/php5-bz2/Makefile,v 1.1 2006/11/05 15:46:59 laffer1 Exp $
#

CATEGORIES=	archivers

LICENSE=	php
MASTERDIR=	${.CURDIR}/../../lang/php5

PKGNAMESUFFIX=	-bz2

.include "${MASTERDIR}/Makefile"
