# $MidnightBSD$

PORTNAME=	xf86-video-sis
PORTVERSION=	0.10.9
PORTREVISION=	1
CATEGORIES=	x11-drivers

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X.Org sis display driver

LICENSE=	mit

USE_GL=		gl

XORG_CAT=	driver
USE_XORG=	xf86dgaproto

.include <bsd.port.mk>
