# $MidnightBSD$

PORTNAME=	Class-Gomor
PORTVERSION=	1.02
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Class and object builder
LICENSE=	perl

PERL_CONFIGURE=	yes

.include <bsd.port.mk>
