# $MidnightBSD: mports/deskutils/Makefile,v 1.18 2007/12/03 05:23:49 laffer1 Exp $
#

    COMMENT = Things that used to be on the desktop before computers were invented

    SUBDIR += etoile-addresseskit
    SUBDIR += etoile-dictionaryreader
    SUBDIR += etoile-extendedworkspacekit
    SUBDIR += etoile-hardware
    SUBDIR += etoile-inspectorkit
    SUBDIR += etoile-lookandbehavior
    SUBDIR += etoile-menuserver
    SUBDIR += etoile-outerspace
    SUBDIR += etoile-panekit
    SUBDIR += etoile-servicesbarkit
    SUBDIR += etoile-systemconfig
    SUBDIR += etoile-trackerkit
    SUBDIR += etoile-ui
    SUBDIR += gnome-utils
    SUBDIR += gnustep-notebook
    SUBDIR += gucharmap
    SUBDIR += gworkspace
    SUBDIR += jlj
    SUBDIR += linux-sunbird
    SUBDIR += ljclive
    SUBDIR += preferencepanes
    SUBDIR += preferences.app
    SUBDIR += toolbox
    SUBDIR += toolboxkit
    SUBDIR += xpad
    SUBDIR += xpostit

.include <bsd.port.subdir.mk>
