# $FreeBSD: ports/deskutils/Makefile,v 1.237 2006/09/25 02:12:48 dinoex Exp $
#

    COMMENT = Things that used to be on the desktop before computers were invented

    SUBDIR += etoile-addresseskit
    SUBDIR += etoile-dictionaryreader
    SUBDIR += etoile-extendedworkspacekit
    SUBDIR += etoile-hardware
    SUBDIR += etoile-inspectorkit
    SUBDIR += etoile-lookandbehavior
    SUBDIR += etoile-menuserver
    SUBDIR += etoile-outerspace
    SUBDIR += etoile-panekit
    SUBDIR += etoile-servicesbarkit
    SUBDIR += etoile-systemconfig
    SUBDIR += etoile-trackerkit
    SUBDIR += etoile-ui
    SUBDIR += gnome-utils
    SUBDIR += gucharmap
    SUBDIR += gworkspace
    SUBDIR += linux-sunbird
    SUBDIR += ljclive
    SUBDIR += preferencepanes
    SUBDIR += preferences.app
    SUBDIR += toolbox
    SUBDIR += toolboxkit

.include <bsd.port.subdir.mk>
