# $MidnightBSD: mports/converters/p5-Unicode-Map8/Makefile,v 1.1 2009/05/21 14:54:17 laffer1 Exp $

PORTNAME=	Unicode-Map8
PORTVERSION=	0.13
CATEGORIES=	converters perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Mapping table between 8-bit chars and Unicode
LICENSE=	perl

RUN_DEPENDS=	p5-Unicode-String>=2:${PORTSDIR}/converters/p5-Unicode-String

PERL_CONFIGURE=	yes

MAN1=		umap.1
MAN3=		Unicode::Map8.3

.include <bsd.port.mk>
