# $MidnightBSD$

PORTNAME=	viewres
PORTVERSION=	1.0.4
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Graphical class browser for Xt
LICENSE=	mit

XORG_CAT=	app
USE_XORG=	xt xaw

.include <bsd.port.mk>
