PORTNAME=	tty-color
PORTVERSION=	0.6.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Terminal color capabilities detection
WWW=		https://ttytoolkit.org/ \
		https://github.com/piotrmurach/tty-color

LICENSE=	mit
LICENSE_FILE=	${WRKSRC}/LICENSE.txt

USES=		gem

NO_ARCH=	yes

.include <bsd.port.mk>
