# New ports collection makefile for:    p5-Convert-BinHex
# Date created:         2004-03-23
# Whom:                 Jan-Peter Koopmann <j.koopmann@seceidos.de>
#
# $MidnightBSD: mports/converters/p5-Convert-BinHex/Makefile,v 1.1 2007/03/20 19:25:29 laffer1 Exp $
# $FreeBSD: ports/converters/p5-Convert-BinHex/Makefile,v 1.2 2006/06/25 16:38:39 clsung Exp $
#

PORTNAME=	Convert-BinHex
PORTVERSION=	1.119
CATEGORIES=	converters perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	Convert
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Perl module to extract data from Macintosh BinHex files
LICENSE=	gpl2

PERL_CONFIGURE=	yes

MAN3=		Convert::BinHex.3

.include <bsd.port.mk>
