# $FreeBSD: ports/textproc/wv2/Makefile,v 1.17 2006/05/27 10:26:18 lofi Exp $
# $MidnightBSD: mports/textproc/wv2/Makefile,v 1.5 2009/09/20 02:22:58 laffer1 Exp $
#

PORTNAME=	wv2
PORTVERSION=	0.4.2
CATEGORIES=	textproc
MASTER_SITES=	SF/wvware/

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	A library providing routines to access Microsoft Word files
LICENSE=	lgpl

USE_GNOME=	gnometarget libgsf
USE_ICONV=	yes
USE_BZIP2=	yes
USE_CMAKE=	yes
USE_GMAKE=	yes
USE_LDCONFIG=	yes

.include <bsd.port.mk>
