# $MidnightBSD: mports/x11-drivers/xf86-video-vesa/Makefile,v 1.5 2012/03/03 22:23:47 laffer1 Exp $

PORTNAME=	xf86-video-vesa
PORTVERSION=	2.3.0
PORTREVISION=	1
CATEGORIES=	x11-drivers

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X.Org vesa display driver
LICENSE=	mit

XORG_CAT=	driver
USE_XORG=	xextproto videoproto
MAN4=		vesa.4x

.include <bsd.port.mk>
