# $MidnightBSD: mports/net/p5-URI/Makefile,v 1.3 2010/05/26 01:27:16 laffer1 Exp $

PORTNAME=	URI
PORTVERSION=	1.60
CATEGORIES=	net perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:GAAS
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Perl5 interface to Uniform Resource Identifier (URI) references

LICENSE=	perl

PERL_CONFIGURE=	yes

MAN3=		URI.3 \
		URI::Escape.3 \
		URI::Heuristic.3 \
		URI::QueryParam.3 \
		URI::Split.3 \
		URI::URL.3 \
		URI::WithBase.3 \
		URI::_punycode.3 \
		URI::data.3 \
		URI::file.3 \
		URI::ldap.3

.include <bsd.port.mk>
