# New ports collection makefile for:	xgc
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11/xgc/Makefile,v 1.1 2007/05/19 20:27:54 flz Exp $
# $MidnightBSD$
#

PORTNAME=	xgc
PORTVERSION=	1.0.1
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X graphics demo
LICENSE=	x11

XORG_CAT=	app
USE_XORG=	xt xaw

MAN1=		xgc.1

.include <bsd.port.mk>
