# $MidnightBSD: mports/x11-fonts/font-bh-type1/Makefile,v 1.1 2007/10/11 19:29:33 ctriv Exp $

PORTNAME=	font-bh-type1
PORTVERSION=	1.0.0
CATEGORIES=	x11-fonts

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X.Org Bigelow Holmes Type1 font
LICENSE=	unknown

XORG_CAT=	font

.include <bsd.port.mk>
