# $MidnightBSD: mports/x11-fonts/font-bh-type1/Makefile,v 1.2 2009/04/04 15:20:42 laffer1 Exp $

PORTNAME=	font-bh-type1
PORTVERSION=	1.0.3
CATEGORIES=	x11-fonts

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X.Org Bigelow Holmes Type1 font
LICENSE=	unknown

XORG_CAT=	font

.include <bsd.port.mk>
