# $MidnightBSD$
# $FreeBSD: ports/devel/automake-wrapper/Makefile,v 1.1 2007/07/28 06:33:45 ade Exp $

PORTNAME=	automake-wrapper

COMMENT=	Wrapper script for GNU automake

MASTERDIR=	${.CURDIR}/../../devel/autoconf-wrapper
PKGDIR=		${.CURDIR}

TOOL=		AUTOMAKE
WRAPPED_TOOLS=	aclocal automake

.include "${MASTERDIR}/Makefile"
