# $MidnightBSD: mports/converters/Makefile,v 1.18 2008/05/31 03:04:54 laffer1 Exp $
#

    COMMENT = Character code converters

    SUBDIR += fribidi
    SUBDIR += libiconv
    SUBDIR += mpack
    SUBDIR += p5-Convert-ASN1
    SUBDIR += p5-Convert-BinHex
    SUBDIR += p5-Encode
    SUBDIR += p5-Encode-Detect
    SUBDIR += p5-JSON
    SUBDIR += p5-MIME-Base32
    SUBDIR += p5-MIME-Base64
    SUBDIR += p5-Text-Iconv
    SUBDIR += p5-Unicode-String
    SUBDIR += pecl-fribidi
    SUBDIR += php5-iconv
    SUBDIR += php5-mbstring
    SUBDIR += php5-recode
    SUBDIR += psiconv
    SUBDIR += recode
    SUBDIR += ruby-iconv
    SUBDIR += unix2dos
    SUBDIR += uulib

.include <bsd.port.subdir.mk>
