# $MidnightBSD: mports/converters/Makefile,v 1.4 2006/11/25 03:59:55 laffer1 Exp $
#

    COMMENT = Character code converters

    SUBDIR += fribidi
    SUBDIR += libiconv
    SUBDIR += p5-MIME-Base64
    SUBDIR += php5-mbstring
    SUBDIR += unix2dos

.include <bsd.port.subdir.mk>
