PORTNAME=	u2f
PORTVERSION=	1.0.0
CATEGORIES=	net rubygems
MASTER_SITES=	RG

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Library for handling registration and authentication of U2F devices
WWW=		https://github.com/castle/ruby-u2f

LICENSE=	mit
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		gem

NO_ARCH=	yes

.include <bsd.port.mk>
