# Created by: Po-Chuan Hsieh <sunpoet@FreeBSD.org>

PORTNAME=	cryptography-vectors
PORTVERSION=	3.3.2
CATEGORIES=	security python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	cryptography_vectors-${PORTVERSION}

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Test vectors for the cryptography package

LICENSE=	apache2 bsd3
LICENSE_COMB=	dual

USES=		python:3.6+
USE_PYTHON=	autoplist concurrent distutils

NO_ARCH=	yes

.include <bsd.port.mk>
