PORTNAME=	Net_URL
PORTVERSION=	1.0.15
CATEGORIES=	net www

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Easy parsing of URLs
WWW=		https://pear.php.net/package/Net_URL

LICENSE=	bsd3

USES=		pear
NO_ARCH=	yes

.include <bsd.port.mk>
