# $MidnightBSD: mports/x11/xclipboard/Makefile,v 1.1 2007/10/04 21:25:14 ctriv Exp $

PORTNAME=	xclipboard
PORTVERSION=	1.0.1
PORTREVISION=	1
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X clipboard client
LICENSE=	x11

XORG_CAT=	app
USE_XORG=	xt xaw

MAN1=		xclipboard.1 xcutsel.1

.include <bsd.port.mk>
