# New ports collection makefile for:    MySQL-scripts
#
# $MidnightBSD: mports/databases/mysql50-scripts/Makefile,v 1.1 2006/10/03 20:58:54 laffer1 Exp $
# $FreeBSD: ports/databases/mysql50-scripts/Makefile,v 1.7 2006/03/17 07:06:38 ale Exp $
#

PORTNAME=	mysql
PKGNAMESUFFIX=	-scripts

COMMENT=	Multithreaded SQL database (scripts)

MASTERDIR=	${.CURDIR}/../mysql50-server

PKGINSTALL=	mustnotexist
PKGMESSAGE=	mustnotexist
PLIST=		${PKGDIR}/pkg-plist.scripts

SCRIPTS_ONLY=	yes

.include "${MASTERDIR}/Makefile"
