# $MidnightBSD: mports/print/Makefile,v 1.11 2007/01/03 22:14:13 laffer1 Exp $
#

    COMMENT = Desktop publishing

    SUBDIR += acroread7
    SUBDIR += acroreadwrapper
    SUBDIR += cups-base
    SUBDIR += enscript-a4
    SUBDIR += enscript-letter
    SUBDIR += fontforge
    SUBDIR += freetype2
    SUBDIR += ghostscript-gpl
    SUBDIR += ghostscript-gpl-nox11
    SUBDIR += gsfonts
    SUBDIR += pdflib
    SUBDIR += pecl-pdflib
    SUBDIR += wmlpq

.include <bsd.port.subdir.mk>
