# $MidnightBSD: mports/print/Makefile,v 1.33 2007/09/01 19:53:39 laffer1 Exp $
#

    COMMENT = Desktop publishing

    SUBDIR += a2ps-letter
    SUBDIR += acroread7
    SUBDIR += acroreadwrapper
    SUBDIR += adobe-cmaps
    SUBDIR += amspsfnt
    SUBDIR += cm-super
    SUBDIR += cmpsfont
    SUBDIR += cups
    SUBDIR += cups-base
    SUBDIR += cups-pstoraster
    SUBDIR += dvipdfmx
    SUBDIR += dvipsk-tetex
    SUBDIR += enscript-a4
    SUBDIR += enscript-letter
    SUBDIR += fontforge
    SUBDIR += freetype
    SUBDIR += freetype-tools
    SUBDIR += freetype2
    SUBDIR += ghostscript-afpl
    SUBDIR += ghostscript-gpl
    SUBDIR += ghostscript-gpl-nox11
    SUBDIR += gimp-print
    SUBDIR += gsfonts
    SUBDIR += gv
    SUBDIR += jadetex
    SUBDIR += libgnomecups
    SUBDIR += libgnomeprint
    SUBDIR += libgnomeprint-reference
    SUBDIR += libijs
    SUBDIR += libpaper
    SUBDIR += pdflib
    SUBDIR += pecl-pdflib
    SUBDIR += t1utils
    SUBDIR += teTeX
    SUBDIR += teTeX-base
    SUBDIR += teTeX-texmf
    SUBDIR += tex-texmflocal
    SUBDIR += ttf2pt1
    SUBDIR += wmlpq
    SUBDIR += xdvik

.include <bsd.port.subdir.mk>
