# $MidnightBSD$
# $FreeBSD: head/converters/php71-iconv/Makefile 432324 2017-01-24 11:54:20Z tz $

CATEGORIES=	converters

MASTERDIR=	${.CURDIR}/../../lang/php71

PKGNAMESUFFIX=	-iconv

.include "${MASTERDIR}/Makefile"
