PORTNAME=	lpSolve
DISTVERSION=	5.6.23
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Interface to 'Lp_solve' v. 5.5 to Solve Linear/Integer Programs
WWW=		https://cran.r-project.org/web/packages/lpSolve/

LICENSE=	lgpl

LIB_DEPENDS=	liblpsolve55.so:math/lp_solve

USES=		cran:auto-plist,compiles

.include <bsd.port.mk>
