PORTNAME=	Data-Binary
PORTVERSION=	0.01
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Simple detection of binary versus text in strings
WWW=		https://metacpan.org/release/Data-Binary

LICENSE=	artistic2

USES=		perl5
USE_PERL5=	configure

NO_ARCH=	yes

.include <bsd.port.mk>
