# $MidnightBSD$

PORTNAME=	libxml2
PORTVERSION=	2.7.6
CATEGORIES=	textproc linux

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Library providing XML and HTML support (Linux CentOS ${LINUX_DIST_VER})

LICENSE=	mit

DESCR=		${.CURDIR}/../${PORTNAME}/pkg-descr
RPMVERSION=	21.el6_8.1
USES=		linux:c6
USE_LDCONFIG=	yes
USE_LINUX_RPM=	yes

OPTIONS_DEFINE=	DOCS

.include <bsd.port.mk>
