# $FreeBSD: ports/x11-fonts/font-misc-ethiopic/Makefile,v 1.1 2007/05/19 20:29:16 flz Exp $
# $MidnightBSD: mports/x11-fonts/font-misc-ethiopic/Makefile,v 1.2 2011/05/08 17:37:29 laffer1 Exp $

PORTNAME=	font-misc-ethiopic
PORTVERSION=	1.0.3
CATEGORIES=	x11-fonts

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X.Org miscellaneous Ethiopic font
LICENSE=	mit

XORG_CAT=	font
INSTALLS_TTF=	yes
FONTDIR=	TTF OTF

.include <bsd.port.mk>
