# $MidnightBSD: mports/x11-drivers/xf86-video-cirrus/Makefile,v 1.3 2011/05/07 21:17:50 laffer1 Exp $

PORTNAME=	xf86-video-cirrus
PORTVERSION=	1.3.2
CATEGORIES=	x11-drivers

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X.Org cirrus display driver
LICENSE=	mit

XORG_CAT=	driver
USE_XORG=	videoproto xextproto
MAN4=		cirrus.4x

.include <bsd.port.mk>
