# $MidnightBSD$

PORTNAME=	xf86-video-chips
PORTVERSION=	1.2.7
CATEGORIES=	x11-drivers

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X.Org chips display driver

LICENSE=	mit

XORG_CAT=	driver
USE_XORG=	videoproto xextproto

.include <bsd.port.mk>
