PORTNAME=	marcel
PORTVERSION=	1.1.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Simple mime type detection
WWW=		https://github.com/rails/marcel

LICENSE=	mit
LICENSE_FILE=	${WRKSRC}/MIT-LICENSE

USES=		gem

NO_ARCH=	yes

.include <bsd.port.mk>
