# $MidnightBSD: mports/x11/libxkbfile/Makefile,v 1.3 2011/05/07 00:30:34 laffer1 Exp $

PORTNAME=	libxkbfile
PORTVERSION=	1.0.7
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	XKB file library
LICENSE=	sgi

XORG_CAT=	lib
USE_XORG=	x11 kbproto:both

.include <bsd.port.mk>
