PORTNAME=	bsdisks
DISTVERSION=	0.31
CATEGORIES=	sysutils

MAINTAINER=	ports@MidnightBSD>org
COMMENT=	UDisks2 service implementation for SD
WWW=		https://foss.heptapod.net/bsdutils/bsdisks

LICENSE=	bsd3

USES=		cmake compiler:c++11-lang qt:5

USE_QT=		qmake:build buildtools:build core dbus

USE_GITLAB=		yes
GL_SITE=		https://foss.heptapod.net
GL_ACCOUNT=		bsdutils
GL_TAGNAME=		2f5de587db9c726425898bccdd6a3bdd7fee655b

.include <bsd.port.mk>
