# $MidnightBSD$

PORTNAME=	libtasn1
PORTVERSION=	2.3
CATEGORIES=	security linux

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	ASN.1 structure parser library (Linux CentOS ${LINUX_DIST_VER})

LICENSE=	lgpl2.1

DESCR=		${.CURDIR}/../${PORTNAME}/pkg-descr
RPMVERSION=	6.el6_5
USES=		cpe linux:c6
CPE_VENDOR=	gnu
USE_LDCONFIG=	yes
USE_LINUX_RPM=	yes

OPTIONS_DEFINE=	DOCS

.include <bsd.port.mk>
