PORTNAME=	Log-Log4perl
PORTVERSION=	1.49
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Log4j implementation for Perl

LICENSE=	artistic gpl
LICENSE_COMB=	dual

USES=		perl5 shebangfix
SHEBANG_FILES=	lib/Log/Log4perl/Layout/PatternLayout/Multiline.pm
USE_PERL5=	configure
NO_ARCH=	yes

.include <bsd.port.mk>
