PORTNAME=	unix-selfauth-helper
DISTVERSION=	1.0.1
DISTVERSIONPREFIX=	v
CATEGORIES=	security

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Local self-authentication for pam_exec
WWW=		https://github.com/Zirias/unix-selfauth-helper

LICENSE=	bsd2

USES=		uidfix

USE_GITHUB=	yes
GH_ACCOUNT=	Zirias

PLIST_FILES=	libexec/unix-selfauth-helper \
		man/man8/unix-selfauth-helper.8.gz

.include <bsd.port.mk>
