PORTNAME=	Math-BigInt
PORTVERSION=	2.003002
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Arbitrary size integer math perl package
WWW=		https://metacpan.org/release/Math-BigInt

LICENSE=	artistic gpl+
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

NO_ARCH=	yes

.include <bsd.port.mk>
