# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/databases/php56-pdo_dblib/Makefile 367268 2014-09-04 14:24:25Z ale $

CATEGORIES=	databases

MASTERDIR=	${.CURDIR}/../../lang/php56

PKGNAMESUFFIX=	-pdo_dblib

.include "${MASTERDIR}/Makefile"
