# $MidnightBSD: mports/x11-drivers/xf86-input-acecad/Makefile,v 1.4 2009/04/07 15:26:21 crash Exp $

PORTNAME=	xf86-input-acecad
PORTVERSION=	1.3.0
PORTREVISION=	1
CATEGORIES=	x11-drivers

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X.Org acecad input driver
LICENSE=	x11

XORG_CAT=	driver
MAN4=		acecad.4x

.include <bsd.port.mk>
