# $FreeBSD: head/multimedia/gstreamer1-plugins-mpeg2enc/Makefile 375225 2014-12-22 10:22:38Z kwm $

PORTREVISION=	0
CATEGORIES=	multimedia

COMMENT=	Gstreamer mpeg encoder plugin

GST_PLUGIN=	mpeg2enc
DIST=		bad

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
