# $MidnightBSD: mports/dns/Makefile,v 1.12 2007/11/11 23:25:35 laffer1 Exp $
#

    COMMENT = Domain Name Service tools

    SUBDIR += ares
    SUBDIR += bind9
    SUBDIR += bind94
    SUBDIR += bind95
    SUBDIR += c-ares
    SUBDIR += ddclient
    SUBDIR += ez-ipupdate
    SUBDIR += inadyn
    SUBDIR += libidn
    SUBDIR += mdnsd
    SUBDIR += nslint
    SUBDIR += p5-Net-DNS
    SUBDIR += p5-Net-DNS-Resolver-Programmable

.include <bsd.port.subdir.mk>
