PORTNAME=	unicode-emoji
PORTVERSION=	4.2.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Provide Unicode Emoji data and regexes
WWW=		https://github.com/janlelis/unicode-emoji

LICENSE=	mit
LICENSE_FILE=	${WRKSRC}/MIT-LICENSE.txt

USES=		gem

NO_ARCH=	yes

.include <bsd.port.mk>
