# New ports collection makefile for:	p5-Encode-Detect
# Date created:		2006-07-10
# Whom:			Gea-Suan Lin <gslin@gslin.org>
#
# $MidnightBSD$
# $FreeBSD: ports/converters/p5-Encode-Detect/Makefile,v 1.2 2006/11/21 12:12:31 sumikawa Exp $
#

PORTNAME=	Encode-Detect
PORTVERSION=	1.00
CATEGORIES=	converters perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	Encode
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	An Encode::Encoding subclass that detects the encoding of data

PERL_MODBUILD=	yes

MAN3=		Encode::Detect.3 Encode::Detect::Detector.3

.include <bsd.port.mk>
