# New ports collection makefile for:	linux-thunderbird
# Date created:		17 April 2006
# Whom:			Andrew Pantyukhin <infofarmer@FreeBSD.org>
#
# $MidnightBSD: mports/mail/linux-thunderbird/Makefile,v 1.2 2006/09/27 13:54:06 laffer1 Exp $
# $FreeBSD: ports/mail/linux-thunderbird/Makefile,v 1.6 2006/07/30 00:09:53 sat Exp $
#

PORTNAME=	thunderbird
PORTVERSION=	1.5.0.8
PORTREVISION=	1
CATEGORIES=	mail
MASTER_SITE_SUBDIR?=	${PORTNAME}/releases/${PORTVERSION}/linux-i686/en-US

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Mozilla Thunderbird is standalone mail and news that stands above

.include "${.CURDIR}/../../www/linux-seamonkey/Makefile.common"
.include <bsd.port.mk>
