# Created by: Koop Mast <kwm@FreeBSD.org>
# $MidnightBSD$

PORTNAME=	gnome-video-effects
PORTVERSION=	0.4.1
CATEGORIES=	graphics
MASTER_SITES=	GNOME

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Collection of Gstreamer effects

LICENSE=	gpl2

USE_GNOME=	intlhack
USES=		gettext gmake pathfix tar:xz
GNU_CONFIGURE=	yes

.include <bsd.port.mk>
