# New ports collection makefile for:	xf86-input-magellan
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11-drivers/xf86-input-magellan/Makefile,v 1.2 2007/09/13 19:44:48 flz Exp $
# $MidnightBSD$
#

PORTNAME=	xf86-input-magellan
PORTVERSION=	1.1.1
CATEGORIES=	x11-drivers

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X.Org magellan input driver
LICENSE=	x11

XORG_CAT=	driver

.include <bsd.port.mk>
