# $MidnightBSD$

PORTNAME=	Math-BigInt
PORTVERSION=	1.997
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:PJACKLAM
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Math::BigInt - Arbitrary size integer math package
LICENSE=	perl

PERL_CONFIGURE=	yes

MAN3=		Math::BigFloat.3 \
		Math::BigInt.3 \
		Math::BigInt::Calc.3 \
		Math::BigInt::CalcEmu.3

.include <bsd.port.mk>

