# $MidnightBSD: mports/x11/Makefile,v 1.10 2006/10/02 03:55:53 archite Exp $
#

    COMMENT = Ports to support the X window system

    SUBDIR += dgs
    SUBDIR += docker
    SUBDIR += libX11
    SUBDIR += libXau
    SUBDIR += libXdmcp
    SUBDIR += libXext
    SUBDIR += libXtrans
    SUBDIR += libXxf86
    SUBDIR += linux-xorg-libs
    SUBDIR += nvidia-driver
    SUBDIR += slim
    SUBDIR += nvidia-xconfig
    SUBDIR += startup-notification
    SUBDIR += terminal.app
    SUBDIR += wdm
    SUBDIR += xextentions
    SUBDIR += xf86ext
    SUBDIR += xorg
    SUBDIR += xorg-clients
    SUBDIR += xorg-documents
    SUBDIR += xorg-libraries
    SUBDIR += xorg-manpages
    SUBDIR += xproto
    SUBDIR += xterm

.include <bsd.port.subdir.mk>
