# $MidnightBSD: mports/devel/wizardkit/Makefile,v 1.4 2008/10/20 19:31:22 laffer1 Exp $

PORTNAME=	wizardkit
PORTVERSION=	0.1
PORTREVISION=	1
CATEGORIES=	devel
MASTER_SITES=	http://download.gna.org/pmanager/0.2/
DISTNAME=	WizardKit-${PORTVERSION}

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Framework needed by Project Manager
LICENSE=	agg

USE_BZIP2=	yes
USE_GNUSTEP=	yes
USE_GNUSTEP_BACK=	yes
USE_GNUSTEP_BUILD=	yes
USE_GNUSTEP_INSTALL=	yes
USE_GNUSTEP_LDCONFIG=	${GNUSTEP_LOCAL_LIBRARIES}

.include <bsd.port.mk>
