# Created by: Yuri Victorovich <yuri@rawbw.com>

PORTNAME=	contextlib2
DISTVERSION=	0.6.0.post1
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Backports and enhancements for the contextlib module

LICENSE=	bsd2

USES=		python:3.6+
USE_PYTHON=	autoplist distutils

NO_ARCH=	yes

.include <bsd.port.mk>
