# $MidnightBSD$

PORTNAME=	xf86-video-s3
PORTVERSION=	0.6.3
CATEGORIES=	x11-drivers

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X.Org s3 display driver
LICENSE=	mit

XORG_CAT=	driver
USE_XORG=	videoproto xextproto
MAN4=		s3.4x

.include <bsd.port.mk>
