PORTNAME=	xf86-video-s3
PORTVERSION=	0.7.0
PORTREVISION=	1
CATEGORIES=	x11-drivers

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X.Org s3 display driver

LICENSE=	mit
LICENSE_FILE=	${WRKSRC}/COPYING

USES=		xorg-cat:driver

.include <bsd.port.mk>
