# $MidnightBSD: mports/accessibility/Makefile,v 1.16 2009/10/31 23:40:07 laffer1 Exp $
    
COMMENT = Ports to help disabled users

SUBDIR += at-poke
SUBDIR += at-spi
SUBDIR += at-spi-reference
SUBDIR += atk
SUBDIR += atk-reference
SUBDIR += dasher
SUBDIR += gnome-mag
SUBDIR += gnome-speech
SUBDIR += gok
SUBDIR += kdeaccessibility
SUBDIR += kdeaccessibility4
SUBDIR += linux-atk
SUBDIR += orca
SUBDIR += qt4-accessible

.include <bsd.port.subdir.mk>
