# $MidnightBSD: mports/accessibility/Makefile,v 1.9 2008/01/01 20:51:03 laffer1 Exp $
# $FreeBSD: ports/accessibility/Makefile,v 1.11 2006/05/28 00:57:23 mezz Exp $
#

    COMMENT = Ports to help disabled users

    SUBDIR += at-poke
    SUBDIR += at-spi
    SUBDIR += at-spi-reference
    SUBDIR += atk
    SUBDIR += atk-reference
    SUBDIR += gail
    SUBDIR += gail-reference
    SUBDIR += gnome-speech
    SUBDIR += kdeaccessibility
    SUBDIR += linux-atk

.include <bsd.port.subdir.mk>
