PORTNAME=	libXxf86vm
PORTVERSION=	1.1.5
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X Vidmode Extension

LICENSE=	mit

USES=		tar:xz cpe xorg xorg-cat:lib
USE_XORG=	xorgproto x11 xext
CPE_PRODUCT=	libxxf86vm
CPE_VENDOR=	x

.include <bsd.port.mk>
