# $MidnightBSD$

PORTNAME=	lrzsz
PORTVERSION=	0.12.20
PORTREVISION=	3
CATEGORIES=	comms
MASTER_SITES=	http://ohse.de/uwe/releases/

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Receive/Send files via X/Y/ZMODEM protocol.  (unrestrictive)

LICENSE=	gpl2

GNU_CONFIGURE=	yes
ALL_TARGET=	all # vcheck

.include <bsd.port.mk>
