# $MidnightBSD: mports/devel/php5-gettext/Makefile,v 1.1 2006/12/04 05:04:08 laffer1 Exp $

CATEGORIES=	devel

MASTERDIR=	${.CURDIR}/../../lang/php5

PKGNAMESUFFIX=	-gettext

.include "${MASTERDIR}/Makefile"
