# New ports collection makefile for:	german/acroread
# Date created:			2005-10-05
# Whom:				trevor
#
# $FreeBSD: ports/german/acroread/Makefile,v 1.6 2006/08/02 05:05:36 hrs Exp $
# $MidnightBSD$
#

PORTVERSION=	7.0.8
PORTREVISION=	0
PORTEPOCH=	1
CATEGORIES=	german print linux
MASTERDIR=	${.CURDIR}/../../print/acroread7
MD5_FILE=	${.CURDIR}/distinfo

ADOBE_LANG=	DEU

.include "${MASTERDIR}/Makefile"
