PORTNAME=	eventmachine
PORTVERSION=	1.2.7
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Fast, simple event-processing library for Ruby programs
WWW=		https://rubyeventmachine.com

LICENSE=	gpl2 ruby
LICENSE_COMB=	dual
LICENSE_FILE_gpl2=	${WRKSRC}/GNU
LICENSE_FILE_ruby=	${WRKSRC}/LICENSE

USES=		gem ssl

.include <bsd.port.mk>
