# $MidnightBSD$

PORTNAME=	kbproto
PORTVERSION=	1.0.7
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	KB extension headers

LICENSE=	sgi
LICENSE_FILE=	${WRKSRC}/COPYING

XORG_CAT=	proto

.include <bsd.port.mk>
