# $MidnightBSD$

PORTNAME=	comserv
PORTVERSION=	1.4.3
CATEGORIES=	comms net
MASTER_SITES=	${MASTER_SITE_FREEBSD_LOCAL}
MASTER_SITE_SUBDIR=	bsd

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Provide network access to local serial ports and make remote ports appear local

LICENSE=	bsd2

.include <bsd.port.mk>
