# New ports collection makefile for:	xfce4-icon-theme
# Date created:				12 October 2004
# Whom:					Oliver Lehmann <oliver@FreeBSD.org>
#
# $MidnightBSD$
# $FreeBSD: ports/x11-themes/xfce4-icon-theme/Makefile,v 1.16 2008/06/06 14:14:41 edwin Exp $
#

PORTNAME=	xfce4-icon-theme
PORTVERSION=	4.4.2
CATEGORIES=	x11-themes xfce
MASTER_SITES=	${MASTER_SITE_XFCE}
DIST_SUBDIR=	xfce4

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Icon themes for XFce 4
LICENSE=	unknown

GNU_CONFIGURE=	yes
INSTALLS_ICONS=	yes
USE_BZIP2=	yes
USE_GETTEXT=	yes
USE_GMAKE=	yes
USE_GNOME=	gnomehack gnometarget intltool intlhack
USE_XFCE=	configenv
WANT_GNOME=	yes

.include <bsd.port.mk>
