# $FreeBSD: head/audio/gstreamer1-plugins-faac/Makefile 375225 2014-12-22 10:22:38Z kwm $

PORTREVISION=	0
CATEGORIES=	audio

COMMENT=	Gstreamer MPEG-2 and MPEG-4 AAC encoder plugin

GST_PLUGIN=	faac
DIST=		bad

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
