# $MidnightBSD: mports/x11/xbitmaps/Makefile,v 1.5 2011/09/20 23:37:07 laffer1 Exp $

PORTNAME=	xbitmaps
PORTVERSION=	1.1.1
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X.Org bitmaps data
LICENSE=	mit

CONFLICTS=	xorg-libraries-6.*

USE_GNOME=	gnomehack

XORG_CAT=	data

.include <bsd.port.mk>
