# $MidnightBSD: mports/deskutils/Makefile,v 1.48 2011/05/28 04:52:48 laffer1 Exp $

COMMENT = Things that used to be on the desktop before computers were invented

SUBDIR += appwrapper
SUBDIR += deskbar-applet
SUBDIR += drivel
SUBDIR += etoile-addresseskit
SUBDIR += etoile-corner
SUBDIR += etoile-dictionaryreader
SUBDIR += etoile-distributedview
SUBDIR += etoile-extendedworkspacekit
SUBDIR += etoile-hardware
SUBDIR += etoile-inspectorkit
SUBDIR += etoile-lookandbehavior
SUBDIR += etoile-menuserver
SUBDIR += etoile-outerspace
SUBDIR += etoile-panekit
SUBDIR += etoile-servicemenulet
SUBDIR += etoile-scriptservices
SUBDIR += etoile-servicesbarkit
SUBDIR += etoile-systemconfig
SUBDIR += etoile-trackerkit
SUBDIR += etoile-ui
SUBDIR += glabels
SUBDIR += gnome-utils
SUBDIR += gnustep-notebook
SUBDIR += gnuwash
SUBDIR += gtkjj
SUBDIR += gucharmap
SUBDIR += gworkspace
SUBDIR += hamster-applet
SUBDIR += hot-babe
SUBDIR += javajj
SUBDIR += jjclient
SUBDIR += jlj
SUBDIR += kbirthday
SUBDIR += kdepim3
SUBDIR += kdepim4
SUBDIR += kdepimlibs4
SUBDIR += kdeplasma-addons
SUBDIR += linux-sunbird
SUBDIR += ljclive
SUBDIR += menumaker
SUBDIR += notification-daemon
SUBDIR += orage
SUBDIR += planner
SUBDIR += preferencepanes
SUBDIR += preferences.app
SUBDIR += strigi
SUBDIR += toolbox
SUBDIR += toolboxkit
SUBDIR += vnc2flv
SUBDIR += xpad
SUBDIR += xpostit

.include <bsd.port.subdir.mk>
