--- pyproject.toml.orig	2026-06-23 18:53:02 UTC
+++ pyproject.toml
@@ -3,3 +3,1 @@ requires = [
-	"setuptools>=77",
+	"setuptools>=61",
-	# jaraco/skeleton#174
-	"coherent.licensed",
@@ -24,1 +22,1 @@ requires-python = ">=3.10"
-license = "Apache-2.0"
+license = {text = "Apache-2.0"}
