# $MidnightBSD$

PORTNAME=	common-sense
PORTVERSION=	3.6
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:MLEHMANN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Perl common defaults with lower memory usage
LICENSE=	perl

PERL_CONFIGURE=	yes

.include <bsd.port.mk>
