# ex:ts=8
# ports collection makefile for:	cscope
# Date created:		1998-11-21
# Whom:			Castor Fu
#
# $MidnightBSD$
# $FreeBSD: ports/devel/cscope/Makefile,v 1.27 2006/11/01 11:23:29 miwi Exp $
#

PORTNAME=	cscope
PORTVERSION=	15.6
PORTREVISION=	0
CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE}
MASTER_SITE_SUBDIR=	${PORTNAME}

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	An interactive C program browser

GNU_CONFIGURE=	yes
CONFIGURE_ARGS=	--with-yacc

MAN1=		cscope.1

.include <bsd.port.mk>
