# Created by: Mathieu Arnold <m@absolight.net>

PORTNAME=	Pod-Simple
PORTVERSION=	3.35
CATEGORIES=	textproc devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Framework for parsing Pod

LICENSE=	artistic gpl
LICENSE_COMB=	dual

PORTSCOUT=	limit:^[0-9\.]*$$

NO_ARCH=	yes
USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
