--- pyproject.toml.orig
+++ pyproject.toml
@@ -1,7 +1,6 @@
 [build-system]
 requires = [
-    # Required for PEP 639 support
-    "setuptools >= 77.0.3"
+    "setuptools >= 61"
 ]
 build-backend = "setuptools.build_meta"
 
@@ -16,8 +15,7 @@
 
 description = "Foreign Function Interface for Python calling C code."
 readme = "README.md"
-license = "MIT-0"
-license-files = ["LICENSE"]
+license = {text = "MIT-0"}
 classifiers = [
     "Programming Language :: Python",
    "Programming Language :: Python :: 3",
