PORTNAME=	logger
PORTVERSION=	1.7.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG
PKGNAMESUFFIX=	-gitlab

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Simple logging utility for outputting messages
WWW=		https://github.com/ruby/logger

LICENSE=	bsd2 ruby
LICENSE_COMB=	dual
LICENSE_FILE_bsd2=${WRKSRC}/BSDL
LICENSE_FILE_ruby=	${WRKSRC}/COPYING

USES=		gem

NO_ARCH=	yes

.include <bsd.port.mk>
