# $MidnightSD$
# $FreeBSD: ports/dns/linux-f10-libasyncns/Makefile,v 1.1 2010/02/04 08:25:54 itetcu Exp $

PORTNAME=	libasyncns
PORTVERSION=	0.7
CATEGORIES=	dns devel linux
PKGNAMEPREFIX=	linux-f10-
DISTNAME=	${PORTNAME}-${PORTVERSION}-${RPMVERSION}

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	C library for executing DNS queries asynchronously (Linux Fedora 10)
LICENSE=	lgpl

USE_LINUX_RPM=	yes
LINUX_DIST_VER=	10
RPMVERSION=	1.fc10
USE_LDCONFIG=	yes
AUTOMATIC_PLIST=yes

.include <bsd.port.mk>
