# $MidnightBSD: mports/x11-fonts/xfontsel/Makefile,v 1.3 2012/03/03 23:17:19 laffer1 Exp $

PORTNAME=	xfontsel
PORTVERSION=	1.0.5
CATEGORIES=	x11-fonts

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Point and click selection of X11 font names
LICENSE=	mit

XORG_CAT=	app
USE_XORG=	xt xaw

MAN1=		xfontsel.1

.include <bsd.port.mk>
