# New ports collection makefile for:	asmodem
# Date created:		11 May 1998
# Whom:			Sean Cole <scole@aracnet.com>
#
# $MidnightBSD$
# $FreeBSD: ports/comms/asmodem/Makefile,v 1.14 2008/04/19 17:47:05 miwi Exp $
#

PORTNAME=	asmodem
PORTVERSION=	0.6.1
CATEGORIES=	comms
MASTER_SITES=	${MASTER_SITE_AFTERSTEP}
MASTER_SITE_SUBDIR=	apps/asmodem
DISTNAME=	${PORTNAME}-0.6-1

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Displays the modem status, designed to match AfterStep
LICENSE=	unknown

USE_IMAKE=	yes
USE_XORG=	xpm

MAN1=		asmodem.1
PLIST_FILES=	bin/asmodem

.include <bsd.port.mk>
