# Created by: Sergei Vyshenski <svysh.fbsd@gmail.com>

PORTNAME=	XML-Parser-Lite
PORTVERSION=	0.722
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Lightweight regexp-based XML parser

LICENSE=	artistic gpl
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure
NO_ARCH=	yes
NO_TEST=	yes

.include <bsd.port.mk>
