# New ports collection makefile for:	p5-Mail-Sendmail
# Date created:				May 9 2008
# Whom:					Lucas Holt <luke@midnightbsd.org>
#
# $MidnightBSD$
#

PORTNAME=	Mail-Sendmail
PORTVERSION=	0.79
CATEGORIES=	mail perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Perl module implementing a simple, platform-independent mailer
LICENSE=	perl

PERL_CONFIGURE=	yes

MAN3=		Mail::Sendmail.3

.include <bsd.port.mk>
