PORTNAME=	faraday-em_synchrony
PORTVERSION=	1.0.1
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Faraday adapter for Em::Synchrony
WWW=		https://github.com/lostisland/faraday-em_synchrony

LICENSE=	mit
LICENSE_FILE=	${WRKSRC}/LICENSE.md

USES=		gem

NO_ARCH=	yes

.include <bsd.port.mk>
