# $FreeBSD: ports/x11/evieext/Makefile,v 1.1 2007/05/19 20:26:14 flz Exp $
# $MidnightBSD: mports/x11/evieext/Makefile,v 1.2 2011/05/02 23:30:23 laffer1 Exp $

PORTNAME=	evieext
PORTVERSION=	1.1.1
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	XEVIE extension headers
LICENSE=	mit

XORG_CAT=	proto

.include <bsd.port.mk>
