# $FreeBSD: ports/x11/xfindproxy/Makefile,v 1.1 2007/05/19 20:27:53 flz Exp $
# $MidnightBSD$

PORTNAME=	xfindproxy
PORTVERSION=	1.0.4
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Locate available proxy services

LICENSE=	mit

XORG_CAT=	app
USE_XORG=	x11 ice xt xproxymngproto

PLIST_FILES=	bin/xfindproxy man/man1/xfindproxy.1.gz

.include <bsd.port.mk>
