# $MidnightBSD: mports/x11/libXTrap/Makefile,v 1.6 2012/03/03 01:52:52 laffer1 Exp $

PORTNAME=	libXTrap
PORTVERSION=	1.0.1
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	The XTrap library
LICENSE=	mit

XORG_CAT=	lib
USE_XORG=	trapproto:both x11 xext xextproto xt
USE_AUTOTOOLS=	libtool

.include <bsd.port.mk>
