PORTNAME=	mkcomposecache
PORTVERSION=	1.2.1
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Program to create Compose cache files

LICENSE=	mit

USES=		xorg xorg-cat:app
USE_XORG=	x11

PLIST_FILES=	sbin/mkcomposecache man/man8/mkcomposecache.8.gz

.include <bsd.port.mk>
