# $MidnightBSD$

PORTNAME=	libogg
PORTVERSION=	1.1.4
CATEGORIES=	audio linux

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Ogg bitstream library (Linux CentOS ${LINUX_DIST_VER})

LICENSE=	bsd3

DESCR=		${.CURDIR}/../${PORTNAME}/pkg-descr
RPMVERSION=	2.1.el6
USES=		linux:c6
USE_LDCONFIG=	yes
USE_LINUX_RPM=	yes

OPTIONS_DEFINE=	DOCS

.include <bsd.port.mk>
