# $MidnightBSD$

PORTNAME=	Variable-Magic
PORTVERSION=	0.52
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Associate user-defined magic to variables from Perl
LICENSE=	perl

PERL_CONFIGURE=	yes

MAN3=		Variable::Magic.3

.include <bsd.port.mk>
