# $MidnightBSD: mports/net-p2p/Makefile,v 1.2 2007/06/08 14:13:07 laffer1 Exp $
#

    COMMENT = peer-to-peer network applications

    SUBDIR += ctorrent
    SUBDIR += gift
    SUBDIR += gift-fasttrack
    SUBDIR += gift-gnutella
    SUBDIR += libtorrent
    SUBDIR += rtorrent

.include <bsd.port.subdir.mk>
