# $MidnightBSD: mports/net-p2p/Makefile,v 1.5 2007/06/11 00:12:20 laffer1 Exp $
#

    COMMENT = peer-to-peer network applications

    SUBDIR += ctorrent
    SUBDIR += gift
    SUBDIR += gift-fasttrack
    SUBDIR += gift-gnutella
    SUBDIR += giftcurs
    SUBDIR += libtorrent
    SUBDIR += limewire
    SUBDIR += mutella
    SUBDIR += rtorrent

.include <bsd.port.subdir.mk>
