PORTNAME=	state_machines
PORTVERSION=	0.31.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Support for creating state machines for attributes on any Ruby class
WWW=		https://github.com/state-machines/state_machines

LICENSE=	mit
LICENSE_FILE=	${WRKSRC}/LICENSE.txt

USES=		gem

NO_ARCH=	yes

.include <bsd.port.mk>
