# $MidnightBSD$

COMMENT = Editors

SUBDIR += 2bsd-vi
SUBDIR += abiword
SUBDIR += emacs
SUBDIR += gedit
SUBDIR += gedit-plugins
SUBDIR += impress
SUBDIR += jedit
SUBDIR += joe
SUBDIR += jupp
SUBDIR += linux-openoffice3
SUBDIR += manedit
SUBDIR += mg
SUBDIR += mousepad
SUBDIR += nano
SUBDIR += nvi-devel
SUBDIR += pico-alpine
SUBDIR += textedit
SUBDIR += vim
SUBDIR += zile

.include <bsd.port.subdir.mk>
