# $MidnightBSD$

COMMENT = Editors

SUBDIR += 2bsd-vi
SUBDIR += abiword
SUBDIR += codeeditor
SUBDIR += emacs
SUBDIR += etoile-typewriter
SUBDIR += gedit
SUBDIR += gedit-plugins
SUBDIR += impress
SUBDIR += jedit
SUBDIR += joe
SUBDIR += jupp
SUBDIR += kate
SUBDIR += linux-openoffice3
SUBDIR += manedit
SUBDIR += mg
SUBDIR += mousepad
SUBDIR += nano
SUBDIR += nvi-devel
SUBDIR += pico-alpine
SUBDIR += textedit.app
SUBDIR += vim
SUBDIR += vim-lite
SUBDIR += xemacs
SUBDIR += xemacs-packages
SUBDIR += xenon
SUBDIR += zile

.include <bsd.port.subdir.mk>
