PORTNAME=	libatomic
PORTVERSION=	11.4.1
DISTVERSIONSUFFIX=	-3.el9
CATEGORIES=	devel linux

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Atomic fallback implementation for GCC
WWW=		https://gcc.gnu.org/

LICENSE=	gpl3

USES=		linux:rl9
USE_LDCONFIG=	yes
USE_LINUX_RPM=	yes

SRC_DISTFILES=	# not available

.include <bsd.port.mk>
