# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/devel/php70-intl/Makefile 424244 2016-10-19 13:34:18Z tz $
# $MidnightBSD$

CATEGORIES=	devel

MASTERDIR=	${.CURDIR}/../../lang/php70

PKGNAMESUFFIX=	-intl

.include "${MASTERDIR}/Makefile"
