# $MidnightBSD$

PORTNAME=	xwud
PORTVERSION=	1.0.5
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Image displayer for X

LICENSE=	mit

XORG_CAT=	app
USE_XORG=	x11

PLIST_FILES=	bin/xwud man/man1/xwud.1.gz

.include <bsd.port.mk>
