PORTNAME=	safety_net_attestation
PORTVERSION=	0.5.0
CATEGORIES=	security rubygems
MASTER_SITES=	RG

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	SafetyNet attestation response verification
WWW=		https://github.com/bdewater/safety_net_attestation

LICENSE=	mit

RUN_DEPENDS=	rubygem-jwt2>=2.0<4:www/rubygem-jwt2

USES=		gem

NO_ARCH=	yes

.include <bsd.port.mk>
