# $MidnightBSD: mports/irc/Makefile,v 1.13 2010/01/23 19:17:57 laffer1 Exp $
#

    COMMENT = Internet Relay Chat utilities

SUBDIR += bitlbee
SUBDIR += bnc
SUBDIR += irssi
SUBDIR += irssi-scripts
SUBDIR += ngircd
SUBDIR += sirc
SUBDIR += talksoup
SUBDIR += xchat
SUBDIR += znc

.include <bsd.port.subdir.mk>
