# $MidnightBSD$

PORTNAME=	xcompmgr
PORTVERSION=	1.1.6
PORTREVISION=	2
CATEGORIES=	x11-wm

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Sample X compositing manager

LICENSE=	mit

XORG_CAT=	app
USE_XORG=	x11 xcomposite xfixes xdamage xrender

PLIST_FILES=	bin/${PORTNAME} man/man1/${PORTNAME}.1.gz

.include <bsd.port.mk>
