# $MidnightBSD: mports/textproc/Makefile,v 1.8 2006/09/24 00:47:40 laffer1 Exp $
# $FreeBSD: ports/textproc/Makefile,v 1.1058 2006/09/12 21:11:30 miwi Exp $
#

    COMMENT = Text processing utilities (does not include desktop publishing)

    SUBDIR += aspell
    SUBDIR += docbook
    SUBDIR += docbook-241
    SUBDIR += docbook-300
    SUBDIR += docbook-310
    SUBDIR += docbook-400
    SUBDIR += docbook-410
    SUBDIR += docbook-420
    SUBDIR += docbook-430
    SUBDIR += docbook-xml
    SUBDIR += expat2
    SUBDIR += intltool
    SUBDIR += iso8879
    SUBDIR += ispell
    SUBDIR += libxml2
    SUBDIR += libxslt
    SUBDIR += linux-expat
    SUBDIR += p5-XML-Parser
    SUBDIR += xmlcatmgr

.include <bsd.port.subdir.mk>
