# $MidnightBSD: mports/textproc/Makefile,v 1.3 2006/09/18 20:48:03 wintellect Exp $
# $FreeBSD: ports/textproc/Makefile,v 1.1058 2006/09/12 21:11:30 miwi Exp $
#

    COMMENT = Text processing utilities (does not include desktop publishing)

    SUBDIR += expat2
    SUBDIR += intltool
    SUBDIR += libxml2
    SUBDIR += p5-XML-Parser

.include <bsd.port.subdir.mk>
