# $MidnightBSD: mports/print/Makefile,v 1.18 2007/01/24 17:18:18 laffer1 Exp $
#

    COMMENT = Desktop publishing

    SUBDIR += acroread7
    SUBDIR += acroreadwrapper
    SUBDIR += amspsfnt
    SUBDIR += cm-super
    SUBDIR += cmpsfont
    SUBDIR += cups
    SUBDIR += cups-base
    SUBDIR += cups-pstoraster
    SUBDIR += enscript-a4
    SUBDIR += enscript-letter
    SUBDIR += fontforge
    SUBDIR += freetype2
    SUBDIR += ghostscript-afpl
    SUBDIR += ghostscript-gpl
    SUBDIR += ghostscript-gpl-nox11
    SUBDIR += gsfonts
    SUBDIR += libpaper
    SUBDIR += pdflib
    SUBDIR += pecl-pdflib
    SUBDIR += teTeX-base
    SUBDIR += teTeX-texmf
    SUBDIR += tex-texmflocal
    SUBDIR += wmlpq

.include <bsd.port.subdir.mk>
