# $MidnightBSD: mports/print/Makefile,v 1.8 2006/11/25 00:43:18 laffer1 Exp $
#

    COMMENT = Desktop publishing

    SUBDIR += acroread7
    SUBDIR += acroreadwrapper
    SUBDIR += cups-base
    SUBDIR += enscript-letter
    SUBDIR += fontforge
    SUBDIR += freetype2
    SUBDIR += gsfonts
    SUBDIR += pdflib
    SUBDIR += pecl-pdflib
    SUBDIR += wmlpq

.include <bsd.port.subdir.mk>
