# $MidnightBSD: mports/print/Makefile,v 1.1.1.1 2006/09/17 03:34:00 archite Exp $
# $FreeBSD: ports/print/Makefile,v 1.405 2006/09/12 15:55:23 rafan Exp $
#

    COMMENT = Desktop publishing

    SUBDIR += cups-base
    SUBDIR += freetype2

.include <bsd.port.subdir.mk>
