# New ports collection makefile for:	p5-UNIVERSAL-require
# Date Created:				25 Oct, 2005
# Whom:					Jun Kuriyama <kuriyama@FreeBSD.org>
#
# $MidnightBSD: mports/devel/p5-UNIVERSAL-require/Makefile,v 1.2 2008/09/22 18:48:45 laffer1 Exp $
# $FreeBSD: ports/devel/p5-UNIVERSAL-require/Makefile,v 1.2 2006/11/29 01:09:56 kuriyama Exp $
#

PORTNAME=	UNIVERSAL-require
PORTVERSION=	0.11
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Perl module to require() from a variable
LICENSE=	perl

PERL_CONFIGURE=	yes

MAN3=		UNIVERSAL::require.3

.include <bsd.port.mk>
