# $MidnightBSD: mports/x11-drivers/xf86-video-tseng/Makefile,v 1.1 2007/10/12 03:43:52 ctriv Exp $

PORTNAME=	xf86-video-tseng
PORTVERSION=	1.2.1
CATEGORIES=	x11-drivers

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X.Org tseng display driver
LICENSE=	x11

XORG_CAT=	driver
USE_XORG=	videoproto xextproto
MAN4=		tseng.4x

.include <bsd.port.mk>
