    COMMENT = Biology

    SUBDIR += linux-foldingathome
    SUBDIR += ruby-bio
    SUBDIR += rubygem-bio
    SUBDIR += rubygem-bio-executables
    SUBDIR += rubygem-bio-old-biofetch-emulator
    SUBDIR += rubygem-bio-shell

.include <bsd.port.subdir.mk>
