# $FreeBSD: ports/x11/xineramaproto/Makefile,v 1.1 2007/05/19 20:27:55 flz Exp $
# $MidnightBSD: mports/x11/xineramaproto/Makefile,v 1.2 2011/05/07 15:29:45 laffer1 Exp $

PORTNAME=	xineramaproto
PORTVERSION=	1.2.1
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Xinerama extension headers
LICENSE=	mit

XORG_CAT=	proto

.include <bsd.port.mk>
