# $MidnightBSD: mports/multimedia/Makefile,v 1.26 2007/06/11 02:40:50 laffer1 Exp $
#

    COMMENT = Multimedia software

    SUBDIR += etoile-babbler
    SUBDIR += etoile-multimediakit
    SUBDIR += gnustep-mplayer
    SUBDIR += gpac-libgpac
    SUBDIR += gstreamer
    SUBDIR += gstreamer-plugins
    SUBDIR += libdts
    SUBDIR += libdv
    SUBDIR += libdvdcss
    SUBDIR += libdvdread
    SUBDIR += libfame
    SUBDIR += libmpeg2
    SUBDIR += libtheora
    SUBDIR += libxine
    SUBDIR += linux-realplayer
    SUBDIR += mpeg2codec
    SUBDIR += mpeg4ip-libmp4v2
    SUBDIR += mplayer
    SUBDIR += mplayer-skins
    SUBDIR += ogle
    SUBDIR += smpeg
    SUBDIR += streamdvd
    SUBDIR += v4l_compat
    SUBDIR += vcdimager
    SUBDIR += win32-codecs
    SUBDIR += xanim
    SUBDIR += xine
    SUBDIR += xmms
    SUBDIR += xmms-skins
    SUBDIR += xvid

.include <bsd.port.subdir.mk>
