# $MidnightBSD$

PORTNAME=	libXprintAppUtil
PORTVERSION=	1.0.1
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	The XprintAppUtil library
LICENSE=	mit

XORG_CAT=	lib
USE_XORG=	printproto x11 xau xp xprintutil xproto:both
USE_AUTOTOOLS=	libtool

.include <bsd.port.mk>
