# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/databases/php70-pdo_sqlite/Makefile 408932 2016-02-15 14:34:26Z miwi $

CATEGORIES=	databases

MASTERDIR=	${.CURDIR}/../../lang/php70

PKGNAMESUFFIX=	-pdo_sqlite

.include "${MASTERDIR}/Makefile"
