# $MidnightBSD$

PORTNAME=	smproxy
PORTVERSION=	1.0.5
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Session Manager Proxy
LICENSE=	mit

XORG_CAT=	app
USE_XORG=	xt xmu

PLIST_FILES=	bin/smproxy

MAN1=		smproxy.1

.include <bsd.port.mk>
