# $FreeBSD: ports/x11/rstart/Makefile,v 1.1 2007/05/19 20:27:15 flz Exp $
# $MidnightBSD: mports/x11/rstart/Makefile,v 1.2 2011/05/07 02:19:24 laffer1 Exp $

PORTNAME=	rstart
PORTVERSION=	1.0.4
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Sample implementation of a Remote Start client
LICENSE=	x11

XORG_CAT=	app
USE_XORG=	x11

MAN1=		rstart.1 rstartd.1

.include <bsd.port.mk>
