PORTNAME=	pl-puppetdb-ruby
PORTVERSION=	2.0.3
CATEGORIES=	databases rubygems
MASTER_SITES=	RG

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Simple Ruby client library for PuppetDB API
WWW=		https://rubygems.org/gems/pl-puppetdb-ruby

LICENSE=	Apache-2.0
LICENSE_FILE=	${WRKSRC}/LICENSE

BUILD_DEPENDS=	${RUN_DEPENDS}
RUN_DEPENDS=	rubygem-httparty>0:www/rubygem-httparty

USES=		gem
NO_ARCH=	yes

.include <bsd.port.mk>
