# $MidnightBSD$

PORTNAME=	xsm
PORTVERSION=	1.0.3
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X Session Manager

LICENSE=	mit

XORG_CAT=	app
USE_XORG=	xt xaw

BUILD_DEPENDS=	${LOCALBASE}/libdata/pkgconfig/xorg-macros.pc:${PORTSDIR}/devel/xorg-macros

.include <bsd.port.mk>
