# $MidnightBSD: mports/x11/xsm/Makefile,v 1.2 2009/05/04 02:04:56 laffer1 Exp $

PORTNAME=	xsm
PORTVERSION=	1.0.2
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X Session Manager
LICENSE=	x11

XORG_CAT=	app
USE_XORG=	xt xaw

MAN1=		xsm.1

.include <bsd.port.mk>
