# $MidnightBSD$

PORTNAME=	matharray
PORTVERSION=	1.2
CATEGORIES=	math gnustep
MASTER_SITES=	${MASTER_SITE_GNUSTEP}
MASTER_SITE_SUBDIR=	contrib
DISTNAME=	MathArray-${PORTVERSION}

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Class library for mathematical manipulation of matrices
LICENSE=	lgpl

USES=		gnustep
USE_GNUSTEP=	build base
USE_GNUSTEP_INSTALL=	yes
USE_GNUSTEP_LDCONFIG=	${GNUSTEP_LOCAL_LIBRARIES}

.include <bsd.port.mk>
