# $FreeBSD: ports/x11/xf86miscproto/Makefile,v 1.1 2007/05/19 20:27:50 flz Exp $
# $MidnightBSD: mports/x11/xf86miscproto/Makefile,v 1.2 2011/05/07 14:33:27 laffer1 Exp $

PORTNAME=	xf86miscproto
PORTVERSION=	0.9.3
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	XFree86-Misc extension headers
LICENSE=	mit

XORG_CAT=	proto

.include <bsd.port.mk>
