# $MidnightBSD$

PORTNAME=	xclock
PORTVERSION=	1.0.6
CATEGORIES=	x11-clocks

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Analog and digital clock for X
LICENSE=	mit

XORG_CAT=	app
USE_XORG=	xrender xft xkbfile xt xaw

MAN1=		xclock.1

.include <bsd.port.mk>
