# $MidnightBSD: mports/x11-drivers/xf86-input-penmount/Makefile,v 1.2 2009/03/27 23:50:12 laffer1 Exp $

PORTNAME=	xf86-input-penmount
PORTVERSION=	1.4.0
CATEGORIES=	x11-drivers

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X.Org penmount input driver
LICENSE=	x11

XORG_CAT=	driver
MAN4=		penmount.4x

.include <bsd.port.mk>
