# $MidnightBSD: mports/x11-drivers/xf86-video-ati/Makefile,v 1.10 2010/05/29 14:03:12 laffer1 Exp $

PORTNAME=	xf86-video-ati
PORTVERSION=	6.14.1
CATEGORIES=	x11-drivers

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X.Org ati display driver
LICENSE=	x11

USE_GL=		gl

XORG_CAT=	driver
USE_XORG=	xf86driproto xineramaproto videoproto xf86miscproto xextproto glproto
MAN4=		ati.4x radeon.4x

.include <bsd.port.mk>
