PORTREVISION=	0

COMMENT=	Gpgme Qt${FLAVOR:S|qt||} bindings

LICENSE=	gpl2+
LICENSE_FILE=	${WRKSRC}/COPYING

MASTERDIR=	${.CURDIR:H:H}/security/gpgme
PLIST=		${.CURDIR}/pkg-plist

_GPGME_BINDING=	qt

.include "${MASTERDIR}/Makefile"
