# $MidnightBSD$

PORTNAME=	xclock
PORTVERSION=	1.0.7
PORTREVISION=	2
CATEGORIES=	x11-clocks

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Analog and digital clock for X

LICENSE=	mit

XORG_CAT=	app
USE_XORG=	xrender xft xkbfile xt xaw
USES=		iconv

.include <bsd.port.mk>
