# $FreeBSD: ports/x11-fonts/font-bh-75dpi/Makefile,v 1.1 2007/05/19 20:29:12 flz Exp $
# $MidnightBSD: mports/x11-fonts/font-bh-75dpi/Makefile,v 1.1 2007/10/09 16:37:21 ctriv Exp $

PORTNAME=	font-bh-75dpi
PORTVERSION=	1.0.3
CATEGORIES=	x11-fonts

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X.Org Bigelow Holmes 75dpi font
LICENSE=	unknown

XORG_CAT=	font
USE_XORG=	fontutil

.include <bsd.port.mk>
