# $MidnightBSD: mports/x11/libXdamage/Makefile,v 1.3 2012/03/03 01:52:53 laffer1 Exp $

PORTNAME=	libXdamage
PORTVERSION=	1.1.4
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X Damage extension library
LICENSE=	mit

XORG_CAT=	lib
USE_XORG=	x11 damageproto:both xfixes fixesproto xextproto xproto:both

.include <bsd.port.mk>
