PORTNAME=	hashie
PORTVERSION=	5.0.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG
PKGNAMESUFFIX=	-gitlab

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Simple collection of useful Hash extensions
WWW=		https://github.com/hashie/hashie

LICENSE=	mit
LICENSE_FILE=	${WRKSRC}/LICENSE

BUILD_DEPENDS=	${RUN_DEPENDS}
RUN_DEPENDS=	rubygem-logger-gitlab>=0:devel/rubygem-logger-gitlab

USES=		gem

NO_ARCH=	yes

.include <bsd.port.mk>
