# $MidnightBSD: mports/x11/xinit/Makefile,v 1.2 2009/03/25 01:42:54 laffer1 Exp $

PORTNAME=	xinit
PORTVERSION=	1.2.0
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X Window System initializer
LICENSE=	x11

XORG_CAT=	app
USE_XORG=	x11

PLIST_FILES=	bin/startx bin/xinit lib/X11/xinit/xinitrc
PLIST_DIRS=	lib/X11/xinit

MAN1=		startx.1 xinit.1

.include <bsd.port.mk>
