# $MidnightBSD: mports/x11/xkbutils/Makefile,v 1.2 2009/04/13 17:49:38 laffer1 Exp $

PORTNAME=	xkbutils
PORTVERSION=	1.0.1
PORTREVISION=	2
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	XKB utility demos
LICENSE=	x11

XORG_CAT=	app
USE_XORG=	xkbfile x11 xaw inputproto

.include <bsd.port.mk>
