PORTNAME=	xkbutils
PORTVERSION=	1.0.6
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	XKB utility demos

LICENSE=	mit

USES=		tar:xz xorg xorg-cat:app
USE_XORG=	xkbfile x11 xaw xorgproto xt

.include <bsd.port.mk>
