# $MidnightBSD: mports/x11/xkbutils/Makefile,v 1.5 2012/03/03 01:52:55 laffer1 Exp $

PORTNAME=	xkbutils
PORTVERSION=	1.0.4
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	XKB utility demos
LICENSE=	x11

XORG_CAT=	app
USE_XORG=	xkbfile x11 xaw inputproto

MAN1=		xkbbell.1 xkbvleds.1 xkbwatch.1

.include <bsd.port.mk>
