# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/textproc/php70-xmlwriter/Makefile 408932 2016-02-15 14:34:26Z miwi $

CATEGORIES=	textproc

MASTERDIR=	${.CURDIR}/../../lang/php70

PKGNAMESUFFIX=	-xmlwriter

.include "${MASTERDIR}/Makefile"
