# $MidnightBSD$

PORTNAME=	Compress-Raw-Bzip2
PORTVERSION=	2.064
CATEGORIES=	archivers perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:PMQS
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Low-Level Interface to bzip2 compression library
LICENSE=	perl

PERL_CONFIGURE=	YES

.include <bsd.port.mk>
