PORTNAME=	xsetroot
PORTVERSION=	1.1.2
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Root window parameter setting utility for X

LICENSE=	mit

USES=		xorg xorg-cat:app
USE_XORG=	xmuu x11 xbitmaps xcursor
PLIST_FILES=	bin/xsetroot man/man1/xsetroot.1.gz

.include <bsd.port.mk>
