# $FreeBSD: ports/x11/xman/Makefile,v 1.2 2007/09/13 19:45:04 flz Exp $
# $MidnightBSD: mports/x11/xman/Makefile,v 1.2 2011/05/07 15:29:46 laffer1 Exp $

PORTNAME=	xman
PORTVERSION=	1.1.2
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Manual page display program for X
LICENSE=	mit

XORG_CAT=	app
USE_XORG=	xt xaw xp xprintutil

MAN1=		xman.1

.include <bsd.port.mk>
