PORTNAME=	opentelemetry-semantic_conventions
PORTVERSION=	1.37.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Semantic Convention definitions for OpenTelemetry
WWW=		https://opentelemetry.io/ \
		https://github.com/open-telemetry/opentelemetry-ruby/tree/main/semantic_conventions \
		https://github.com/open-telemetry/opentelemetry-ruby

LICENSE=	Apache-2.0
LICENSE_FILE=	${WRKSRC}/LICENSE

RUN_DEPENDS=	rubygem-opentelemetry-api>=1.0<2:devel/rubygem-opentelemetry-api

USES=		gem

NO_ARCH=	yes

.include <bsd.port.mk>
