PORTNAME=	HTML-Selector-XPath
PORTVERSION=	0.28
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:CORION
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	CSS selector to XPath compiler Perl module
WWW=		https://metacpan.org/release/HTML-Selector-XPath

LICENSE=	artistic gpl+
LICENSE_COMB=	dual

TEST_DEPENDS=	p5-Test-Base>=0:devel/p5-Test-Base

USES=		perl5
USE_PERL5=	configure

NO_ARCH=	yes

.include <bsd.port.mk>
