# $MidnightBSD: mports/x11-drivers/xf86-video-vesa/Makefile,v 1.3 2009/05/08 20:37:25 laffer1 Exp $

PORTNAME=	xf86-video-vesa
PORTVERSION=	2.3.0
CATEGORIES=	x11-drivers

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X.Org vesa display driver
LICENSE=	x11

XORG_CAT=	driver
USE_XORG=	xextproto
MAN4=		vesa.4x

.include <bsd.port.mk>
