# $MidnightBSD: mports/x11-drivers/xf86-video-vesa/Makefile,v 1.2 2009/03/16 15:45:55 laffer1 Exp $

PORTNAME=	xf86-video-vesa
PORTVERSION=	2.1.0
PORTREVISION=	1
CATEGORIES=	x11-drivers

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X.Org vesa display driver
LICENSE=	x11

XORG_CAT=	driver
USE_XORG=	xextproto
MAN4=		vesa.4x

.include <bsd.port.mk>
