# $MidnightBSD$
# $FreeBSD: head/graphics/php71-exif/Makefile 475229 2018-07-24 08:44:32Z tz $

CATEGORIES=	graphics

MASTERDIR=	${.CURDIR}/../../lang/php71

PKGNAMESUFFIX=	-exif

TEST_TARGET=    test

.include "${MASTERDIR}/Makefile"
