# New ports collection makefile for:	php5-sockets
# Date created:			7 Jul 2004
# Whom:				Alex Dupre <ale@FreeBSD.org>
#
# $FreeBSD: ports/net/php5-sockets/Makefile,v 1.1 2004/07/19 09:16:01 ale Exp $
# $MidnightBSD$
#

CATEGORIES=	net

MASTERDIR=	${.CURDIR}/../../lang/php5

PKGNAMESUFFIX=	-sockets

.include "${MASTERDIR}/Makefile"
