# $MidnightBSD$

PORTNAME=	libICE
PORTVERSION=	1.0.9
PORTREVISION=	2
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Inter Client Exchange library for X11

LICENSE=	mit
LICENSE_FILE=	${WRKSRC}/COPYING

XORG_CAT=	lib
USE_XORG=	xproto:both xtrans

INSTALL_TARGET=	install-strip

.include <bsd.port.mk>
