# $MidnightBSD: mports/x11/libICE/Makefile,v 1.2 2009/03/15 20:32:42 laffer1 Exp $

PORTNAME=	libICE
PORTVERSION=	1.0.7
PORTREVISION=	1
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Inter Client Exchange library for X11
LICENSE=	x11

XORG_CAT=	lib
USE_XORG=	xproto:both xtrans

.include <bsd.port.mk>
