# $MidnightBSD: mports/x11-fonts/xlsfonts/Makefile,v 1.2 2009/04/04 15:35:53 laffer1 Exp $

PORTNAME=	xlsfonts
PORTVERSION=	1.0.3
CATEGORIES=	x11-fonts

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Server font list displayer for X
LICENSE=	x11

XORG_CAT=	app
USE_XORG=	x11

PLIST_FILES=	bin/xlsfonts

MAN1=		xlsfonts.1

.include <bsd.port.mk>
