PORTNAME=	font-bitstream-type1
PORTVERSION=	1.0.4
CATEGORIES=	x11-fonts
DISTFILES=      ${PORTNAME}-${PORTVERSION}.tar.xz

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X.Org Bitstream Vera Type1 font

LICENSE=	unknown

USES=		xorg-cat:font tar:xz

.include <bsd.port.mk>
