PORTNAME=	Perl-Tidy
PORTVERSION=	20181120
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Indents and reformats Perl scripts to make them easier to read

LICENSE=	gpl2

USES=		perl5
USE_PERL5=	configure

NO_ARCH=	yes

.include <bsd.port.mk>
