# $MidnightBSD: mports/sysutils/p5-File-Which/Makefile,v 1.1 2007/04/28 03:31:19 laffer1 Exp $

PORTNAME=	File-Which
PORTVERSION=	1.09
CATEGORIES=	sysutils perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	File
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Portable implementation of `which' in Perl
LICENSE=	perl

PERL_CONFIGURE=	yes

MAN1=		pwhich.1
MAN3=		File::Which.3

.include <bsd.port.mk>
