PORTNAME=	libretls
PORTVERSION=	3.3.3
CATEGORIES=	security devel
MASTER_SITES=	https://causal.agency/libretls/

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	TLS library designed to ease writing foolproof applications

LICENSE=	iscl

USES=	libtool ssl pkgconfig
INSTALL_TARGET=	install-strip
GNU_CONFIGURE=	yes

USE_LDCONFIG=	yes

.include <bsd.port.mk>
