# $FreeBSD: head/graphics/gstreamer1-plugins-cairo/Makefile 375225 2014-12-22 10:22:38Z kwm $

PORTREVISION=	0
CATEGORIES=	graphics

COMMENT=	Gstreamer vector graphics plugin

GST_PLUGIN=	cairo
DIST=		good

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
