# $MidnightBSD$
# $FreeBSD: head/security/easy-rsa/Makefile 328226 2013-09-25 00:54:08Z bdrewery $

PORTNAME=	easy-rsa
DISTVERSION=	2.2.0_master
CATEGORIES=	security net-mgmt
MASTER_SITES=	http://swupdate.openvpn.net/community/releases/ \
		http://build.openvpn.net/downloads/releases/

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Small RSA key management package based on openssl

LICENSE=	gpl2

GNU_CONFIGURE=	yes

.include <bsd.port.mk>
