# $MidnightBSD$

PORTNAME=	twm
PORTVERSION=	1.0.7
CATEGORIES=	x11-wm

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Tab Window Manager for the X Window System

LICENSE=	mit

XORG_CAT=	app
USE_XORG=	x11 xext xt xmu

MAN1=		twm.1

.include <bsd.port.mk>
