# $MidnightBSD$
    
COMMENT = Ports to help disabled users

SUBDIR += at-spi
SUBDIR += at-spi-reference
SUBDIR += at-spi2-atk
SUBDIR += at-spi2-core
SUBDIR += atk
SUBDIR += atk-reference
SUBDIR += atkmm
SUBDIR += caribou
SUBDIR += dasher
SUBDIR += gnome-mag
SUBDIR += gnome-speech
SUBDIR += gok
SUBDIR += linux-f10-atk
SUBDIR += mousetweaks
SUBDIR += orca
SUBDIR += py-atspi
SUBDIR += py3-atspi
SUBDIR += qt4-accessible
SUBDIR += speech-dispatcher

.include <bsd.port.subdir.mk>
