# New ports collection makefile for:	xfwm4-artwork
# Date created:				3 August 2003
# Whom:					Dmitry Sivachenko <demon@FreeBSD.org>
#
# $MidnightBSD$
# $FreeBSD: ports/misc/xfce4-artwork/Makefile,v 1.11 2008/08/21 06:17:46 rafan Exp $
#

PORTNAME=	xfce4-artwork
PORTVERSION=	0.0.4
CATEGORIES=	misc xfce
MASTER_SITES=	http://download.berlios.de/xfce-goodies/
DIST_SUBDIR=	xfce4

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Additional artwork for the XFce4 desktop environment
LICENSE=	unknown

RUN_DEPENDS=	xfdesktop:${PORTSDIR}/x11-wm/xfce4-desktop

GNU_CONFIGURE=	yes

.include <bsd.port.mk>
