# New ports collection makefile for:	gstreamer-plugins-vorbis
# Date created:			23 Nov 2007
# Whom:				Lucas Holt <luke@Midnightbsd.org>
#
# $MidnightBSD: mports/audio/gstreamer-plugins-vorbis/Makefile,v 1.1 2007/11/24 03:33:51 laffer1 Exp $

CATEGORIES=	audio

COMMENT=	Gstreamer vorbis encoder/decoder plugin
LICENSE=	lgpl

GST_PLUGIN=	vorbis

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
