PORTNAME=	firstboot-midnightbsd-update
PORTVERSION=	1.0
CATEGORIES=	sysutils
MASTER_SITES=	# none
DISTFILES=	# none
EXTRACT_ONLY=	# none

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Update the system using midnightbsd-update when it first boots

NO_WRKSUBDIR=	yes
NO_BUILD=	yes
NO_INSTALL=	yes
NO_ARCH=	yes

USE_RC_SUBR=	firstboot_midnightbsd_update

.include <bsd.port.mk>
