# New ports collection makefile for:	xf86-video-cyrix
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11-drivers/xf86-video-cyrix/Makefile,v 1.2 2007/09/15 14:04:26 flz Exp $
# $MidnightBSD$
#

PORTNAME=	xf86-video-cyrix
PORTVERSION=	1.1.0
CATEGORIES=	x11-drivers

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X.Org cyrix display driver
LICENSE=	x11

XORG_CAT=	driver
USE_XORG=	xextproto xf86dgaproto
MAN4=		cyrix.4x

.include <bsd.port.mk>
