# New ports collection makefile for:	xf86-video-rendition
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11-drivers/xf86-video-rendition/Makefile,v 1.2 2007/09/15 14:04:28 flz Exp $
# $MidnightBSD$
#

PORTNAME=	xf86-video-rendition
PORTVERSION=	4.1.3
CATEGORIES=	x11-drivers

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X.Org rendition display driver
LICENSE=	x11

XORG_CAT=	driver
USE_XORG=	xextproto
MAN4=		rendition.4x

.include <bsd.port.mk>
