# $MidnightBSD$

PORTNAME=	xf86dgaproto
PORTVERSION=	2.1
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	XFree86-DGA extension headers

LICENSE=	mit
LICENSE_FILE=	${WRKSRC}/COPYING

XORG_CAT=	proto

.include <bsd.port.mk>
