# $MidnightBSD: mports/x11-fonts/Makefile,v 1.1.1.1 2006/09/17 03:33:56 archite Exp $
# $FreeBSD: ports/x11-fonts/Makefile,v 1.84 2006/08/28 13:41:49 ehaupt Exp $
#

    COMMENT = X11 fonts and font utilities

    SUBDIR += bitstream-vera
    SUBDIR += fontconfig
    SUBDIR += libXft
    SUBDIR += linux-fontconfig
    SUBDIR += xorg-fonts-100dpi
    SUBDIR += xorg-fonts-75dpi
    SUBDIR += xorg-fonts-cyrillic
    SUBDIR += xorg-fonts-encodings
    SUBDIR += xorg-fonts-miscbitmaps
    SUBDIR += xorg-fonts-truetype
    SUBDIR += xorg-fonts-type1

.include <bsd.port.subdir.mk>
