# $FreeBSD: ports/x11/xditview/Makefile,v 1.1 2007/05/19 20:27:45 flz Exp $
# $MidnightBSD: mports/x11/xditview/Makefile,v 1.2 2011/05/07 02:53:14 laffer1 Exp $

PORTNAME=	xditview
PORTVERSION=	1.0.2
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Display ditroff output
LICENSE=	x11

XORG_CAT=	app
USE_XORG=	xt xaw

MAN1=		xditview.1

.include <bsd.port.mk>
