# $MidnightBSD: mports/security/Makefile,v 1.34 2006/11/25 04:40:45 laffer1 Exp $
#

    COMMENT = Security tools

    SUBDIR += aide
    SUBDIR += ca-roots
    SUBDIR += chroot_safe
    SUBDIR += clamav
    SUBDIR += cyrus-sasl
    SUBDIR += cyrus-sasl2
    SUBDIR += cyrus-sasl2-ldapdb
    SUBDIR += cyrus-sasl2-saslauthd
    SUBDIR += gnupg
    SUBDIR += gnutls
    SUBDIR += libgcrypt
    SUBDIR += libgpg-error
    SUBDIR += libmcrypt
    SUBDIR += mcrypt
    SUBDIR += mhash
    SUBDIR += nss
    SUBDIR += openssh-portable
    SUBDIR += openvpn
    SUBDIR += p5-Digest
    SUBDIR += p5-Digest-MD5
    SUBDIR += p5-IO-Socket-SSL
    SUBDIR += p5-Net-SSLeay
    SUBDIR += php5-mcrypt
    SUBDIR += php5-openssl
    SUBDIR += sudo
    SUBDIR += tripwire
    SUBDIR += vlock
    SUBDIR += vlog
    SUBDIR += vnccrack
    SUBDIR += webfwlog
    SUBDIR += wipe
    SUBDIR += wpa_supplicant
    SUBDIR += xinetd
    SUBDIR += xmlsec
    SUBDIR += xmlsec1
    SUBDIR += xspy
    SUBDIR += yafic
    SUBDIR += zebedee
    SUBDIR += zombiezapper

.include <bsd.port.subdir.mk>
