# $MidnightBSD: mports/security/Makefile,v 1.17 2006/10/31 23:28:44 wintellect Exp $
# $FreeBSD: ports/security/Makefile,v 1.816 2006/09/07 21:40:37 acm Exp $
#

    COMMENT = Security tools

    SUBDIR += aide
    SUBDIR += ca-roots
    SUBDIR += clamav
    SUBDIR += cyrus-sasl
    SUBDIR += cyrus-sasl2
    SUBDIR += cyrus-sasl2-ldapdb
    SUBDIR += cyrus-sasl2-saslauthd
    SUBDIR += gnupg
    SUBDIR += gnutls
    SUBDIR += libgcrypt
    SUBDIR += libgpg-error
    SUBDIR += mhash
    SUBDIR += nss
    SUBDIR += openssh-portable
    SUBDIR += openvpn
    SUBDIR += p5-Digest
    SUBDIR += p5-Digest-MD5
    SUBDIR += p5-IO-Socket-SSL
    SUBDIR += p5-Net-SSLeay
    SUBDIR += sudo
    SUBDIR += wpa_supplicant

.include <bsd.port.subdir.mk>
