# $MidnightBSD$

PORTNAME=	portsearch
PORTVERSION=	1.3.4
CATEGORIES=	ports-mgmt
MASTER_SITES=	${MASTER_SITE_FREEBSD_LOCAL} \
		http://people.freebsd.org/~vd/portsearch/
MASTER_SITE_SUBDIR=	vd/portsearch

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Port searching tool that supports search by packing list files

LICENSE=	bsd2

FAKE_OPTS=	trueprefix

PLIST_FILES=	bin/portsearch %%DATADIR%%/Makefile
PLIST_DIRS=	%%DATADIR%%

.include <bsd.port.mk>
