# $MidnightBSD: mports/security/libntlm/Makefile,v 1.4 2011/02/02 21:20:53 laffer1 Exp $

PORTNAME=	libntlm
PORTVERSION=	1.2
CATEGORIES=	security
MASTER_SITES=	http://josefsson.org/${PORTNAME}/releases/

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	A library that implement Microsoft's NTLM authentication
LICENSE=	lgpl

USE_AUTOTOOLS=	libtool
USE_GNOME=	gnomehack gnometarget pkgconfig
GNU_CONFIGURE=	yes
USE_LDCONFIG=	yes

.include <bsd.port.mk>
