# $MidnightBSD$
# $FreeBSD: ports/devel/p5-File-Remove/Makefile,v 1.13 2008/02/14 07:46:26 ade Exp $

PORTNAME=	File-Remove
PORTVERSION=	1.57
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:ADAMK
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Perl5 module to easily removes files and directories

LICENSE=	artistic gpl
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
