# New ports collection Makefile for:	p5-File-Remove
# Date created:				16th March 2001
# Whom: 				Justin Stanford <jus@security.za.net>
#
# $MidnightBSD: mports/devel/p5-File-Remove/Makefile,v 1.1 2008/03/21 20:18:18 laffer1 Exp $
# $FreeBSD: ports/devel/p5-File-Remove/Makefile,v 1.13 2008/02/14 07:46:26 ade Exp $
#

PORTNAME=	File-Remove
PORTVERSION=	0.39
CATEGORIES=	devel perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	File
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Perl5 module to easily removes files and directories
LICENSE=	perl

PERL_CONFIGURE=	YES

MAN3=		File::Remove.3

.include <bsd.port.mk>
