PORTNAME=	jwt
PORTVERSION=	3.1.2
CATEGORIES=	www devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	JSON Web Token implementation in Ruby
WWW=		https://github.com/jwt/ruby-jwt

LICENSE=	mit
LICENSE_FILE=	${WRKSRC}/LICENSE

BUILD_DEPENDS=	${RUN_DEPENDS}
RUN_DEPENDS=	rubygem-base64>=0:converters/rubygem-base64

USES=		gem

NO_ARCH=	yes

.include <bsd.port.mk>
