PORTNAME=	creole
PORTVERSION=	0.5.0
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Creole-to-HTML converter
WWW=		https://github.com/minad/creole

LICENSE=	ruby

NO_ARCH=	yes

USES=		gem

.include <bsd.port.mk>
