PKGNAMESUFFIX=	-xskin

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X11AMP skin interface for TiMidity++

LICENSE=	gpl2+

OPTIONS_DEFINE=	DOCS

MASTERDIR=	${.CURDIR}/../../audio/timidity++

.include "${MASTERDIR}/Makefile"
