# $MidnightBSD: mports/lang/p5-Error/Makefile,v 1.3 2008/08/13 16:48:25 laffer1 Exp $

PORTNAME=	Error
PORTVERSION=	0.17.015
CATEGORIES=	lang perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	Error
PKGNAMEPREFIX=	p5-
DISTNAME=	${PORTNAME}-0.17015

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Perl module to provide Error/exception support for perl: Error
LICENSE=	perl

MAKE_JOBS_SAFE=	yes
PERL_CONFIGURE=	YES

MAN3=		Error.3 Error::Simple.3

.include <bsd.port.mk>
