# $MidnightBSD$

PORTNAME=	Error
PORTVERSION=	0.17019
CATEGORIES=	lang perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Perl module to provide Error/exception support for perl: Error
LICENSE=	perl

MAKE_JOBS_SAFE=	yes
PERL_CONFIGURE=	yes

MAN3=		Error.3 Error::Simple.3

.include <bsd.port.mk>
