# New ports collection makefile for:    font-bh-ttf
# Date created:		28 Aug 2005
# Whom:			Pawel Worach
#
# $FreeBSD: ports/x11-fonts/font-bh-ttf/Makefile,v 1.1 2007/05/19 20:29:12 flz Exp $
# $MidnightBSD$
#

PORTNAME=	font-bh-ttf
PORTVERSION=	1.0.0
CATEGORIES=	x11-fonts

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X.Org Bigelow & Holmes TTF font
LICENSE=	unknown

XORG_CAT=	font

.include <bsd.port.mk>
