# $MidnightBSD: mports/x11-wm/Makefile,v 1.7 2006/09/29 19:42:22 wintellect Exp $
# $FreeBSD: ports/x11-wm/Makefile,v 1.186 2006/09/10 15:15:38 vanilla Exp $
#

    COMMENT = X11 window managers

    SUBDIR += blackbox
    SUBDIR += boxtools
    SUBDIR += fluxbox
    SUBDIR += fluxbox-devel
    SUBDIR += libdockapp
    SUBDIR += openbox
    SUBDIR += pekwm
    SUBDIR += windowmaker
    SUBDIR += wmii

.include <bsd.port.subdir.mk>
