# $MidnightBSD: mports/x11-wm/Makefile,v 1.18 2007/10/12 14:47:25 ctriv Exp $
#

    COMMENT = X11 window managers

    SUBDIR += afterstep
    SUBDIR += blackbox
    SUBDIR += boxtools
    SUBDIR += etoile-azalea
    SUBDIR += etoile-azdock
    SUBDIR += fluxbox
    SUBDIR += fvwm2
    SUBDIR += kompmgr
    SUBDIR += libdockapp
    SUBDIR += metacity
    SUBDIR += mlvwm
    SUBDIR += obconf
    SUBDIR += openbox
    SUBDIR += pekwm
    SUBDIR += ratpoison
    SUBDIR += skippy-xd
    SUBDIR += twm
    SUBDIR += windowmaker
    SUBDIR += wmii

.include <bsd.port.subdir.mk>
