# $MidnightBSD: mports/x11-wm/Makefile,v 1.12 2007/03/13 06:21:17 laffer1 Exp $
#

    COMMENT = X11 window managers

    SUBDIR += blackbox
    SUBDIR += boxtools
    SUBDIR += etoile-azalea
    SUBDIR += etoile-azdock
    SUBDIR += fluxbox
    SUBDIR += fluxbox-devel
    SUBDIR += kompmgr
    SUBDIR += libdockapp
    SUBDIR += mlvwm
    SUBDIR += obconf
    SUBDIR += openbox
    SUBDIR += pekwm
    SUBDIR += skippy-xd
    SUBDIR += windowmaker
    SUBDIR += wmii

.include <bsd.port.subdir.mk>
