# $MidnightBSD: mports/x11-fonts/font-bh-ttf/Makefile,v 1.3 2011/05/08 15:25:56 laffer1 Exp $

PORTNAME=	font-bh-ttf
PORTVERSION=	1.0.3
PORTREVISION=	1
CATEGORIES=	x11-fonts

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X.Org Bigelow & Holmes TTF font
LICENSE=	unknown

XORG_CAT=	font

.include <bsd.port.mk>
