# $FreeBSD: ports/www/p5-HTML-Breadcrumbs/Makefile,v 1.2 2006/05/23 07:08:47 erwin Exp $
# $MidnightBSD$
#

PORTNAME=	HTML-Breadcrumbs
PORTVERSION=	0.7
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Module to produce HTML 'breadcrumb trails'
LICENSE=	perl

PERL_CONFIGURE=	yes

.include <bsd.port.mk>
