# $MidnightBSD$

PORTNAME=	XML-RegExp
PORTVERSION=	0.03
CATEGORIES=	textproc perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	XML
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Regular expressions for XML tokens
LICENSE=	perl

PERL_CONFIGURE=	yes

.include <bsd.port.mk>
