PORTNAME=	fastmap
PORTVERSION=	1.2.0
CATEGORIES=	databases
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Fast Implementation of a Key-Value Store
WWW=		https://cran.r-project.org/web/packages/fastmap/

LICENSE=	mit
LICENSE_FILE=	${WRKSRC}/LICENSE.note

USES=		compiler:c++17-lang cran:auto-plist,compiles

.include <bsd.port.mk>
