# $MidnightBSD: mports/multimedia/Makefile,v 1.7 2006/10/05 00:52:06 laffer1 Exp $
#

    COMMENT = Multimedia software

    SUBDIR += libdvdcss
    SUBDIR += libdvdread
    SUBDIR += libfame
    SUBDIR += libtheora
    SUBDIR += linux-realplayer
    SUBDIR += vcdimager
    SUBDIR += win32-codecs
    SUBDIR += xmms
    SUBDIR += xmms-skins

.include <bsd.port.subdir.mk>
