# $MidnightBSD: mports/ftp/Makefile,v 1.9 2007/04/02 00:52:57 laffer1 Exp $
#

    COMMENT = File Transfer Protocol 

    SUBDIR += curl
    SUBDIR += gnustep-ftp
    SUBDIR += linux-curl 
    SUBDIR += ncftp
    SUBDIR += ncftp2
    SUBDIR += ncftp3
    SUBDIR += ncftpd
    SUBDIR += php5-curl
    SUBDIR += php5-ftp
    SUBDIR += wget

.include <bsd.port.subdir.mk>
