PORTNAME=	praise
DISTVERSION=	1.0.0
PORTREVISION=	0
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Praise Users
WWW=		https://cran.r-project.org/web/packages/praise/

LICENSE=	mit
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		cran:auto-plist

NO_TEST=	yes

.include <bsd.port.mk>
