# $MidnightBSD: mports/x11/xbacklight/Makefile,v 1.2 2009/05/04 01:57:57 laffer1 Exp $

PORTNAME=	xbacklight
PORTVERSION=	1.1.1
PORTREVISION=	1
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Program to adjust backlight brightness
LICENSE=	x11

XORG_CAT=	app
USE_XORG=	x11 xrender xrandr

MAN1=		xbacklight.1
PLIST_FILES=	bin/xbacklight

.include <bsd.port.mk>
