# $MidnightBSD$
# $FreeBSD: head/graphics/php71-gd/Makefile 477442 2018-08-17 19:02:36Z joneum $

CATEGORIES=	graphics

MASTERDIR=	${.CURDIR}/../../lang/php71

PKGNAMESUFFIX=	-gd

TEST_TARGET=    test

.include "${MASTERDIR}/Makefile"

LIB_DEPENDS+=	libgd.so:graphics/gd
