# $MidnightBSD: mports/x11-fonts/font-misc-ethiopic/Makefile,v 1.3 2012/03/03 23:17:18 laffer1 Exp $

PORTNAME=	font-misc-ethiopic
PORTVERSION=	1.0.3
CATEGORIES=	x11-fonts

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X.Org miscellaneous Ethiopic font
LICENSE=	mit

XORG_CAT=	font
INSTALLS_TTF=	yes
FONTDIR=	TTF OTF

.include <bsd.port.mk>
