# $MidnightBSD: mports/net-im/Makefile,v 1.23 2011/05/28 05:10:37 laffer1 Exp $

COMMENT = Instant messaging

SUBDIR += aim
SUBDIR += etoile-stepchat
SUBDIR += etoile-xmppkit
SUBDIR += gossip
SUBDIR += grouch
SUBDIR += jabberd
SUBDIR += kopete
SUBDIR += libnice
SUBDIR += libpurple
SUBDIR += libtelepathy
SUBDIR += linux-ymessenger
SUBDIR += loudmouth
SUBDIR += meanwhile
SUBDIR += msn-proxy
SUBDIR += openfire
SUBDIR += p5-Net-XMPP
SUBDIR += pidgin
SUBDIR += pidgin-twitter
SUBDIR += pork
SUBDIR += sendxmpp
SUBDIR += telepathy-glib
SUBDIR += tmsnc

.include <bsd.port.subdir.mk>
