# $MidnightBSD: mports/net-im/Makefile,v 1.20 2010/01/21 01:56:50 laffer1 Exp $
#

    COMMENT = Instant messaging

    SUBDIR += aim
    SUBDIR += etoile-stepchat
    SUBDIR += etoile-xmppkit
    SUBDIR += gossip
    SUBDIR += grouch
    SUBDIR += jabberd
    SUBDIR += kopete
    SUBDIR += libnice
    SUBDIR += libpurple
    SUBDIR += libtelepathy
    SUBDIR += loudmouth
    SUBDIR += meanwhile
    SUBDIR += msn-proxy
    SUBDIR += p5-Net-XMPP
    SUBDIR += pidgin
    SUBDIR += pidgin-twitter
    SUBDIR += pork
    SUBDIR += sendxmpp
    SUBDIR += telepathy-glib
    SUBDIR += tmsnc

.include <bsd.port.subdir.mk>
