# $MidnightBSD: mports/net-im/Makefile,v 1.8 2007/05/03 06:07:03 laffer1 Exp $
#

    COMMENT = Instant messaging

    SUBDIR += aim
    SUBDIR += gaim
    SUBDIR += grouch
    SUBDIR += jabberd
    SUBDIR += kopete
    SUBDIR += meanwhile
    SUBDIR += p5-Net-XMPP
    SUBDIR += pork
    SUBDIR += sendxmpp
    SUBDIR += tmsnc

.include <bsd.port.subdir.mk>
