# $MidnightBSD: mports/mail/pantomime/Makefile,v 1.6 2012/02/03 03:43:17 laffer1 Exp $

PORTNAME=	pantomime
PORTVERSION=	1.2.0
PORTREVISION=	1
CATEGORIES=	mail gnustep
MASTER_SITES=	http://download.gna.org/gnustep-nonfsf/
DISTNAME=	Pantomime-${PORTVERSION}

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Mail/MIME handling library for GNUstep
LICENSE=	lgpl2.1

USE_GMAKE=	yes
USE_GNUSTEP=	yes
USE_GNUSTEP_BACK=	yes
USE_GNUSTEP_BUILD=	yes
USE_GNUSTEP_INSTALL=	yes
USE_GNUSTEP_LDCONFIG=	${GNUSTEP_LOCAL_LIBRARIES}

DEFAULT_LIBVERSION=	1.2

.include <bsd.port.mk>
