PORTNAME=	httpclient
PORTVERSION=	2.9.0
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Yet another HTTP client implementation by NaHi
WWW=		https://github.com/nahi/httpclient

LICENSE=	bsd2 ruby
LICENSE_COMB=	dual

NO_ARCH=	yes
USES=		gem

RUN_DEPENDS=	rubygem-mutex_m>=0:devel/rubygem-mutex_m

PLIST_FILES=	bin/httpclient

.include <bsd.port.mk>
