# $FreeBSD: head/textproc/php72-xsl/Makefile 475229 2018-07-24 08:44:32Z tz $

CATEGORIES=	textproc

MASTERDIR=	${.CURDIR}/../../lang/php72

PKGNAMESUFFIX=	-xsl

TEST_TARGET=    test

.include "${MASTERDIR}/Makefile"
