PORTNAME=	ruby-yadis
PORTVERSION=	0.3.4
CATEGORIES=	net rubygems
MASTER_SITES=	RG

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Yadis Service discovery library written in pure Ruby
WWW=		http://www.openidenabled.com/yadis/libraries/ruby/

LICENSE=	Apache-2.0

NO_ARCH=	yes

USES=		gem

.include <bsd.port.mk>
