# $MidnightBSD$

PORTNAME=	parsedatetime
PORTVERSION=	2.1
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Python module for parsing 'human readable' date/time expressions

LICENSE=	apache2

USES=	python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
