# New ports collection makefile for:	xfwp
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11/xfwp/Makefile,v 1.1 2007/05/19 20:27:53 flz Exp $
# $MidnightBSD$
#

PORTNAME=	xfwp
PORTVERSION=	1.0.1
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X firewall proxy
LICENSE=	x11

XORG_CAT=	app
USE_XORG=	x11 ice xproxymngproto

PLIST_FILES=	bin/xfwp

MAN1=		xfwp.1

.include <bsd.port.mk>
