# Created by: Dmitry Marakasov <amdmi3@FreeBSD.org>

PORTNAME=	aioftp
PORTVERSION=	0.18.1
CATEGORIES=	ftp python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	FTP client/server for asyncio

LICENSE=	apache2
LICENSE_FILE=	${WRKSRC}/license.txt

USES=		python:3.7+
USE_PYTHON=	autoplist distutils
NO_ARCH=	yes
NO_TEST=	yes

.include <bsd.port.mk>
