# $FreeBSD: ports/x11/xlsatoms/Makefile,v 1.1 2007/05/19 20:27:59 flz Exp $
# $MidnightBSD: mports/x11/xlsatoms/Makefile,v 1.1 2007/10/08 15:07:04 ctriv Exp $

PORTNAME=	xlsatoms
PORTVERSION=	1.0.2
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	List interned atoms defined on a server
LICENSE=	x11

XORG_CAT=	app
USE_XORG=	x11 xmuu

PLIST_FILES=	bin/xlsatoms

MAN1=		xlsatoms.1

.include <bsd.port.mk>
