# New ports collection makefile for:	gstreamer-plugins-dts
# Date created:			3 Oct 2004
# Whom:				Michael Johnson <ahze@FreeBSD.org>
#
# $MidnightBSD$
# $FreeBSD: ports/multimedia/gstreamer-plugins-dts/Makefile,v 1.11 2007/08/18 05:57:55 marcus Exp $
#

PORTREVISION=	3
CATEGORIES=	multimedia

COMMENT=	Gstreamer dts plugin

GST_PLUGIN=	dts

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
