# New ports collection makefile for:	listres
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11/listres/Makefile,v 1.1 2007/05/19 20:27:04 flz Exp $
# $MidnightBSD$
#

PORTNAME=	listres
PORTVERSION=	1.0.1
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	List resources in widgets
LICENSE=	x11

XORG_CAT=	app
USE_XORG=	x11 xt xmu xaw

PLIST_FILES=	bin/listres

MAN1=		listres.1

.include <bsd.port.mk>
