# New ports collection makefile for:   osh
# Date created:        29 December 2000
# Whom:                George Reid <greid@ukug.uk.freebsd.org>
#
# $MidnightBSD: mports/shells/osh/Makefile,v 1.2 2007/05/17 17:56:07 ctriv Exp $ 
# $FreeBSD: ports/shells/osh/Makefile,v 1.17 2006/08/07 07:58:26 miwi Exp $
#

PORTNAME=	osh
DISTVERSION=	20090527
CATEGORIES=	shells
MASTER_SITES=	http://v6shell.org/src/ \
		http://freebsd.unixfreunde.de/sources/

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	An implementation of the UNIX 6th Edition shell
LICENSE=	bsd4

FAKE_OPTS=	trueprefix
MAN1=		fd2.1 goto.1 if.1 osh.1

.include <bsd.port.mk>
