# $MidnightBSD: mports/x11-drivers/xf86-input-calcomp/Makefile,v 1.1 2007/10/11 21:33:42 ctriv Exp $

PORTNAME=	xf86-input-calcomp
PORTVERSION=	1.1.2
CATEGORIES=	x11-drivers

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X.Org calcomp input driver
LICENSE=	x11

XORG_CAT=	driver
MAN4=		calcomp.4x

.include <bsd.port.mk>
