# $MidnightBSD: mports/x11-drivers/xf86-input-calcomp/Makefile,v 1.2 2009/03/15 21:03:12 laffer1 Exp $

PORTNAME=	xf86-input-calcomp
PORTVERSION=	1.1.2
PORTREVISION=	1
CATEGORIES=	x11-drivers

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X.Org calcomp input driver
LICENSE=	x11

XORG_CAT=	driver
MAN4=		calcomp.4x

.include <bsd.port.mk>
