PORTNAME=	xf86-input-mouse
PORTVERSION=	1.9.3
PORTREVISION=	3
CATEGORIES=	x11-drivers

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X.Org mouse input driver

LICENSE=	mit
LICENSE_FILE=	${WRKSRC}/COPYING

USES=		pathfix xorg-cat:driver

CONFIGURE_TARGET=      ${ARCH}-portbld-freebsd10.4

.include <bsd.port.mk>
