# $MidnightBSD: mports/audio/Makefile,v 1.2 2006/09/26 15:45:33 archite Exp $
#

    COMMENT = Audio tools

    SUBDIR += libao
    SUBDIR += libaudiofile
    SUBDIR += libid3tag

.include <bsd.port.subdir.mk>
