# $MidnightBSD: mports/audio/Makefile,v 1.23 2007/01/11 16:49:06 wintellect Exp $
#

    COMMENT = Audio tools

    SUBDIR += arts
    SUBDIR += artswrapper
    SUBDIR += cdparanoia
    SUBDIR += flac
    SUBDIR += jack
    SUBDIR += lame
    SUBDIR += liba52-devel
    SUBDIR += libao
    SUBDIR += libaudiofile
    SUBDIR += libcddb
    SUBDIR += libid3tag
    SUBDIR += libmad
    SUBDIR += libmikmod
    SUBDIR += libmodplug
    SUBDIR += libogg
    SUBDIR += libsndfile
    SUBDIR += libvorbis
    SUBDIR += madplay
    SUBDIR += mpg123
    SUBDIR += nas
    SUBDIR += openal
    SUBDIR += portaudio
    SUBDIR += sdl_mixer
    SUBDIR += speex
    SUBDIR += wmmp3
    SUBDIR += wmsmixer

.include <bsd.port.subdir.mk>
