# $FreeBSD: ports/x11/libXevie/Makefile,v 1.1 2007/05/19 20:26:50 flz Exp $
# $MidnightBSD$

PORTNAME=	libXevie
PORTVERSION=	1.0.3
PORTREVISION=	3
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	The Xevie library

LICENSE=	mit

XORG_CAT=	lib
USE_XORG=	x11 xext xorgproto

.include <bsd.port.mk>
