# $MidnightBSD: mports/dns/Makefile,v 1.5 2006/10/31 23:35:03 wintellect Exp $
#

    COMMENT = Domain Name Service tools

    SUBDIR += bind9
    SUBDIR += c-ares
    SUBDIR += ddclient
    SUBDIR += libidn
    SUBDIR += mdnsd
    SUBDIR += p5-Net-DNS

.include <bsd.port.subdir.mk>
