# $MidnightBSD: mports/dns/Makefile,v 1.18 2009/04/14 03:05:27 laffer1 Exp $

COMMENT = Domain Name Service tools

SUBDIR += ares
SUBDIR += bind95
SUBDIR += bind96
SUBDIR += bindgraph
SUBDIR += c-ares
SUBDIR += ddclient
SUBDIR += ez-ipupdate
SUBDIR += inadyn
SUBDIR += libidn
SUBDIR += mdnsd
SUBDIR += nslint
SUBDIR += p5-Net-DNS
SUBDIR += p5-Net-DNS-Resolver-Programmable
SUBDIR += pdnsd
SUBDIR += udns

.include <bsd.port.subdir.mk>
