PORTNAME=	xconsole
PORTVERSION=	1.0.8
CATEGORIES=	x11
DISTFILES=	xconsole-${PORTVERSION}.tar.xz

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Monitor system console messages with X

LICENSE=	mit

USES=		xorg xorg-cat:app tar:xz
USE_XORG=	xt xaw

.include <bsd.port.mk>
