# $MidnightBSD: mports/archivers/Makefile,v 1.9 2006/10/02 16:46:01 laffer1 Exp $

    COMMENT = Archivers

    SUBDIR += arc
    SUBDIR += arj
    SUBDIR += bzip
    SUBDIR += bzip2
    SUBDIR += gtar
    SUBDIR += gzip
    SUBDIR += gzrecover
    SUBDIR += lha
    SUBDIR += lzo2
    SUBDIR += p7zip
    SUBDIR += rar
    SUBDIR += rpm
    SUBDIR += rpm2cpio
    SUBDIR += unace
    SUBDIR += unarj
    SUBDIR += unrar
    SUBDIR += unzip
    SUBDIR += unzoo
    SUBDIR += zip
    SUBDIR += zoo

.include <bsd.port.subdir.mk>
