# $MidnightBSD: mports/x11-drivers/xf86-video-glint/Makefile,v 1.3 2011/05/07 21:20:04 laffer1 Exp $

PORTNAME=	xf86-video-glint
PORTVERSION=	1.2.5
CATEGORIES=	x11-drivers

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X.Org glint display driver
LICENSE=	mit

USE_GL=		gl

XORG_CAT=	driver
USE_XORG=	xf86driproto videoproto xextproto xf86dgaproto glproto
MAN4=		glint.4x

.include <bsd.port.mk>
