# New ports collection makefile for:	php5-gmp
# Date created:			7 Jul 2004
# Whom:				Alex Dupre <ale@FreeBSD.org>
#
# $MidnightBSD$
# $FreeBSD: ports/math/php5-gmp/Makefile,v 1.2 2006/05/10 14:46:47 ale Exp $
#

PORTREVISION=	1
CATEGORIES=	math

MASTERDIR=	${.CURDIR}/../../lang/php5

PKGNAMESUFFIX=	-gmp

.include "${MASTERDIR}/Makefile"
