# $MidnightBSD$

PORTNAME=	libXfontcache
PORTVERSION=	1.0.5
PORTREVISION=	4
CATEGORIES=	x11-fonts

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	The Xfontcache library

LICENSE=	mit

XORG_CAT=	lib
USE_XORG=	x11 xext xorgproto

.include <bsd.port.mk>
