PORTNAME=	Proc-Queue
PORTVERSION=	1.23
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Limit the number of child processes running
WWW=		https://metacpan.org/release/Proc-Queue

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
