PORTNAME=	tzinfo-data
PORTVERSION=	1.2024.2
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	IANA Time Zone database for TZInfo
WWW=		https://tzinfo.github.io/ \
		https://github.com/tzinfo/tzinfo-data

LICENSE=	mit
LICENSE_FILE=	${WRKSRC}/LICENSE

RUN_DEPENDS=	rubygem-tzinfo>=1.0.0:devel/rubygem-tzinfo

USES=		gem

NO_ARCH=	yes

.include <bsd.port.mk>
