# Created by: Stefan Esser <se@FreeBSD.org>

PORTNAME=	pdf
PORTVERSION=	1.13
CATEGORIES=	print python
MASTER_SITES=	http://pybrary.net/pyPdf/
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	pyPdf-${PORTVERSION}

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Pure-Python PDF toolkit

LICENSE=	bsd3

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
