PORTNAME=	Horde_Oauth
DISTVERSION=	2.0.4
CATEGORIES=	security www pear

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Horde OAuth client/server
WWW=		https://pear.horde.org

LICENSE=	NONE

USES=		horde php cpe
USE_HORDE_RUN=	Horde_Exception \
		Horde_Http \
		Horde_Util

.include <bsd.port.mk>
