PORTNAME=	net-ping
PORTVERSION=	2.0.8
CATEGORIES=	net rubygems
MASTER_SITES=	RG

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Collection of classes that provide different ways to ping computers
WWW=		https://github.com/chernesk/net-ping

LICENSE=	Apache-2.0

USES=		gem

.include <bsd.port.mk>
