# $MidnightBSD: mports/comms/lrzsz/Makefile,v 1.2 2007/11/11 00:15:17 laffer1 Exp $

PORTNAME=	lrzsz
PORTVERSION=	0.12.20
PORTREVISION=	2
CATEGORIES=	comms
MASTER_SITES=	http://www.ohse.de/uwe/releases/

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Receive/Send files via X/Y/ZMODEM protocol.  (unrestrictive)
LICENSE=	gpl2

GNU_CONFIGURE=	yes
ALL_TARGET=	all # vcheck
MAN1=		lrz.1 lsz.1

.include <bsd.port.mk>
