# $MidnightBSD$

COMMENT = Software support for handheld devices (Palm, PocketPC, ...)

SUBDIR += bibelot
SUBDIR += imgvtopgm
SUBDIR += jfconv
SUBDIR += libmal
SUBDIR += mdbconv
SUBDIR += palmos-sdk
SUBDIR += pilot-link
SUBDIR += pilot_makedoc

.include <bsd.port.subdir.mk>
