PORTNAME=	alt-aspell
SPELLVERSION=	6-de-alt-2.1-1
PORTREVISION=	1
PORTEPOCH=	1
CATEGORIES=	german textproc
MASTER_SITES=	GNU/aspell/dict/de-alt

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Aspell German Old Spelling (Deutsch - alte Rechtschreibung) dictionary

LICENSE=	lgpl2.1

DICT=	 	de

.include "${.CURDIR}/../../textproc/aspell/Makefile.inc"
.include <bsd.port.post.mk>
