# $MidnightBSD$

PORTNAME=	xf86-video-savage
PORTVERSION=	2.3.7
CATEGORIES=	x11-drivers

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X.Org savage display driver

LICENSE=	mit

USE_GL=		gl

XORG_CAT=	driver
USE_XORG=	xf86driproto videoproto xextproto glproto
MAN4=		savage.4x

.include <bsd.port.mk>
