# $FreeBSD: ports/x11/xcmsdb/Makefile,v 1.1 2007/05/19 20:27:41 flz Exp $
# $MidnightBSD: mports/x11/xcmsdb/Makefile,v 1.2 2011/05/07 02:48:44 laffer1 Exp $

PORTNAME=	xcmsdb
PORTVERSION=	1.0.3
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Device Color Characterization utility for X
LICENSE=	x11

XORG_CAT=	app
USE_XORG=	x11

PLIST_FILES=	bin/xcmsdb

MAN1=		xcmsdb.1

.include <bsd.port.mk>
