PORTNAME=	font-bh-ttf
PORTVERSION=	1.0.4
CATEGORIES=	x11-fonts
DISTFILES=	font-bh-ttf-1.0.4.tar.xz

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X.Org Bigelow & Holmes TTF font
WWW=		https://www.x.org/

LICENSE=	unknown

USES=		xorg-cat:font tar:xz

.include <bsd.port.mk>
