PORTNAME=	graphite2
PORTVERSION=	1.3.10
DISTVERSIONSUFFIX=	-1.el7_3
CATEGORIES=	graphics linux

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Rendering capabilities for complex non-Roman writing systems (Linux CentOS ${LINUX_DIST_VER})
WWW=		https://graphite.sil.org

LICENSE=	lgpl2.1

USES=		cpe linux:c7
CPE_VENDOR=	sil
USE_LDCONFIG=	yes
USE_LINUX_RPM=	yes

DESCR=		${.CURDIR}/../${PORTNAME}/pkg-descr

OPTIONS_DEFINE=	DOCS

.include <bsd.port.mk>
