PORTNAME=	Sys-Hostname-Long
PORTVERSION=	1.5
PORTREVISION=	1
CATEGORIES=	sysutils perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Try every conceivable way to get full hostname
WWW=		https://metacpan.org/release/Sys-Hostname-Long

LICENSE=	artistic gpl+
LICENSE_COMB=	dual

USES=	perl5
USE_PERL5=	configure
NO_ARCH=	yes

.include <bsd.port.mk>
