# New ports collection makefile for:	xf86-video-neomagic
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11-drivers/xf86-video-neomagic/Makefile,v 1.2 2007/09/15 14:04:27 flz Exp $
# $MidnightBSD$
#

PORTNAME=	xf86-video-neomagic
PORTVERSION=	1.1.1
CATEGORIES=	x11-drivers

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X.Org neomagic display driver
LICENSE=	x11

XORG_CAT=	driver
USE_XORG=	videoproto xextproto xf86dgaproto
MAN4=		neomagic.4x

.include <bsd.port.mk>
