# $MidnightBSD$

PORTNAME=	freedesktop-sound-theme
PORTVERSION=	0.7
PORTREVISION=	3
CATEGORIES=	audio gnome
MASTER_SITES=	FREEBSD_LOCAL
MASTER_SITE_SUBDIR=	kwm
DISTNAME=	sound-theme-freedesktop-${PORTVERSION}

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Sound theme based on the FreeDesktop specification

LICENSE=	unknown

USES=		gettext gmake tar:bzip2
USE_GNOME=	intlhack
GNU_CONFIGURE=	yes

.include <bsd.port.mk>
