# $MidnightBSD: mports/x11/xlsclients/Makefile,v 1.4 2012/03/03 01:52:56 laffer1 Exp $

PORTNAME=	xlsclients
PORTVERSION=	1.1.2
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	List client applications running on a display
LICENSE=	mit

XORG_CAT=	app
USE_XORG=	x11 xmuu

PLIST_FILES=	bin/xlsclients

MAN1=		xlsclients.1

.include <bsd.port.mk>
