# $MidnightBSD: mports/x11/renderproto/Makefile,v 1.3 2011/05/07 02:17:38 laffer1 Exp $

PORTNAME=	renderproto
PORTVERSION=	0.11.1
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	RenderProto protocol headers
LICENSE=	x11

XORG_CAT=	proto

.include <bsd.port.mk>
