PORTNAME=	dosfstools
PORTVERSION=	3.0.20
DISTVERSIONSUFFIX=	-10.el7
CATEGORIES=	filesystems sysutils linux

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Utilities for MS-DOS FAT filesystems (CentOS ${LINUX_DIST_VER})
WWW=		https://github.com/dosfstools/dosfstools

LICENSE=	gpl3+

USES=		cpe linux:c7
USE_LINUX_RPM=	nolib
CPE_VENDOR=	dosfstools_project

OPTIONS_DEFINE=	DOCS
PLIST=		${PKGDIR}/pkg-plist

.include <bsd.port.mk>
