# $MidnightBSD$

PORTNAME=	libXp
PORTVERSION=	1.0.2
PORTREVISION=	1
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X print library

LICENSE=	mit

XORG_CAT=	lib
USE_XORG=	x11 xext xextproto xau printproto:both

.include <bsd.port.mk>
