COMMENT = Monetary, financial and related applications

SUBDIR += expense
SUBDIR += libofx
SUBDIR += py-bitcoin
SUBDIR += py-pycoin
SUBDIR += py-stripe
SUBDIR += py-vatnumber
SUBDIR += py-ystockquote
SUBDIR += qtbitcointrader
SUBDIR += quickfix
SUBDIR += rubygem-money
SUBDIR += sql-ledger
SUBDIR += venice
SUBDIR += weberp
SUBDIR += wmstock

.include <bsd.port.subdir.mk>
