# New ports collection makefile for:	xload
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11/xload/Makefile,v 1.2 2007/07/02 17:20:56 lesi Exp $
# $MidnightBSD$
#

PORTNAME=	xload
PORTVERSION=	1.0.2
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	System load average display for X
LICENSE=	x11

XORG_CAT=	app
USE_XORG=	xt xaw

MAN1=		xload.1

.include <bsd.port.mk>
