# $MidnightBSD$

PORTNAME=	xcompmgr
PORTVERSION=	1.1.6
CATEGORIES=	x11-wm

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	A sample X compositing manager

LICENSE=	mit

XORG_CAT=	app
USE_XORG=	x11 xcomposite xfixes xdamage xrender

PLIST_FILES=	bin/${PORTNAME}

MAN1=		xcompmgr.1

.include <bsd.port.mk>
