# $MidnightBSD: mports/x11-wm/xcompmgr/Makefile,v 1.4 2013/06/16 01:07:04 laffer1 Exp $

PORTNAME=	xcompmgr
PORTVERSION=	1.1.6
CATEGORIES=	x11-wm

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	A sample X compositing manager

LICENSE=	mit

XORG_CAT=	app
USE_XORG=	x11 xcomposite xfixes xdamage xrender

PLIST_FILES=	bin/${PORTNAME}

MAN1=		xcompmgr.1

.include <bsd.port.mk>
