PORTNAME=	bindr
PORTVERSION=	0.1.2
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Parametrized Active Bindings
WWW=		https://cran.r-project.org/web/packages/bindr/

LICENSE=	gpl2+

USES=		cran:auto-plist,compiles

.include <bsd.port.mk>
