# $MidnightBSD: mports/x11-drivers/xf86-input-tek4957/Makefile,v 1.2 2009/03/27 23:38:53 laffer1 Exp $

PORTNAME=	xf86-input-tek4957
PORTVERSION=	1.2.0
PORTREVISION=	1
CATEGORIES=	x11-drivers

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X.Org tek4957 input driver
LICENSE=	x11

IGNORE=		Unmaintained upstream.

XORG_CAT=	driver
MAN4=		tek4957.4x

.include <bsd.port.mk>
