# $MidnightBSD$
# $FreeBSD: ports/multimedia/gnustep-mplayer/Makefile,v 1.4 2007/05/19 20:17:15 flz Exp $

PORTNAME=	mplayer
PORTVERSION=	0.4.1
PORTREVISION=	5
CATEGORIES=	multimedia gnustep
MASTER_SITES=	http://www.sonappart.net/gnustep/mplayer/
PKGNAMEPREFIX=	gnustep-
DISTNAME=	Mplayer-0.4-1

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	GNUstep port of MPlayerOSX

LICENSE=        gpl3

USES=		gnustep
USE_GNUSTEP=	back build

WRKSRC=		${WRKDIR}/mplayerPort/Sources

.include <bsd.port.mk>
