# $MidnightBSD: mports/x11-fonts/fontsproto/Makefile,v 1.1 2007/10/03 18:05:51 ctriv Exp $

PORTNAME=	fontsproto
PORTVERSION=	2.0.2
CATEGORIES=	x11-fonts

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Fonts extension headers
LICENSE=	x11

XORG_CAT=	proto

.include <bsd.port.mk>
