# $MidnightBSD: mports/net-im/Makefile,v 1.16 2008/06/25 14:33:01 laffer1 Exp $
#

    COMMENT = Instant messaging

    SUBDIR += aim
    SUBDIR += etoile-stepchat
    SUBDIR += gossip
    SUBDIR += grouch
    SUBDIR += jabberd
    SUBDIR += kopete
    SUBDIR += libpurple
    SUBDIR += loudmouth
    SUBDIR += meanwhile
    SUBDIR += msn-proxy
    SUBDIR += p5-Net-XMPP
    SUBDIR += pidgin
    SUBDIR += pork
    SUBDIR += sendxmpp
    SUBDIR += telepathy-glib
    SUBDIR += tmsnc

.include <bsd.port.subdir.mk>
