# New ports collection makefile for:	xmore
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11/xmore/Makefile,v 1.1 2007/05/19 20:28:02 flz Exp $
# $MidnightBSD$
#

PORTNAME=	xmore
PORTVERSION=	1.0.1
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Plain text display program for X
LICENSE=	x11

XORG_CAT=	app
USE_XORG=	xt xaw xp xprintutil

MAN1=		xmore.1

.include <bsd.port.mk>
