# $MidnightBSD: mports/archivers/Makefile,v 1.14 2007/01/20 15:56:39 wintellect Exp $

    COMMENT = Archivers

    SUBDIR += arc
    SUBDIR += arj
    SUBDIR += bzip
    SUBDIR += bzip2
    SUBDIR += freetar
    SUBDIR += gtar
    SUBDIR += gzip
    SUBDIR += gzrecover
    SUBDIR += lha
    SUBDIR += libunrar
    SUBDIR += lzo2
    SUBDIR += p7zip
    SUBDIR += pecl-zip
    SUBDIR += php5-bz2
    SUBDIR += php5-zlib
    SUBDIR += rar
    SUBDIR += rpm
    SUBDIR += rpm2cpio
    SUBDIR += unace
    SUBDIR += unarj
    SUBDIR += unrar
    SUBDIR += unzip
    SUBDIR += unzoo
    SUBDIR += zip
    SUBDIR += zipios++
    SUBDIR += zoo

.include <bsd.port.subdir.mk>
