# $MidnightBSD: mports/archivers/Makefile,v 1.2 2006/09/17 23:55:31 laffer1 Exp $

    COMMENT = Archivers

    SUBDIR += arc
    SUBDIR += gtar
    SUBDIR += gzip
    SUBDIR += gzrecover
    SUBDIR += p7zip
    SUBDIR += rar
    SUBDIR += rpm
    SUBDIR += unrar
    SUBDIR += unzip
    SUBDIR += zip

.include <bsd.port.subdir.mk>
