# Created by: Fabiano Sidler <fabianosidler@swissonline.ch>

PORTNAME=	fpdf
PORTVERSION=	1.7.2
CATEGORIES=	print python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Simple PDF generation for Python

LICENSE=	lgpl3

USES=		python
USE_PYTHON=	autoplist distutils
NO_ARCH=	yes

.include <bsd.port.mk>
