# $MidnightBSD: mports/x11/viewres/Makefile,v 1.3 2011/09/20 23:34:41 laffer1 Exp $

PORTNAME=	viewres
PORTVERSION=	1.0.4
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Graphical class browser for Xt
LICENSE=	mit

XORG_CAT=	app
USE_XORG=	xt xaw

MAN1=		viewres.1

.include <bsd.port.mk>
