# $MidnightBSD: mports/x11-fonts/font-jis-misc/Makefile,v 1.2 2011/05/08 17:37:29 laffer1 Exp $

PORTNAME=	font-jis-misc
PORTVERSION=	1.0.3
CATEGORIES=	x11-fonts

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X.Org miscellaneous JIS fonts
LICENSE=	unknown

XORG_CAT=	font

.include <bsd.port.mk>
