# $MidnightBSD: mports/ftp/Makefile,v 1.12 2007/04/02 01:34:27 laffer1 Exp $
#

    COMMENT = File Transfer Protocol 

    SUBDIR += curl
    SUBDIR += gnustep-ftp
    SUBDIR += linux-curl 
    SUBDIR += lukemftp
    SUBDIR += ncftp
    SUBDIR += ncftp2
    SUBDIR += ncftp3
    SUBDIR += ncftpd
    SUBDIR += php5-curl
    SUBDIR += php5-ftp
    SUBDIR += wget
    SUBDIR += wu-ftpd
    SUBDIR += wu-ftpd+ipv6

.include <bsd.port.subdir.mk>
