# $MidnightBSD: mports/ftp/Makefile,v 1.20 2008/04/12 00:31:19 laffer1 Exp $
#

    COMMENT = File Transfer Protocol 

    SUBDIR += curl
    SUBDIR += ftpcopy
    SUBDIR += gnustep-ftp
    SUBDIR += kwebget
    SUBDIR += linux-curl 
    SUBDIR += mirror
    SUBDIR += ncftp
    SUBDIR += ncftp2
    SUBDIR += ncftp3
    SUBDIR += ncftpd
    SUBDIR += php5-curl
    SUBDIR += php5-ftp
    SUBDIR += proftpd
    SUBDIR += tnftp
    SUBDIR += wget
    SUBDIR += wu-ftpd
    SUBDIR += wu-ftpd+ipv6

.include <bsd.port.subdir.mk>
