# $MidnightBSD$

PORTNAME=	hscolour
PORTVERSION=	1.20.3
PORTREVISION=	8
PORTEPOCH=	1
CATEGORIES=	print haskell

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Colourise Haskell code

LICENSE=	gpl2

EXECUTABLE=	HsColour

.include "${.CURDIR}/../../lang/ghc/bsd.cabal.mk"
.include <bsd.port.mk>
