# $FreeBSD: head/textproc/php74-xmlwriter/Makefile 512406 2019-09-20 12:21:11Z tz $

CATEGORIES=	textproc

MASTERDIR=	${.CURDIR}/../../lang/php74

PKGNAMESUFFIX=	-xmlwriter

NO_TEST=	yes

.include "${MASTERDIR}/Makefile"
