# $MidnightBSD: mports/java/Makefile,v 1.25 2011/05/28 05:10:29 laffer1 Exp $

COMMENT = Java 

SUBDIR += berkeley-db
SUBDIR += bluej
SUBDIR += bouncycastle
SUBDIR += classpath
SUBDIR += cos
SUBDIR += diablo-jdk15
SUBDIR += diablo-jdk16
SUBDIR += diablo-jre15
SUBDIR += diablo-jre16
SUBDIR += jai
SUBDIR += jai-imageio
SUBDIR += jakarta-bcel
SUBDIR += jakarta-commons-cli
SUBDIR += jakarta-commons-lang
SUBDIR += jakarta-commons-logging
SUBDIR += jakarta-commons-primitives
SUBDIR += jakarta-oro
SUBDIR += jakarta-regexp
SUBDIR += jakarta-struts
SUBDIR += jamvm
SUBDIR += javavmwrapper
SUBDIR += jaxen
SUBDIR += jboss4
SUBDIR += jdbcpool
SUBDIR += jdom
SUBDIR += jikes
SUBDIR += junit
SUBDIR += kaffe
SUBDIR += linux-blackdown-jdk14
SUBDIR += linux-sun-jdk13
SUBDIR += linux-sun-jdk14
SUBDIR += linux-sun-jdk15
SUBDIR += linux-sun-jdk16
SUBDIR += linux-sun-jre16
SUBDIR += maven2
SUBDIR += netbeans61
SUBDIR += netbeans55
SUBDIR += openjdk6
SUBDIR += xdoclet

.include <bsd.port.subdir.mk>
