# $MidnightBSD$
# $FreeBSD: ports/graphics/gir-repository-goocanvas/Makefile,v 1.1 2009/11/28 20:06:31 marcus Exp $

CATEGORIES=	graphics

MASTERDIR=	${.CURDIR}/../../devel/gir-repository

PKGNAMESUFFIX=	-goocanvas

.include "${MASTERDIR}/bsd.gir.mk"
