# $MidnightBSD: mports/www/Makefile,v 1.4 2006/09/23 22:41:48 laffer1 Exp $
# $FreeBSD: ports/www/Makefile,v 1.1564 2006/09/12 08:28:30 miwi Exp $
#

    COMMENT = Ports related to the World Wide Web

    SUBDIR += libwww
    SUBDIR += links
    SUBDIR += linux-mozilla
    SUBDIR += linux-seamonkey
    SUBDIR += lynx
    SUBDIR += opera

.include <bsd.port.subdir.mk>
