# $FreeBSD: head/devel/php74-shmop/Makefile 512406 2019-09-20 12:21:11Z tz $

CATEGORIES=	devel

MASTERDIR=	${.CURDIR}/../../lang/php74

PKGNAMESUFFIX=	-shmop

TEST_TARGET=    test

.include "${MASTERDIR}/Makefile"
