# $MidnightBSD$

PORTNAME=	Text-TabularDisplay
PORTVERSION=	1.38
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Display text in formatted table output

LICENSE=	gpl2

USES=		perl5
USE_PERL5=	configure
PERL_CONFIGURE=	yes

.include <bsd.port.mk>
