PORTNAME=	BH
DISTVERSION=	1.87.0-1
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Boost C++ Header Files
WWW=		https://cran.r-project.org/web/packages/BH/

LICENSE=	BSL-1.0

USES=		cran:auto-plist

.include <bsd.port.mk>
