# $MidnightBSD: mports/misc/Makefile,v 1.15 2007/01/20 15:37:18 laffer1 Exp $
#

    COMMENT = Miscellaneous utilities

    SUBDIR += brs
    SUBDIR += compat4x
    SUBDIR += compat5x
    SUBDIR += gnomehier
    SUBDIR += gnustep-examples
    SUBDIR += help2man
    SUBDIR += hicolor-icon-theme
    SUBDIR += kde-xdg-env
    SUBDIR += kdeedu3
    SUBDIR += kdehier
    SUBDIR += kdeutils3
    SUBDIR += ldconfig_compat
    SUBDIR += localedata
    SUBDIR += mime-support
    SUBDIR += php5-calendar
    SUBDIR += shared-mime-info

.include <bsd.port.subdir.mk>
