# $MidnightBSD: mports/misc/Makefile,v 1.11 2006/11/24 18:35:29 laffer1 Exp $
#

    COMMENT = Miscellaneous utilities

    SUBDIR += brs
    SUBDIR += compat4x
    SUBDIR += compat5x
    SUBIDR += gnomehier
    SUBDIR += gnustep-examples
    SUBDIR += help2man
    SUBDIR += hicolor-icon-theme
    SUBDIR += kde-xdg-env
    SUBDIR += kdehier
    SUBDIR += ldconfig_compat
    SUBDIR += localedata
    SUBDIR += mime-support
    SUBDIR += shared-mime-info

.include <bsd.port.subdir.mk>
