# $MidnightBSD$

PORTNAME=	libXinerama
PORTVERSION=	1.1.3
PORTREVISION=	1
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X11 Xinerama library

LICENSE=	mit

XORG_CAT=	lib
USE_XORG=	x11 xext xextproto xineramaproto:both

.include <bsd.port.mk>
