# $MidnightBSD: mports/x11-drivers/xf86-video-voodoo/Makefile,v 1.3 2009/08/21 02:25:00 laffer1 Exp $

PORTNAME=	xf86-video-voodoo
PORTVERSION=	1.2.4
CATEGORIES=	x11-drivers

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X.Org voodoo display driver
LICENSE=	x11

XORG_CAT=	driver
USE_XORG=	xf86dgaproto xextproto
MAN4=		voodoo.4x

.include <bsd.port.mk>
