# $MidnightBSD: mports/textproc/localize/Makefile,v 1.2 2011/11/10 21:07:29 laffer1 Exp $

PORTNAME=	localize
PORTVERSION=	0.0.1
PORTREVISION=	2
CATEGORIES=	textproc gnustep
MASTER_SITES=	http://www.eskimo.com/~pburns/Localize/files/
DISTNAME=	Localize-20040424

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Application to aid in the translation of .strings files
LICENSE=	gpl2

USE_GNUSTEP=	yes
USE_GNUSTEP_BACK=	yes
USE_GNUSTEP_BUILD=	yes
USE_GNUSTEP_INSTALL=	yes

WRKSRC=		${WRKDIR}/Localize

.include <bsd.port.mk>
