# $FreeBSD: head/multimedia/gstreamer1-plugins-v4l2/Makefile 351947 2014-04-23 14:22:47Z tijl $

PORTREVISION=	0
CATEGORIES=	multimedia
PKGNAMESUFFIX=	1-plugins-v4l2

COMMENT=	Gstreamer Video 4 Linux 2 source plugin

GST_PLUGIN=	gst_v4l2
DIST=		good

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
