# $MidnightBSD$
# $FreeBSD: ports/databases/p5-SQL-Statement/Makefile,v 1.21 2006/03/15 08:51:38 lth Exp $

PORTNAME=	SQL-Statement
PORTVERSION=	1.15
CATEGORIES=	databases perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Perl5 module for SQL parsing and processing

LICENSE=	artistic gpl
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	modbuild

.include <bsd.port.mk>
