PORTNAME=	bdsmatrix
DISTVERSION=	1.3-7
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Routines for Block Diagonal Symmetric matrices
WWW=		https://cran.r-project.org/web/packages/bdsmatrix/

LICENSE=	lgpl

USES=		cran:auto-plist,compiles

.include <bsd.port.mk>
