# $FreeBSD: head/databases/php74-pdo_dblib/Makefile 512406 2019-09-20 12:21:11Z tz $

CATEGORIES=	databases

MASTERDIR=	${.CURDIR}/../../lang/php74

PKGNAMESUFFIX=	-pdo_dblib

TEST_TARGET=    test

.include "${MASTERDIR}/Makefile"
