# New ports collection makefile for:	xf86-video-s3
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11-drivers/xf86-video-s3/Makefile,v 1.2 2007/09/15 14:04:28 flz Exp $
# $MidnightBSD$
#

PORTNAME=	xf86-video-s3
PORTVERSION=	0.5.0
CATEGORIES=	x11-drivers

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X.Org s3 display driver
LICENSE=	x11

XORG_CAT=	driver
USE_XORG=	videoproto xextproto

.include <bsd.port.mk>
