PORTNAME=	text
PORTVERSION=	1.3.1
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Collection of text algorithms
WWW=		https://github.com/threedaymonk/text

LICENSE=	mit
LICENSE_FILE=	${WRKSRC}/COPYING.txt

NO_ARCH=	yes

USES=		gem

.include <bsd.port.mk>
