# $FreeBSD: head/databases/php73-interbase/Makefile 481525 2018-10-08 08:52:51Z tz $

CATEGORIES=	databases

MASTERDIR=	${.CURDIR}/../../lang/php73

PKGNAMESUFFIX=	-interbase

TEST_TARGET=    test

.include "${MASTERDIR}/Makefile"
