# $MidnightBSD$

PORTNAME=	editres
PORTVERSION=	1.0.7
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Dynamic resource editor for X Toolkit Applications

LICENSE=	mit
LICENSE_FILE=	${WRKSRC}/COPYING

XORG_CAT=	app
USE_XORG=	x11 xt xmu xaw

.include <bsd.port.mk>
