# New ports collection makefile for:	php5-imap
# Date created:			7 Jul 2004
# Whom:				Alex Dupre <ale@FreeBSD.org>
#
# $MidnightBSD$
# $FreeBSD: ports/mail/php5-imap/Makefile,v 1.1 2004/07/19 09:12:31 ale Exp $
#

CATEGORIES=	mail

MASTERDIR=	${.CURDIR}/../../lang/php5

PKGNAMESUFFIX=	-imap

.include "${MASTERDIR}/Makefile"
