COMMENT = Network management tools

SUBDIR += aircrack-ng
SUBDIR += docsis
SUBDIR += flow-tools
SUBDIR += kismet
SUBDIR += libsmi
SUBDIR += nagios
SUBDIR += nagios-plugins
SUBDIR += nagios4
SUBDIR += p5-Cflow
SUBDIR += p5-Cisco-Reconfig
SUBDIR += p5-Data-Validate-IP
SUBDIR += p5-Mon
SUBDIR += p5-Net-CIDR
SUBDIR += p5-Net-IP
SUBDIR += p5-Net-SNMP
SUBDIR += p5-NetAddr-IP
SUBDIR += p5-NSNMP
SUBDIR += p5-SNMP_Session
SUBDIR += php71-snmp
SUBDIR += php72-snmp
SUBDIR += net-snmp
SUBDIR += softflowd
SUBDIR += subcalc
SUBDIR += sysmon
SUBDIR += tcpreplay
SUBDIR += tcptrack
SUBDIR += whatmask
SUBDIR += wifimgr

.include <bsd.port.subdir.mk>
