# $MidnightBSD: mports/net-mgmt/Makefile,v 1.2 2006/12/27 02:48:19 laffer1 Exp $
#

    COMMENT = Network management tools

    SUBDIR += p5-Altoids
    SUBDIR += p5-Cflow
    SUBDIR += p5-Cisco-Reconfig
    SUBDIR += p5-Mon
    SUBDIR += p5-NSNMP
    SUBDIR += p5-SNMP_Session
    SUBDIR += net-snmp
    SUBDIR += softflowd
    SUBDIR += subcalc
    SUBDIR += sysmon
    SUBDIR += tas
    SUBDIR += tcpreplay
    SUBDIR += tcptrack
    SUBDIR += trafd
    SUBDIR += weplab
    SUBDIR += whatmask
    SUBDIR += yabm

.include <bsd.port.subdir.mk>
