# New ports collection makefile for:    font-daewoo-misc
# Date created:		28 Aug 2005
# Whom:			Pawel Worach
#
# $FreeBSD: ports/x11-fonts/font-daewoo-misc/Makefile,v 1.1 2007/05/19 20:29:14 flz Exp $
# $MidnightBSD$
#

PORTNAME=	font-daewoo-misc
PORTVERSION=	1.0.0
CATEGORIES=	x11-fonts

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X.Org miscellaneous Daewoo fonts
LICENSE=	unknown

XORG_CAT=	font

.include <bsd.port.mk>
