# $MidnightBSD: mports/x11-drivers/xf86-input-citron/Makefile,v 1.2 2009/08/21 17:44:33 laffer1 Exp $

PORTNAME=	xf86-input-citron
PORTVERSION=	2.2.2
CATEGORIES=	x11-drivers

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X.Org citron input driver
LICENSE=	x11

XORG_CAT=	driver
MAN4=		citron.4x

BROKEN=		does not compile

.include <bsd.port.mk>
