# $MidnightBSD: mports/devel/makedepend/Makefile,v 1.3 2009/04/08 19:05:53 laffer1 Exp $

PORTNAME=	makedepend
PORTVERSION=	1.0.2
CATEGORIES=	devel

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	A dependency generator for makefiles
LICENSE=	x11

XORG_CAT=	util
USE_GNOME=	pkgconfig
USE_XORG=	xproto

PLIST_FILES=	bin/makedepend

MAN1=		makedepend.1

.include <bsd.port.mk>
