# $MidnightBSD$

PORTNAME=	Set-IntSpan
PORTVERSION=	1.19
PORTREVISION=	1
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Manages sets of integers

LICENSE=	artistic gpl
LICENSE_COMB=	dual

USES=		perl5
PERL_CONFIGURE=	yes

.include <bsd.port.mk>
