# $MidnightBSD$

PORTNAME=	addresses
PORTVERSION=	0.4.8
PORTREVISION=	2
CATEGORIES=	mail gnustep
MASTER_SITES=	SAVANNAH/gap
DISTNAME=	Addresses-${PORTVERSION}

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	A versatile addressbook for GNUstep

LICENSE=	lgpl2.1

USES=		gnustep
USE_GNUSTEP=	back build
USE_LDCONFIG=	${GNUSTEP_LOCAL_LIBRARIES}

.include <bsd.port.mk>
