# $MidnightBSD$

PORTNAME=	libunistring
PORTVERSION=	0.9.4
CATEGORIES=	devel
MASTER_SITES=	GNU

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Unicode string library

LICENSE=	gpl3 lgpl3
LICENSE_COMB=	dual

USES=		charsetfix gmake iconv libtool
USE_LDCONFIG=	yes
GNU_CONFIGURE=	yes
INSTALL_TARGET=	install-strip
INFO=		${PORTNAME}

OPTIONS_DEFINE=	DOCS

.include <bsd.port.mk>
