PORTNAME=	Regexp-Common
PORTVERSION=	2017060201
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Regexp::Common - Provide commonly requested regular expressions
WWW=		https://metacpan.org/release/Regexp-Common

LICENSE=	artistic artistic2 bsd3 mit
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure
NO_ARCH=	yes

.include <bsd.port.mk>
