# New ports collection makefile for:	mkfontdir
# Date Created:				28 Aug 2005
# Whom:					Pawel Worach
#
# $FreeBSD: ports/x11-fonts/mkfontdir/Makefile,v 1.2 2007/07/02 17:27:23 lesi Exp $
# $MidnightBSD$
#

PORTNAME=	mkfontdir
PORTVERSION=	1.0.3
CATEGORIES=	x11-fonts

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Create an index of X font files in a directory
LICENSE=	unknown

XORG_CAT=	app

PLIST_FILES=	bin/mkfontdir
MAN1=		mkfontdir.1

.include <bsd.port.mk>
