# $MidnightBSD: mports/sysutils/Makefile,v 1.12 2006/11/01 03:02:12 laffer1 Exp $
#

    COMMENT = System utilities

    SUBDIR += cdrtools
    SUBDIR += coreutils
    SUBDIR += fusefs-kmod 
    SUBDIR += fusefs-libs 
    SUBDIR += fusefs-sshfs
    SUBDIR += libcdio
    SUBDIR += libchk
    SUBDIR += memtest
    SUBDIR += memtest86
    SUBDIR += portsearch
    SUBDIR += portupgrade
    SUBDIR += pwgen
    SUBDIR += screen
    SUBDIR += timemon
    SUBDIR += yawho

.include <bsd.port.subdir.mk>
