# $MidnightBSD: mports/sysutils/Makefile,v 1.4 2006/09/28 02:07:25 archite Exp $
# $FreeBSD: ports/sysutils/Makefile,v 1.836 2006/09/12 19:58:25 miwi Exp $
#

    COMMENT = System utilities

    SUBDIR += cdrtools
    SUBDIR += coreutils
    SUBDIR += fusefs-kmod 
    SUBDIR += fusefs-libs 
    SUBDIR += fusefs-sshfs
    SUBDIR += screen
    SUBDIR += timemon

.include <bsd.port.subdir.mk>
