PORTNAME=	simple_po_parser
PORTVERSION=	1.1.6
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Simple PO file to ruby hash parser
WWW=		http://github.com/experteer/simple_po_parser

LICENSE=	mit

USES=		gem

NO_ARCH=	yes

.include <bsd.port.mk>
