PORTNAME=	xfsinfo
PORTVERSION=	1.0.6
CATEGORIES=	x11-fonts

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X font server information utility

LICENSE=	mit

USES=		xorg xorg-cat:app
USE_XORG=	x11 libfs

PLIST_FILES=	bin/xfsinfo man/man1/xfsinfo.1.gz

.include <bsd.port.mk>
