# $MidnightBSD: mports/x11-fonts/xfsinfo/Makefile,v 1.3 2011/05/10 13:51:07 laffer1 Exp $

PORTNAME=	xfsinfo
PORTVERSION=	1.0.3
CATEGORIES=	x11-fonts

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X font server information utility
LICENSE=	mit

XORG_CAT=	app
USE_XORG=	x11 libfs

PLIST_FILES=	bin/xfsinfo

MAN1=		xfsinfo.1

.include <bsd.port.mk>
