# $MidnightBSD: mports/x11-drivers/xf86-input-palmax/Makefile,v 1.2 2009/04/07 16:00:12 crash Exp $

PORTNAME=	xf86-input-palmax
PORTVERSION=	1.2.0
PORTREVISION=	1
CATEGORIES=	x11-drivers

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X.Org palmax input driver
LICENSE=	unknown

IGNORE=		Unmaintained upstream.

XORG_CAT=	driver
MAN4=		palmax.4x

.include <bsd.port.mk>
