# $MidnightBSD: mports/misc/p5-Geography-Countries/Makefile,v 1.2 2009/04/16 04:32:55 laffer1 Exp $

PORTNAME=	Geography-Countries
PORTVERSION=	2009041301
CATEGORIES=	misc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Handle ISO-3166 country codes
LICENSE=	perl

PERL_CONFIGURE=	yes
CONFIGURE_ARGS+=	INSTALLDIRS='site'

MAN3=		Geography::Countries.3

.include <bsd.port.mk>
