PORTNAME=	Geography-Countries
PORTVERSION=	2009041301
CATEGORIES=	misc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Handle ISO-3166 country codes

LICENSE=	artistic gpl
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure
CONFIGURE_ARGS+=	INSTALLDIRS='site'

.include <bsd.port.mk>
