# $MidnightBSD$

PORTNAME=	liboldX
PORTVERSION=	1.0.1
PORTREVISION=	5
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Old X library

LICENSE=	mit

XORG_CAT=	lib
USE_XORG=	x11

.include <bsd.port.mk>
