# $FreeBSD: ports/x11/libXfixes/Makefile,v 1.14 2007/05/19 20:26:51 flz Exp $
# $MidnightBSD: mports/x11/libXfixes/Makefile,v 1.2 2011/05/03 00:16:53 laffer1 Exp $

PORTNAME=	libXfixes
PORTVERSION=	5.0
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X Fixes extension library
LICENSE=	x11

XORG_CAT=	lib
USE_XORG=	x11 fixesproto:both xproto:both xextproto

MAN3=		Xfixes.3

.include <bsd.port.mk>
