# $MidnightBSD$

PORTNAME=	fileutils
PORTVERSION=	0.6
CATEGORIES=	devel python
MASTER_SITES=	http://ftp.livinglogic.de/fileutils/
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	FileUtils-${PORTVERSION}

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	File I/O related functions and classes
LICENSE=	mit

USE_BZIP2=		yes
USE_PYTHON=		yes
USE_PYDISTUTILS=	yes
PYDISTUTILS_AUTOPLIST=	yes

.include <bsd.port.mk>
