# $MidnightBSD: mports/news/Makefile,v 1.3 2008/05/31 02:56:27 laffer1 Exp $
#

    COMMENT = Network news

    SUBDIR += PicMonger
    SUBDIR += knews
    SUBDIR += newsfetch
    SUBDIR += slrn
    SUBDIR += tin

.include <bsd.port.subdir.mk>
