# $FreeBSD: head/security/php74-sodium/Makefile 512406 2019-09-20 12:21:11Z tz $

CATEGORIES=	security

MASTERDIR=	${.CURDIR}/../../lang/php74

PKGNAMESUFFIX=	-sodium

TEST_TARGET=    test

.include "${MASTERDIR}/Makefile"
