PORTNAME=	PatchReader
PORTVERSION=	0.9.6
CATEGORIES=	devel perl5
MASTER_SITES=${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	../by-authors/id/T/TM/TMANNERM/
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Perl module with utilities to read and manipulate patches and CVS
WWW=		https://metacpan.org/release/PatchReader

LICENSE=	artistic gpl+
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.post.mk>
