# $MidnightBSD: mports/x11/x11perf/Makefile,v 1.4 2011/09/20 23:35:38 laffer1 Exp $

PORTNAME=	x11perf
PORTVERSION=	1.5.4
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X11 server performance test program
LICENSE=	mit

XORG_CAT=	app
USE_XORG=	x11 xmuu xrender xft xext

MAN1=		Xmark.1 \
		x11perf.1 \
		x11perfcomp.1

.include <bsd.port.mk>
