# $MidnightBSD$
# $FreeBSD: ports/textproc/p5-Text-Tabs+Wrap/Makefile,v 1.5 2007/01/05 01:45:36 clsung Exp $

PORTNAME=	Text-Tabs+Wrap
PORTVERSION=	2009.0305
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Line wrapping to form simple paragraphs

LICENSE=	perl

PERL_CONFIGURE=	YES

.include <bsd.port.mk>
