# $MidnightBSD: mports/devel/p5-Params-Validate/Makefile,v 1.3 2011/05/12 13:20:42 laffer1 Exp $

PORTNAME=	Params-Validate
PORTVERSION=	0.95
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ctriv@MidnightBSD.org
COMMENT=	Validate method/function parameters
LICENSE=	perl

BUILD_DEPENDS=	p5-ExtUtils-CBuilder>=0.2703:${PORTSDIR}/devel/p5-ExtUtils-CBuilder

PERL_MODBUILD=	yes

MAN3=		Attribute::Params::Validate.3 Params::ValidateXS.3 \
		Params::ValidatePP.3 Params::Validate.3

.include <bsd.port.mk>

