# $FreeBSD: head/converters/php72-mbstring/Makefile 475229 2018-07-24 08:44:32Z tz $

CATEGORIES=	converters

MASTERDIR=	${.CURDIR}/../../lang/php72

PKGNAMESUFFIX=	-mbstring

TEST_TARGET=    test

.include "${MASTERDIR}/Makefile"
