# $MidnightBSD$

PORTNAME=	Encode-Locale
PORTVERSION=	1.05
CATEGORIES=	converters perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Determine the locale encoding

LICENSE=	artistic gpl
LICENSE_COMB=	dual

USES=		perl5
PERL_CONFIGURE=	yes

.include <bsd.port.mk>
