# $MidnightBSD: mports/graphics/Makefile,v 1.7 2006/09/20 16:14:09 laffer1 Exp $
# $FreeBSD: ports/graphics/Makefile,v 1.983 2006/09/12 18:28:05 dinoex Exp $
#

    COMMENT = Graphics tools and libraries

    SUBDIR += cairo
    SUBDIR += dri
    SUBDIR += glitz
    SUBDIR += jpeg
    SUBDIR += gle
    SUBDIR += libart_lgpl
    SUBDIR += libdrm
    SUBDIR += libglut
    SUBDIR += libungif
    SUBDIR += png
    SUBDIR += tiff
    SUBDIR += wmicons

.include <bsd.port.subdir.mk>
