# $MidnightBSD: mports/graphics/Makefile,v 1.9 2006/09/23 22:21:44 laffer1 Exp $
# $FreeBSD: ports/graphics/Makefile,v 1.983 2006/09/12 18:28:05 dinoex Exp $
#

    COMMENT = Graphics tools and libraries

    SUBDIR += cairo
    SUBDIR += dri
    SUBDIR += glitz
    SUBDIR += jpeg
    SUBDIR += gle
    SUBDIR += libart_lgpl
    SUBDIR += libdrm
    SUBDIR += libglut
    SUBDIR += libungif
    SUBDIR += linux-ac3d
    SUBDIR += linux-adobesvg
    SUBDIR += linux-gdk-pixbuf
    SUBDIR += linux-imlib
    SUBDIR += linux-jpeg
    SUBDIR += linux-libmng
    SUBDIR += linux-panorama-tools
    SUBDIR += linux-png
    SUBDIR += linux-png10
    SUBDIR += linux-sdl_image
    SUBDIR += linux-tiff
    SUBDIR += linux-ungif
    SUBDIR += linux_dri
    SUBDIR += png
    SUBDIR += tiff
    SUBDIR += wmicons

.include <bsd.port.subdir.mk>
