# $MidnightBSD: mports/emulators/Makefile,v 1.20 2007/05/05 05:39:27 laffer1 Exp $
#

    COMMENT = Emulators for other operating systems

    SUBDIR += adamem
    SUBDIR += aftp
    SUBDIR += basiliskII
    SUBDIR += bochs
    SUBDIR += dgen-sdl
    SUBDIR += dosbox
    SUBDIR += extract-xiso
    SUBDIR += kqemu-kmod
    SUBDIR += linux_base-fc4
    SUBDIR += linux_base-gentoo-stage1
    SUBDIR += linux_base-gentoo-stage2
    SUBDIR += linux_base-gentoo-stage3
    SUBDIR += linux_dist-gentoo-stage1
    SUBDIR += linux_dist-gentoo-stage2
    SUBDIR += linux_dist-gentoo-stage3
    SUBDIR += mtools
    SUBDIR += pearpc
    SUBDIR += qemu
    SUBDIR += rtc
    SUBDIR += tiemu2
    SUBDIR += vMac
    SUBDIR += vxtools
    SUBDIR += wine
    SUBDIR += xhomer
    SUBDIR += yabause
    SUBDIR += yape

.include <bsd.port.subdir.mk>
