# New ports collection makefile for:   xproto
# Date Created:			29 Oct, 2003
# Whom:				Eric Anholt <anholt@FreeBSD.org>
#
# $FreeBSD: ports/x11/xproto/Makefile,v 1.13 2007/05/19 20:28:10 flz Exp $
# $MidnightBSD$
#

PORTNAME=	xproto
PORTVERSION=	7.0.11
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X11 protocol headers
LICENSE=	x11

XORG_CAT=	proto

.include <bsd.port.mk>
