# Created by: Martin Matuska <mm@FreeBSD.org>
# $FreeBSD: head/www/php70-opcache/Makefile 408932 2016-02-15 14:34:26Z miwi $

CATEGORIES=	www

MASTERDIR=	${.CURDIR}/../../lang/php70

PKGNAMESUFFIX=	-opcache

USE_ZENDEXT=	yes

.include "${MASTERDIR}/Makefile"
