PORTNAME=	sdbm
PORTVERSION=	1.0.0
CATEGORIES=	databases rubygems
MASTER_SITES=	RG

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Simple file-based key-value store with String keys and values
WWW=		https://github.com/ruby/sdbm

LICENSE=	bsd2

USES=		gem

.include <bsd.port.mk>
