# $FreeBSD: head/graphics/gstreamer1-plugins-gdkpixbuf/Makefile 351947 2014-04-23 14:22:47Z tijl $

PORTREVISION=	0
CATEGORIES=	graphics
PKGNAMESUFFIX=	1-plugins-gdkpixbuf

COMMENT=	Gstreamer image decoder plugin

GST_PLUGIN=	gdk_pixbuf
DIST=		good

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
