# $MidnightBSD: mports/devel/p5-Class-Accessor/Makefile,v 1.3 2010/12/02 01:14:02 laffer1 Exp $

PORTNAME=	Class-Accessor
PORTVERSION=	0.34
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Automated accessor generation
LICENSE=	perl

PERL_CONFIGURE=	yes

MAN3=		Class::Accessor.3 Class::Accessor::Fast.3 \
		Class::Accessor::Faster.3

.include <bsd.port.mk>

