PORTNAME=	storable
PORTVERSION=	0.10.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Marshal Ruby classes into and out of multiple formats
WWW=		https://github.com/delano/storable

LICENSE=	mit

USES=		gem

NO_ARCH=	yes

.include <bsd.port.mk>
