PORTNAME=	Lingua-ZH-Keywords
PORTVERSION=	0.04
CATEGORIES=	chinese perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Chinese Keywords Extraction via Lingua::ZH::TaBE
WWW=		https://metacpan.org/release/Lingua-ZH-Keywords

LICENSE=	NONE

BUILD_DEPENDS=	${RUN_DEPENDS}
RUN_DEPENDS=	p5-Lingua-ZH-TaBE>=0:chinese/p5-Lingua-ZH-TaBE

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
