# $MidnightBSD$

PORTNAME=	libasyncns
PORTVERSION=	0.7
CATEGORIES=	dns devel linux
PKGNAMEPREFIX=	linux-f10-
DISTNAME=	${PORTNAME}-${PORTVERSION}-${RPMVERSION}

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	C library for executing DNS queries asynchronously (Linux Fedora 10)
LICENSE=	lgpl

USE_LINUX=	f10
USE_LINUX_RPM=	yes
RPMVERSION=	1.fc10
USE_LDCONFIG=	yes
AUTOMATIC_PLIST=yes

.include <bsd.port.mk>
