# $MidnightBSD: mports/shells/Makefile,v 1.6 2010/01/21 01:42:36 laffer1 Exp $
#

    COMMENT = Shells

    SUBDIR += 44bsd-csh
    SUBDIR += bash
    SUBDIR += bash-completion
    SUBDIR += es
    SUBDIR += esh
    SUBDIR += fd
    SUBDIR += gscommander
    SUBDIR += ibsh
    SUBDIR += ksh93
    SUBDIR += mksh
    SUBDIR += nologinmsg
    SUBDIR += osh
    SUBDIR += p5-Term-ShellUI
    SUBDIR += pash
    SUBDIR += pdksh
    SUBDIR += psh
    SUBDIR += rc
    SUBDIR += rssh
    SUBDIR += sash
    SUBDIR += scponly
    SUBDIR += tcshrc
    SUBDIR += v7sh
    SUBDIR += wapsh
    SUBDIR += zsh

.include <bsd.port.subdir.mk>
