PORTNAME=	ast
PORTVERSION=	2.4.3
CATEGORIES=	devel ruby
MASTER_SITES=	RG

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Library for working with Abstract Syntax Trees
WWW=		https://github.com/whitequark/ast

LICENSE=	mit
LICENSE_FILE=	${WRKSRC}/LICENSE.MIT

USES=		gem

NO_ARCH=	yes

.include <bsd.port.mk>
