PORTNAME=	font-bh-lucidatypewriter-75dpi
PORTVERSION=	1.0.4
CATEGORIES=	x11-fonts
DISTFILES=      ${PORTNAME}-${PORTVERSION}.tar.xz

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X.Org Bigelow Holmes Lucida TypeWriter 75dpi font

LICENSE=	unknown

USES=		xorg xorg-cat:font tar:xz
USE_XORG=	fontutil

.include <bsd.port.mk>
