# New ports collection makefile for:	gstreamer-plugins-mpeg2dec
# Date created:			Nov 23 2007
# Whom:				Lucas Holt <luke@midnightbsd.org>
#
# $MidnightBSD$
#

CATEGORIES=	multimedia

COMMENT=	Gstreamer mpeg decode plugin

GST_PLUGIN=	mpeg2dec

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
