PORTNAME=	ptyprocess
PORTVERSION=	0.5.1
CATEGORIES=	sysutils python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Run a subprocess in a pseudo terminal

LICENSE=	isc

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
