# New ports collection makefile for:	tk84-thread
# Date created:				09 March 2007
# Whom:					Martin Matuska <martin@matuska.org>
#
# $MidnightBSD: mports/x11-toolkits/tk84-thread/Makefile,v 1.1 2007/04/04 19:22:36 laffer1 Exp $
# $FreeBSD: ports/x11-toolkits/tk84-thread/Makefile,v 1.2 2007/03/20 10:53:02 miwi Exp $
#

PKGNAMESUFFIX=	-threads
BUILDING_TK_THREADS=	yes

MASTERDIR=	${.CURDIR}/../tk84

.include "${MASTERDIR}/Makefile"
