# New ports collection makefile for:	google-sitemapgen
# Date created:	   09 June 2005
# Whom:		   Sergey Skvortsov <skv@protey.ru>
#
# $MidnightBSD: mports/www/google-sitemapgen/Makefile,v 1.1 2007/05/08 21:24:16 laffer1 Exp $
# $FreeBSD: ports/www/google-sitemapgen/Makefile,v 1.3 2006/02/17 09:01:57 skv Exp $
#

PORTNAME=	google-sitemapgen
PORTVERSION=	1.4
CATEGORIES=	www devel
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE}
MASTER_SITE_SUBDIR=	goog-sitemapgen
DISTNAME=	sitemap_gen-${PORTVERSION}

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Script to analyze web server and generate Google Sitemap files
LICENSE=	bsd3

USE_PYTHON=	YES
USE_PYDISTUTILS=YES

.include <bsd.port.mk>
