# $MidnightBSD$

PORTNAME=	google-sitemapgen
PORTVERSION=	1.5
PORTREVISION=	1
CATEGORIES=	www devel
MASTER_SITES=	https://fossies.org/linux/www/old/
DISTNAME=	sitemap_gen_${PORTVERSION}

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Script to analyze web server and generate Google Sitemap files

LICENSE=	bsd3

NO_WRKSUBDIR=

USES=		python:2.7
USE_PYTHON=	autoplist distutils
PYDISTUTILS_PKGNAME=	sitemap_gen

.include <bsd.port.mk>
