# $MidnightBSD$

PORTNAME=	libasyncns
PORTVERSION=	0.8
CATEGORIES=	dns devel linux

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Library for executing DNS queries (Linux CentOS ${LINUX_DIST_VER})

LICENSE=	lgpl2.1

CONFLICTS=	linux-c6-${PORTNAME}-[0-9]*

RPMVERSION=	7.el7
USES=		linux:c7
USE_LDCONFIG=	yes
USE_LINUX_RPM=	yes

OPTIONS_DEFINE=	DOCS

.include <bsd.port.mk>
