# Created by: Yuri Victorovich <yuri@rawbw.com>

PORTNAME=	pyphen
PORTVERSION=	0.10.0
CATEGORIES=	textproc python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	Pyphen-${PORTVERSION}

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Module to hyphenate text based on Hunspell dictionaries

LICENSE=	gpl2 lgpl2.1 mpl
LICENSE_COMB=	multi

USES=		python:3.6+
USE_PYTHON=	autoplist distutils
NO_ARCH=	yes

.include <bsd.port.mk>
