# $FreeBSD: head/security/php72-filter/Makefile 475229 2018-07-24 08:44:32Z tz $

CATEGORIES=	security

MASTERDIR=	${.CURDIR}/../../lang/php72

PKGNAMESUFFIX=	-filter

TEST_TARGET=    test

.include "${MASTERDIR}/Makefile"
