# New ports collection makefile for:	kmobiletools
# Date created:		2006-12-19
# Whom:			Stefan Ehmann <shoesoft@gmx.net>
#
# $MidnightBSD: mports/comms/kmobiletools/Makefile,v 1.1 2008/08/17 22:14:13 laffer1 Exp $
# $FreeBSD: ports/comms/kmobiletools/Makefile,v 1.2 2007/05/19 20:00:55 flz Exp $
#

PORTNAME=	kmobiletools
PORTVERSION=	0.4.3.3
CATEGORIES=	comms kde
MASTER_SITES=	${MASTER_SITE_BERLIOS}
MASTER_SITE_SUBDIR=	kmobiletools

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Control mobile phones with your PC
LICENSE=	gpl2

USE_KDELIBS_VER=3

USE_BZIP2=	yes
USE_AUTOTOOLS=	libtool:22
USE_GMAKE=	yes

.include <bsd.port.mk>
