PORTNAME=	rbase
PORTVERSION=	0.1.3
CATEGORIES=	databases rubygems
MASTER_SITES=	RG

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Library to create/read/write to XBase databases (*.DBF files)
WWW=		https://rubygems.org/gems/rbase

LICENSE=	NONE

USES=		gem

NO_ARCH=	yes

.include <bsd.port.mk>
