PORTNAME=	mlbench
DISTVERSION=	2.1-6
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Machine Learning Benchmark Problems
WWW=		https://cran.r-project.org/web/packages/mlbench/

LICENSE=	gpl2

USES=		cran:auto-plist,compiles

.include <bsd.port.mk>
