# $FreeBSD: head/security/php73-filter/Makefile 481525 2018-10-08 08:52:51Z tz $

CATEGORIES=	security

MASTERDIR=	${.CURDIR}/../../lang/php73

PKGNAMESUFFIX=	-filter

TEST_TARGET=    test

.include "${MASTERDIR}/Makefile"
