PORTNAME=	dm-constraints
PORTVERSION=	1.2.0
PORTREVISION=	1
CATEGORIES=	databases rubygems
MASTER_SITES=	RG

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	DataMapper plugin constraining relationships
WWW=		https://github.com/datamapper/dm-constraints

LICENSE=	mit

BUILD_DEPENDS=	${RUN_DEPENDS}
RUN_DEPENDS=	rubygem-dm-core>=${PORTVERSION}:databases/rubygem-dm-core

NO_ARCH=	yes

USES=		gem

.include <bsd.port.mk>
