PORTNAME=	xkbevd
PORTVERSION=	1.1.4
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	XKB event daemon
WWW=		https://gitlab.freedesktop.org/xorg/app/xkbevd

LICENSE=	mit

USES=		xorg xorg-cat:app
USE_XORG=	xkbfile x11

PLIST_FILES=	bin/xkbevd share/man/man1/xkbevd.1.gz

.include <bsd.port.mk>
