PORTNAME=	xstdcmap
PORTVERSION=	1.0.5
CATEGORIES=	x11
DISTFILES=      ${PORTNAME}-${PORTVERSION}.tar.xz

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X standard colormap utility

LICENSE=	mit

USES=		xorg xorg-cat:app tar:xz
USE_XORG=	xmu x11 xt

PLIST_FILES=	bin/xstdcmap man/man1/xstdcmap.1.gz

.include <bsd.port.mk>
