PORTNAME=	ruby-rc4
PORTVERSION=	0.1.5
CATEGORIES=	security rubygems
MASTER_SITES=	RG

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Pure Ruby implementation of the RC4 algorithm
WWW=		https://github.com/caiges/Ruby-RC4

LICENSE=	mit

NO_ARCH=	yes

USES=		gem

.include <bsd.port.mk>
