# $MidnightBSD$

PORTNAME=	JSON
PORTVERSION=	2.90
CATEGORIES=	converters perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Perl extension to convert to JSON (JavaScript Object Notation)

LICENSE=	artistic gpl
LICENSE_COMB=	dual

CONFLICTS=	p5-JSON-1.* p5-JSON1-*

USE_PERL5_BUILD=	yes
USE_PERL5_RUN=	yes
PERL_CONFIGURE=	yes

.include <bsd.port.mk>
