PORTNAME=	font-adobe-100dpi
PORTVERSION=	1.0.4
CATEGORIES=	x11-fonts
DISTFILES=	font-adobe-100dpi-1.0.4.tar.xz

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X.Org Adobe 100dpi font

LICENSE=	unknown

USES=		xorg xorg-cat:font tar:xz
USE_XORG=	fontutil

.include <bsd.port.mk>
