PORTNAME=	siosocks
PORTVERSION=	0.3.0
CATEGORIES=	net python
MASTER_SITES=	PYPI
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Sans-io socks proxy client/server library/framework
WWW=		https://pypi.python.org/pypi/siosocks

LICENSE=	mit
LICENSE_FILE=	${WRKSRC}/license.txt

USES=		python
USE_PYTHON=	autoplist distutils pytest
NO_ARCH=	yes
NO_TEST=	yes

.include <bsd.port.mk>
