# $MidnightBSD$

PORTNAME=	xf86-video-i128
PORTVERSION=	1.3.6
PORTREVISION=	2
CATEGORIES=	x11-drivers

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X.Org i128 display driver

LICENSE=	mit

XORG_CAT=	driver
USE_XORG=	videoproto xextproto

.include <bsd.port.mk>
