# $MidnightBSD$

PORTNAME=	xf86miscproto
PORTVERSION=	0.9.3
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	XFree86-Misc extension headers

LICENSE=	mit
LICENSE_FILE=	${WRKSRC}/COPYING

XORG_CAT=	proto

.include <bsd.port.mk>
