# New ports collection makefile for:	xdriinfo
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11/xdriinfo/Makefile,v 1.2 2007/09/13 19:45:03 flz Exp $
# $MidnightBSD$
#

PORTNAME=	xdriinfo
PORTVERSION=	1.0.2
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Query configuration information of DRI drivers
LICENSE=	x11

USE_GL=		gl

XORG_CAT=	app
USE_XORG=	x11 glproto
MAN1=		xdriinfo.1
PLIST_FILES=	bin/xdriinfo

.include <bsd.port.mk>
