# $MidnightBSD$
# $FreeBSD: head/devel/py-pycparser/Makefile 371280 2014-10-20 16:04:12Z mva $

PORTNAME=	pycparser
PORTVERSION=	2.10
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	C parser in Python

LICENSE=	bsd3

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
