PORTNAME=	attr_required
PORTVERSION=	1.0.2
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Ruby implementations of attr_required and attr_optional
WWW=		https://github.com/nov/attr_required

LICENSE=	mit
LICENSE_FILE=	${WRKSRC}/LICENSE

NO_ARCH=	yes
USES=		gem

.include <bsd.port.mk>
