# $MidnightBSD$

PORTNAME=	libXpm
PORTVERSION=	3.5.11
PORTREVISION=	1
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X Pixmap library

LICENSE=	mit

XORG_CAT=	lib
USE_XORG=	xproto x11 xext xextproto xt

.include <bsd.port.mk>
