# $FreeBSD: ports/x11-fonts/encodings/Makefile,v 1.1 2007/05/19 20:29:09 flz Exp $
# $MidnightBSD: mports/x11-fonts/encodings/Makefile,v 1.1 2007/10/09 15:44:02 ctriv Exp $

PORTNAME=	encodings
PORTVERSION=	1.0.4
CATEGORIES=	x11-fonts

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X.Org Encoding fonts
LICENSE=	x11

XORG_CAT=	font
USE_XORG=	fontutil
FONTDIR=	encodings/large encodings

.include <bsd.port.mk>
