# New ports collection makefile for:	ciso
#
# $MidnightBSD: mports/sysutils/ciso/Makefile,v 1.1 2008/08/24 21:41:39 laffer1 Exp $
# $FreeBSD: ports/sysutils/ciso/Makefile,v 1.1 2007/12/15 21:18:18 miwi Exp $

PORTNAME=	ciso
PORTVERSION=	1.0.0
CATEGORIES=	sysutils
MASTER_SITES=	http://ciso.tenshu.fr/

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	A tool to compress ISO images to CSO format
LICENSE=	gpl2

FAKE_OPTS=	trueprefix
USE_DOS2UNIX=	yes

PLIST_FILES=	bin/ciso

.include <bsd.port.mk>
