# $MidnightBSD$

PORTNAME=	ciso
PORTVERSION=	1.0.0
PORTREVISION=	1
CATEGORIES=	sysutils
MASTER_SITES=	SF

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	A tool to compress ISO images to CSO format

LICENSE=	gpl2

FAKE_OPTS=	trueprefix
USE_DOS2UNIX=	yes

PLIST_FILES=	bin/ciso

.include <bsd.port.mk>
