# $MidnightBSD: mports/x11/xauth/Makefile,v 1.2 2009/05/04 02:19:01 laffer1 Exp $

PORTNAME=	xauth
PORTVERSION=	1.0.5
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X authority file utility
LICENSE=	x11

XORG_CAT=	app
USE_XORG=	x11 xau xext xmuu

PLIST_FILES=	bin/xauth

MAN1=		xauth.1

.include <bsd.port.mk>
