# $MidnightBSD$

PORTNAME=	xwininfo
PORTVERSION=	1.1.4
PORTREVISION=	1
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Window information utility for X

LICENSE=	mit

XORG_CAT=	app
USES=		iconv
USE_XORG=	x11 xcb xorgproto xorg-macros

PLIST_FILES=	bin/xwininfo man/man1/xwininfo.1.gz

.include <bsd.port.mk>
