# New ports collection makefile for:	xwininfo
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11/xwininfo/Makefile,v 1.2 2007/09/13 19:45:07 flz Exp $
# $MidnightBSD$
#

PORTNAME=	xwininfo
PORTVERSION=	1.0.3
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Window information utility for X
LICENSE=	x11

XORG_CAT=	app
USE_XORG=	xmuu xext x11

PLIST_FILES=	bin/xwininfo

MAN1=		xwininfo.1

.include <bsd.port.mk>
