# $MidnightBSD: mports/games/Makefile,v 1.7 2007/01/19 18:07:47 wintellect Exp $
#

    COMMENT = Games

    SUBDIR += bass
    SUBDIR += battalion
    SUBDIR += fotaq
    SUBDIR += goonies
    SUBDIR += gtypist
    SUBDIR += linux-enemyterritory
    SUBDIR += linux-enemyterritory-etpro
    SUBDIR += linux-enemyterritory-etpub
    SUBDIR += linux-enemyterritory-fortress
    SUBDIR += linux-enemyterritory-jaymod
    SUBDIR += linux-enemyterritory-omni-bot
    SUBDIR += linux-enemyterritory-shrub
    SUBDIR += linux-enemyterritory-tce
    SUBDIR += scummvm
    SUBDIR += tuxracer
    SUBDIR += wesnoth

.include <bsd.port.subdir.mk>
