# $MidnightBSD: mports/devel/p5-IO-Multiplex/Makefile,v 1.2 2008/10/16 21:38:54 laffer1 Exp $

PORTNAME=	IO-Multiplex
PORTVERSION=	1.13
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	IO::Multiplex - Manage IO on many file handles
LICENSE=	perl

PERL_CONFIGURE=	yes

MAN3=		IO::Multiplex.3

.include <bsd.port.mk>
