# $MidnightBSD$

PORTNAME=	libXxf86misc
PORTVERSION=	1.0.4
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X XF86-Misc Extension

LICENSE=	mit

XORG_CAT=	lib
USE_XORG=	xproto x11 xextproto xext xf86miscproto:both

.include <bsd.port.mk>
