PORTNAME=	Log-Any
PORTVERSION=	1.707
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:PREACTION
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Perl extension to bring loggers and listeners together

LICENSE=	artistic gpl
LICENSE_COMB=	dual

CONFLICTS_INSTALL=	p5-Log-Any-Adapter-Syslog

USES=		perl5
USE_PERL5=	configure
NO_ARCH=	YES

.include <bsd.port.mk>
