# $FreeBSD: ports/x11/oclock/Makefile,v 1.1 2007/05/19 20:27:08 flz Exp $
# $MidnightBSD: mports/x11-clocks/oclock/Makefile,v 1.1 2011/05/07 00:45:25 laffer1 Exp $

PORTNAME=	oclock
PORTVERSION=	1.0.1
CATEGORIES=	x11-clocks

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Round clock application for X
LICENSE=	x11

XORG_CAT=	app
USE_XORG=	x11 xmu xext xt

MAN1=		oclock.1

.include <bsd.port.mk>
