PORTNAME=	Net_IPv6
DISTVERSION=	1.3.0.b4
PORTREVISION=	2
CATEGORIES=	net pear
DISTNAME=	${PORTNAME}-1.3.0b4

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Check and validate IPv6 addresses
WWW=		https://pear.php.net/package/Net_IPv6

LICENSE=	bsd2

USES=		pear

PORTSCOUT=	skipv:1.2.2b,1.2.2b2

.include <bsd.port.mk>
