# $MidnightBSD: mports/x11-toolkits/libXmu/Makefile,v 1.3 2011/05/15 16:57:17 laffer1 Exp $

PORTNAME=	libXmu
PORTVERSION=	1.1.0
CATEGORIES=	x11-toolkits

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X Miscellaneous Utilities libraries
LICENSE=	mit

XORG_CAT=	lib
USE_XORG=	xproto:both x11 xt xext

.include <bsd.port.mk>
