PORTNAME=	labeling
PORTVERSION=	0.4.3
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Provides a range of axis labeling algorithms
WWW=		https://cran.r-project.org/web/packages/labeling/

LICENSE=	mit

USES=		cran:auto-plist

.include <bsd.port.mk>
