# Created by: Pawel Worach

PORTNAME=	font-jis-misc
PORTVERSION=	1.0.3
PORTREVISION=	4
CATEGORIES=	x11-fonts

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X.Org miscellaneous JIS fonts

LICENSE=	unknown

USES=		xorg-cat:font

.include <bsd.port.mk>
