# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/archivers/php70-bz2/Makefile 408932 2016-02-15 14:34:26Z miwi $
# $MidnightBSD$

CATEGORIES=	archivers

MASTERDIR=	${.CURDIR}/../../lang/php70

PKGNAMESUFFIX=	-bz2

.include "${MASTERDIR}/Makefile"
