--- pyproject.toml.orig	2026-06-23 20:03:55 UTC
+++ pyproject.toml
@@ -1,5 +1,5 @@
 [build-system]
-requires = ["setuptools", "wheel", "twine>=6.1.0", "packaging>=24.2", "pkginfo>=1.12.0"]
+requires = ["setuptools", "wheel", "packaging>=24.2", "pkginfo>=1.12.0"]
-
+
 [project]
 name = "google-genai"
@@ -6,7 +6,7 @@ name = "google-genai"
 version = "2.9.0"
 description = "GenAI Python SDK"
 readme = "README.md"
-license = "Apache-2.0"
+license = {text = "Apache-2.0"}
 requires-python = ">=3.10"
 authors = [
     { name = "Google LLC", email = "googleapis-packages@google.com" },
