# $MidnightBSD: mports/x11-toolkits/libXaw/Makefile,v 1.2 2009/03/15 20:40:08 laffer1 Exp $

PORTNAME=	libXaw
PORTVERSION=	1.0.5
PORTREVISION=	1
CATEGORIES=	x11-toolkits

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X Athena Widgets library
LICENSE=	x11

XORG_CAT=	lib
USE_XORG=	printproto:both x11 xau xext xextproto xmu xp xpm xproto:both xt

MAN3=		Xaw.3

.include <bsd.port.mk>
