PORTNAME=	chardet
PORTVERSION=	4.0.0
PORTREVISION=	1
PORTEPOCH=	1
CATEGORIES=	textproc python
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
MASTER_SITES=	PYPI

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Universal encoding detector for Python

LICENSE=	lgpl2.1
LICENSE_FILE=	${WRKSRC}/LICENSE

NO_ARCH=	yes
NO_TEST=	yes
USES=		python
USE_PYTHON=	autoplist concurrent distutils

.include <bsd.port.mk>
