PORTNAME=	date
DISTVERSION=	1.2-42
PORTREVISION=	1
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Functions for Handling Dates
WWW=		https://CRAN.R-project.org/package=date

LICENSE=	gpl2

USES=		cran:auto-plist,compiles

.include <bsd.port.mk>
