# $MidnightBSD$

PORTNAME=	Module-Find
PORTVERSION=	0.13
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ctriv@MidnightBSD.org
COMMENT=	Lets you find and use modules in categories

LICENSE=	perl

PERL_CONFIGURE=	yes

.include <bsd.port.mk>

