# $MidnightBSD$

PORTNAME=	font-adobe-utopia-type1
PORTVERSION=	1.0.4
PORTREVISION=	1
CATEGORIES=	x11-fonts

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X.Org Adobe Utopia Type1 font
LICENSE=	unknown

XORG_CAT=	font

.include <bsd.port.mk>
