# $MidnightBSD$
# $FreeBSD: head/databases/qt5-sqldrivers-pgsql/Makefile 373100 2014-11-22 20:40:08Z crees $

PORTNAME=	pgsql

DB=		PSQL
DB_DESC=	PostgreSQL

USES+=		pgsql
USE_PGSQL=	yes

.include "${.CURDIR:H:H}/devel/qt5/Makefile.sqldrivers"
