# $MidnightBSD$

PORTNAME=	opencore-amr
PORTVERSION=	0.1.3
CATEGORIES=	audio
MASTER_SITES=	SF/${PORTNAME}/${PORTNAME}

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	OpenCORE implementation of AMR Narrowband & Wideband speech codec

LICENSE=	apache2

GNU_CONFIGURE=	yes
USES=		gmake libtool pathfix
USE_LDCONFIG=	yes
INSTALL_TARGET=	install-strip

.include <bsd.port.mk>
