PORTNAME=	xf86-video-apm
PORTVERSION=	1.3.0
PORTREVISION=	1
CATEGORIES=	x11-drivers

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X.Org apm display driver

LICENSE=	mit

USES=		xorg-cat:driver

.include <bsd.port.mk>
