# New ports collection makefile for:    fortunate
# Date created:         09 Nov 2006
# Whom:                 dirk.meyer@dinoex.sub.org
#

#

PORTNAME=	fortunate
PORTVERSION=	3.1
PORTREVISION=	4
CATEGORIES=	games gnustep
MASTER_SITES=	GNUSTEP_CH

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Graphical front-end to the command-line BSD fortune

LICENSE=	bsd4

USES=		gnustep
USE_GNUSTEP=	back build

.include <bsd.port.mk>
