# $MidnightBSD$

PORTNAME=	font-ibm-type1
PORTVERSION=	1.0.3
CATEGORIES=	x11-fonts

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X.Org IBM Type1 font
LICENSE=	unknown

XORG_CAT=	font

.include <bsd.port.mk>
