# $MidnightBSD: mports/x11/xf86miscproto/Makefile,v 1.3 2012/03/03 01:52:55 laffer1 Exp $

PORTNAME=	xf86miscproto
PORTVERSION=	0.9.3
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	XFree86-Misc extension headers
LICENSE=	mit

XORG_CAT=	proto

.include <bsd.port.mk>
