PORTNAME=	allenroids
PORTVERSION=	1.1
PORTREVISION=	1
CATEGORIES=	games
MASTER_SITES=	http://people.midnightbsd.org/~laffer1/
DISTFILES=	AllenroidsRyan.tgz
WRKSRC=		${WRKDIR}/Allenroids

MAINTAINER=	luke@MidnightBSD.org
COMMENT=	Asteroids clone by Allen Smith

LICENSE=	other

USES=		gmake
USE_SDL=	sound
USE_GL=		glut glu gl

.include <bsd.port.mk>
