# $MidnightBSD: mports/editors/Makefile,v 1.4 2006/10/04 23:52:07 laffer1 Exp $
#

    COMMENT = Editors

    SUBDIR += emacs
    SUBDIR += jedit
    SUBDIR += manedit
    SUBDIR += pico
    SUBDIR += staroffice70
    SUBDIR += textedit.app
    SUBDIR += vim
    SUBDIR += vim-lite
    SUBDIR += vim5
    SUBDIR += vim6
    SUBDIR += xemacs
    SUBDIR += xemacs-packages

.include <bsd.port.subdir.mk>
