# $MidnightBSD$

PORTNAME=	xdriinfo
PORTVERSION=	1.0.4
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Query configuration information of DRI drivers
LICENSE=	mit

USE_GL=		gl

XORG_CAT=	app
USE_XORG=	x11 glproto
MAN1=		xdriinfo.1
PLIST_FILES=	bin/xdriinfo

.include <bsd.port.mk>
