--- pyproject.toml.orig	2025-06-10 15:09:59 UTC
+++ pyproject.toml
@@ -6,6 +6,7 @@ readme = "README.md"
 requires-python = ">=3.9"
 authors = [{name = "Simon Willison"}]
-license = "Apache-2.0"
+license = { text = "Apache-2.0" }
+
 classifiers = [
     "Typing :: Typed"
 ]
@@ -14,3 +15,3 @@ dependencies = []
 [build-system]
-requires = ["setuptools"]
+requires = ["setuptools>=61"]
 build-backend = "setuptools.build_meta"
