PORTNAME=	lapacke

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Standard C language APIs for LAPACK

LICENSE=	bsd3
LICENSE_FILE=	${WRKSRC}/LICENSE

DESCR=	${.CURDIR}/pkg-descr
LAPACKE_SLAVEPORT=	yes

MASTERDIR=	${.CURDIR}/../lapack

.include "${MASTERDIR}/Makefile"
