# $MidnightBSD: mports/x11/xcmsdb/Makefile,v 1.3 2011/09/20 23:39:36 laffer1 Exp $

PORTNAME=	xcmsdb
PORTVERSION=	1.0.4
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Device Color Characterization utility for X
LICENSE=	mit

XORG_CAT=	app
USE_XORG=	x11

PLIST_FILES=	bin/xcmsdb

MAN1=		xcmsdb.1

.include <bsd.port.mk>
