# $MidnightBSD$

PORTNAME=	makedepend
PORTVERSION=	1.0.5
PORTREVISION=	3
CATEGORIES=	devel

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Dependency generator for makefiles

LICENSE=	mit

XORG_CAT=	util
USES=		pkgconfig
USE_XORG=	xorgproto

PLIST_FILES=	bin/makedepend man/man1/makedepend.1.gz

.include <bsd.port.mk>
