# $FreeBSD: ports/x11/scripts/Makefile,v 1.1 2007/05/19 20:27:17 flz Exp $
# $MidnightBSD: mports/x11/scripts/Makefile,v 1.1 2007/10/04 05:45:04 ctriv Exp $

PORTNAME=	scripts
PORTVERSION=	1.0.1
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Various X related scripts
LICENSE=	unknown

XORG_CAT=	app
USE_XORG=	x11

MAN1=		xon.1

.include <bsd.port.mk>
