# $MidnightBSD: mports/x11-clocks/Makefile,v 1.3 2007/01/20 17:30:20 laffer1 Exp $
#

    COMMENT = X11 clocks

    SUBDIR += asclock
    SUBDIR += kdetoys3
    SUBDIR += wmbinclock
    SUBDIR += wmcalclock

.include <bsd.port.subdir.mk>
