# New ports collection makefile for:	furl
# Date created:				3 January 2007
# Whom:					Phil Pereira <phil@bsdnexus.com>
#
# $MidnightBSD: mports/www/furl/Makefile,v 1.4 2010/04/28 00:24:29 laffer1 Exp $
#

PORTNAME=	furl
PORTVERSION=	2.1
CATEGORIES=	www
MASTER_SITES=	http://www.gumbynet.org.uk/software/

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Utility to display the HTTP headers returned by web-servers
LICENSE=	gpl2

GNU_CONFIGURE=	yes
CONFIGURE_TARGET=       ${MACHINE_ARCH}-portbld-midnightbsd${OSREL}

MAKE_JOBS_SAFE=	yes

.include <bsd.port.mk>
