PORTNAME=	cscope
DISTVERSION=	15.9
CATEGORIES=	devel
MASTER_SITES=	SF/${PORTNAME}/${PORTNAME}/v${PORTVERSION}

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Interactive C program browser

LICENSE=	bsd3

USES=		cpe ncurses

GNU_CONFIGURE=	yes

.include <bsd.port.mk>
