# New ports collection makefile for:	makepatch
# Date created:				May 20 2008
# Whom:					Lucas Holt <luke@midnightbsd.org>
#
# $MidnightBSD$
#

PORTNAME=	makepatch
PORTVERSION=	2.03
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	../../authors/id/JV

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Perl scripts to assist in the generation and application of patches
LICENSE=	perl

PERL_CONFIGURE=	yes

MAN1=		makepatch.1 applypatch.1

.include <bsd.port.mk>
