# New ports collection makefile for:	JSON-XS
# Date created:		25 Mar 2007
# Whom:			Cheng-Lung Sung <clsung@FreeBSD.org>
#
# $FreeBSD: ports/converters/p5-JSON-XS/Makefile,v 1.15 2007/10/17 03:46:25 clsung Exp $
# $MidnightBSD: mports/converters/p5-JSON-XS/Makefile,v 1.2 2008/03/14 00:34:39 laffer1 Exp $
#

PORTNAME=	JSON-XS
PORTVERSION=	2.232
CATEGORIES=	converters perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	../../authors/id/M/ML/MLEHMANN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	JSON serialising/deserialising, done correctly and fast
LICENSE=	perl

PERL_CONFIGURE=	yes
MAN3=		JSON::XS.3 JSON::XS::Boolean.3
MAN1=		json_xs.1

.include <bsd.port.mk>
