# $FreeBSD: head/math/php72-gmp/Makefile 475229 2018-07-24 08:44:32Z tz $

CATEGORIES=	math

MASTERDIR=	${.CURDIR}/../../lang/php72

PKGNAMESUFFIX=	-gmp

TEST_TARGET=    test

.include "${MASTERDIR}/Makefile"
