PORTNAME=	temple
PORTVERSION=	0.10.4
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Template compilation framework in Ruby
WWW=		https://github.com/judofyr/temple

LICENSE=	mit
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		gem

NO_ARCH=	yes

.include <bsd.port.mk>
