# $MidnightBSD$

PORTNAME=	xf86-input-mutouch
PORTVERSION=	1.2.1
PORTREVISION=	3
CATEGORIES=	x11-drivers

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X.Org mutouch input driver
LICENSE=	mit

XORG_CAT=	driver
MAN4=		mutouch.4x

.include <bsd.port.mk>
