PORTNAME=	yaml
DISTVERSION=	2.3.10
CATEGORIES=	textproc
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Methods to convert R data to YAML and back
WWW=		https://cran.r-project.org/web/packages/yaml/

LICENSE=	bsd3

TEST_DEPENDS=	R-cran-RUnit>0:devel/R-cran-RUnit

USES=		cran:auto-plist,compiles

.include <bsd.port.mk>
