# Created by: Mike Muir <mmuir@es.co.nz>
# $FreeBSD: head/sysutils/consolehm/Makefile 393892 2015-08-10 19:28:57Z amdmi3 $
# $MidnightBSD$

PORTNAME=	consolehm
PORTVERSION=	1.31
PORTREVISION=	1
CATEGORIES=	sysutils
MASTER_SITES=	FREEBSD_LOCAL/fenner

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Console based hardware monitor for FreeBSD

LICENSE=	bsd2

USES=		uidfix
GNU_CONFIGURE=	yes
WRKSRC=		${WRKDIR}/consolehm/consolehm

PLIST_FILES=	bin/chm man/man8/chm.8.gz

.include <bsd.port.mk>
