PORTNAME=	TimeDate
PORTVERSION=	2.33
PORTEPOCH=	1
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN/Date
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Perl5 module containing a better/faster date parser for absolute dates
WWW=		https://metacpan.org/release/TimeDate

LICENSE=	artistic gpl+
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure
NO_ARCH=	yes
NO_TEST=	yes

.include <bsd.port.mk>
