PORTNAME=	gnome-video-effects
PORTVERSION=	0.5.0
CATEGORIES=	graphics
MASTER_SITES=	GNOME

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Collection of Gstreamer effects
WWW=		https://wiki.gnome.org/Projects/GnomeVideoEffects

LICENSE=	gpl2
LICENSE_FILE=	${WRKSRC}/COPYING

USES=		gettext gstreamer meson tar:xz
USE_GSTREAMER=	good bad
NO_ARCH=	yes

.include <bsd.port.mk>
