# $MidnightBSD$

PORTNAME=	xrdb
PORTVERSION=	1.1.1
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X server resource database utility

LICENSE=	mit

XORG_CAT=	app
USE_XORG=	xmuu x11

PLIST_FILES=	bin/xrdb man/man1/xrdb.1.gz

.include <bsd.port.mk>
