# $MidnightBSD: mports/emulators/Makefile,v 1.7 2007/03/09 16:22:31 laffer1 Exp $
#

    COMMENT = Emulators for other operating systems

    SUBDIR += basiliskII
    SUBDIR += bochs
    SUBDIR += dosbox
    SUBDIR += linux_base-fc4
    SUBDIR += mtools
    SUBDIR += pearpc
    SUBDIR += qemu
    SUBDIR += wine

.include <bsd.port.subdir.mk>
