# $MidnightBSD: mports/emulators/Makefile,v 1.32 2013/07/04 16:13:46 laffer1 Exp $

COMMENT = Emulators for other operating systems

SUBDIR += adamem
SUBDIR += aftp
SUBDIR += basiliskII
SUBDIR += bochs
SUBDIR += dgen-sdl
SUBDIR += dosbox
SUBDIR += extract-xiso
SUBDIR += ia64sim
SUBDIR += kqemu-kmod
SUBDIR += kqemu-kmod-devel
SUBDIR += linux_base-f10
SUBDIR += mtools
SUBDIR += pearpc
SUBDIR += qemu
SUBDIR += rtc
SUBDIR += vMac
SUBDIR += virtio-kmod
SUBDIR += vxtools
SUBDIR += wine
SUBDIR += xhomer
SUBDIR += yabause
SUBDIR += yape

.include <bsd.port.subdir.mk>
