# $MidnightBSD: mports/emulators/Makefile,v 1.9 2007/03/09 18:34:51 laffer1 Exp $
#

    COMMENT = Emulators for other operating systems

    SUBDIR += basiliskII
    SUBDIR += bochs
    SUBDIR += dosbox
    SUBDIR += kqemu-kmod
    SUBDIR += linux_base-fc4
    SUBDIR += mtools
    SUBDIR += pearpc
    SUBDIR += qemu
    SUBDIR += vMac
    SUBDIR += wine

.include <bsd.port.subdir.mk>
