# $MidnightBSD: mports/x11-fm/Makefile,v 1.6 2010/01/21 01:28:24 laffer1 Exp $
#

    COMMENT = X11 file managers

SUBDIR += FSViewer
SUBDIR += etoile-fontmanager
SUBDIR += gentoo
SUBDIR += nautilus
SUBDIR += thunar
SUBDIR += workplace

.include <bsd.port.subdir.mk>
