# $MidnightBSD: mports/comms/Makefile,v 1.26 2013/03/09 20:27:42 laffer1 Exp $

COMMENT = Communication utilities

SUBDIR += acfax
SUBDIR += aldo
SUBDIR += asmodem
SUBDIR += atslog
SUBDIR += bforce
SUBDIR += bforce-kst
SUBDIR += cdr_read
SUBDIR += chu
SUBDIR += comserv
SUBDIR += efax
SUBDIR += kermit
SUBDIR += kmobiletools
SUBDIR += libirman
SUBDIR += lirc
SUBDIR += lrzsz
SUBDIR += minicom
SUBDIR += p5-Device-Gsm
SUBDIR += p5-Device-Modem
SUBDIR += p5-Device-SerialPort
SUBDIR += p5-SMS-Send
SUBDIR += pr
SUBDIR += qfaxreader
SUBDIR += tits
SUBDIR += zssh

.include <bsd.port.subdir.mk>
