# $FreeBSD: ports/x11/xf86driproto/Makefile,v 1.1 2007/05/19 20:27:50 flz Exp $
# $MidnightBSD: mports/x11/xf86driproto/Makefile,v 1.2 2010/03/13 00:29:29 laffer1 Exp $

PORTNAME=	xf86driproto
PORTVERSION=	2.1.0
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	XFree86-DRI extension headers
LICENSE=	x11

XORG_CAT=	proto

.include <bsd.port.mk>
