PORTNAME=	xf86-input-elographics
PORTVERSION=	1.4.2
PORTREVISION=	1
CATEGORIES=	x11-drivers

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X.Org elographics input driver

LICENSE=	mit
LICENSE_FILE=	${WRKSRC}/COPYING

USES=		xorg-cat:driver

.include <bsd.port.mk>
