# $MidnightBSD: mports/lang/Makefile,v 1.17 2007/01/20 14:40:05 wintellect Exp $
#

    COMMENT = Programming languages

    SUBDIR += ezm3
    SUBDIR += gawk
    SUBDIR += gcc-objc
    SUBDIR += gcc32
    SUBDIR += gcc33
    SUBDIR += gcc40
    SUBDIR += gcc41
    SUBDIR += gcc41-withgcjawt
    SUBDIR += gcc42
    SUBDIR += gcc42-withgcjawt
    SUBDIR += gnustep-base
    SUBDIR += gnustep-objc
    SUBDIR += p5-Data-JavaScript
    SUBDIR += p5-Error
    SUBDIR += p5-F77
    SUBDIR += p5-List-MoreUtils
    SUBDIR += p5-Scalar-List-Utils
    SUBDIR += p5-ePerl
    SUBDIR += python
    SUBDIR += python21
    SUBDIR += python22
    SUBDIR += python23
    SUBDIR += perl5.8
    SUBDIR += php5
    SUBDIR += php5-extensions
    SUBDIR += ruby18
    SUBDIR += tcl83
    SUBDIR += tcl84

.include <bsd.port.subdir.mk>
