PORTNAME=	base64
PORTVERSION=	0.2.0
CATEGORIES=	converters rubygems
MASTER_SITES=	RG

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Encode and decode binary data using a Base64 representation
WWW=		https://github.com/ruby/base64

LICENSE=	bsd2 ruby
LICENSE_COMB=	dual
LICENSE_FILE_bsd2=${WRKSRC}/LICENSE.txt

USES=		gem

NO_ARCH=	yes

.include <bsd.port.mk>
