PORTNAME=	xmore
PORTVERSION=	1.0.3
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Plain text display program for X

LICENSE=	mit

USES=		xorg xorg-cat:app
USE_XORG=	x11 xt xaw

.include <bsd.port.mk>
