# $MidnightBSD: mports/devel/p5-version/Makefile,v 1.8 2011/05/31 00:11:56 laffer1 Exp $

PORTNAME=	version
PORTVERSION=	0.89
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	../by-authors/id/J/JP/JPEACOCK
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Perl extension for Version Objects
LICENSE=	perl

PERL_CONFIGURE=	yes

MAN3=		version.3 version::Internals.3

.include <bsd.port.mk>
