# New ports collection makefile for:    tcl85-thread
# Date created:         4 Apr 2007
# Whom:                 Lucas Holt <luke@midnightbsd.org>
#
# $MidnightBSD: mports/lang/tcl85-thread/Makefile,v 1.4 2008/03/31 00:19:44 ctriv Exp $
# $FreeBSD: ports/lang/tcl85-thread/Makefile,v 1.2 2007/03/16 20:23:52 miwi Exp $
#

BROKEN=	doesn't fake right.
BUILDING_TCL_THREADS=	yes
PKGNAMESUFFIX=		-thread

MASTERDIR=	${.CURDIR}/../tcl85

.include	"${MASTERDIR}/Makefile"
