# Ports collection makefile for:	db42-nocrypto
# Date created:				2004-01-04
# Whom:					matthias.andree@gmx.de
#
# $FreeBSD: ports/databases/db42-nocrypto/Makefile,v 1.2 2004/01/09 09:45:37 pav Exp $
# $MidnightBSD$
#

PKGNAMESUFFIX=	-nocrypto
DISTNAME=	db-${PORTVERSION}.NC

MAINTAINER=	ports@MidnightBSD.org

MASTERDIR=	${.CURDIR}/../db42
MD5_FILE=	${.CURDIR}/distinfo

.include "${MASTERDIR}/Makefile"
