# $MidnightBSD: mports/audio/Makefile,v 1.9 2006/10/03 16:00:04 wintellect Exp $
#

    COMMENT = Audio tools

    SUBDIR += libao
    SUBDIR += libaudiofile
    SUBDIR += libid3tag
    SUBDIR += libmad
    SUBDIR += libmikmod
    SUBDIR += libogg
    SUBDIR += libvorbis
    SUBDIR += madplay
    SUBDIR += mpg123
    SUBDIR += wmmp3
    SUBDIR += wmsmixer

.include <bsd.port.subdir.mk>
