# $MidnightBSD: mports/audio/Makefile,v 1.14 2006/10/05 01:33:44 laffer1 Exp $
#

    COMMENT = Audio tools

    SUBDIR += flac
    SUBDIR += lame
    SUBDIR += libao
    SUBDIR += libaudiofile
    SUBDIR += libcddb
    SUBDIR += libid3tag
    SUBDIR += libmad
    SUBDIR += libmikmod
    SUBDIR += libmodplug
    SUBDIR += libogg
    SUBDIR += libvorbis
    SUBDIR += madplay
    SUBDIR += mpg123
    SUBDIR += sdl_mixer
    SUBDIR += speex
    SUBDIR += wmmp3
    SUBDIR += wmsmixer

.include <bsd.port.subdir.mk>
