# $MidnightBSD: mports/lang/Makefile,v 1.5 2006/10/02 23:46:19 laffer1 Exp $
# $FreeBSD: ports/lang/Makefile,v 1.512 2006/09/04 16:28:30 bsam Exp $
#

    COMMENT = Programming languages

    SUBDIR += gcc-objc
    SUBDIR += gcc32
    SUBDIR += gcc33
    SUBDIR += gcc40
    SUBDIR += gcc41
    SUBDIR += gcc41-withgcjawt
    SUBDIR += gcc42
    SUBDIR += gcc42-withgcjawt
    SUBDIR += gnustep-base
    SUBDIR += gnustep-objc
    SUBDIR += perl5.8
    SUBDIR += ruby18

.include <bsd.port.subdir.mk>
