# $MidnightBSD: mports/lang/Makefile,v 1.8 2006/10/31 19:57:03 laffer1 Exp $
#

    COMMENT = Programming languages

    SUBDIR += gcc-objc
    SUBDIR += gcc32
    SUBDIR += gcc33
    SUBDIR += gcc40
    SUBDIR += gcc41
    SUBDIR += gcc41-withgcjawt
    SUBDIR += gcc42
    SUBDIR += gcc42-withgcjawt
    SUBDIR += gnustep-base
    SUBDIR += gnustep-objc
    SUBDIR += p5-Data-JavaScript
    SUBDIR += p5-Error
    SUBDIR += p5-F77
    SUBDIR += p5-List-MoreUtils
    SUBDIR += p5-Scalar-List-Utils
    SUBDIR += p5-ePerl
    SUBDIR += perl5.8
    SUBDIR += php5
    SUBDIR += ruby18

.include <bsd.port.subdir.mk>
