# $MidnightBSD: mports/x11-wm/Makefile,v 1.40 2012/12/19 04:06:21 laffer1 Exp $

COMMENT = X11 window managers

SUBDIR += afterstep
SUBDIR += awesome
SUBDIR += blackbox
SUBDIR += compiz
SUBDIR += enlightenment
SUBDIR += enlightenment-docs
SUBDIR += etoile-azalea
SUBDIR += etoile-azdock
SUBDIR += etoile-azswitch
SUBDIR += etoile-login
SUBDIR += fluxbox
SUBDIR += fvwm2
SUBDIR += icewm
SUBDIR += kompmgr
SUBDIR += libcompizconfig
SUBDIR += libdockapp
SUBDIR += metacity
SUBDIR += obconf
SUBDIR += obmenu
SUBDIR += openbox
SUBDIR += ratpoison
SUBDIR += skippy-xd
SUBDIR += transset-df
SUBDIR += twm
SUBDIR += windowmaker
SUBDIR += wmii
SUBDIR += xcompmgr
SUBDIR += xfce4
SUBDIR += xfce4-desktop
SUBDIR += xfce4-panel
SUBDIR += xfce4-session
SUBDIR += xfce4-wm

.include <bsd.port.subdir.mk>
