COMMENT = X11 window managers

SUBDIR += afterstep
SUBDIR += awesome
SUBDIR += blackbox
SUBDIR += compiz
SUBDIR += compton
SUBDIR += emwm
SUBDIR += enlightenment
SUBDIR += fluxbox
SUBDIR += fvwm2
SUBDIR += hikari
SUBDIR += i3
SUBDIR += icewm
SUBDIR += libcompizconfig
SUBDIR += libdockapp
SUBDIR += libwraster
SUBDIR += marco
SUBDIR += metacity
SUBDIR += muffin
SUBDIR += mutter
SUBDIR += obconf
SUBDIR += openbox
SUBDIR += ratpoison
SUBDIR += twm
SUBDIR += windowmaker
SUBDIR += wmii
SUBDIR += wmii-devel
SUBDIR += xcompmgr
SUBDIR += xfce4
SUBDIR += xfce4-desktop
SUBDIR += xfce4-panel
SUBDIR += xfce4-session
SUBDIR += xfce4-wm
SUBDIR += yeahwm

.include <bsd.port.subdir.mk>
