# $MidnightBSD: mports/x11-wm/Makefile,v 1.1 2006/09/17 04:48:51 archite Exp $
# $FreeBSD: ports/x11-wm/Makefile,v 1.186 2006/09/10 15:15:38 vanilla Exp $
#

    COMMENT = X11 window managers

    SUBDIR += boxtools
    SUBDIR += fluxbox
    SUBDIR += pekwm

.include <bsd.port.subdir.mk>
