# $MidnightBSD$

PORTNAME=	libpthread-stubs
PORTVERSION=	0.1
CATEGORIES=	devel
MASTER_SITES=	http://xcb.freedesktop.org/dist/

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	This library provides weak aliases for pthread functions
LICENSE=	x11

USE_GMAKE=	yes
USE_BZIP2=	yes
USE_GNOME=	gnomehack pkgconfig
USE_LDCONFIG=	yes

GNU_CONFIGURE=	yes

.include <bsd.port.mk>
