# $MidnightBSD: mports/science/Makefile,v 1.5 2009/01/20 15:35:13 laffer1 Exp $

COMMENT= Scientific applications

SUBDIR += cfitsio
SUBDIR += openbabel
SUBDIR += linux-foldingathome

.include <bsd.port.subdir.mk>
