COMMENT= Scientific applications

SUBDIR += gtamsanalyzer
SUBDIR += hdf5
SUBDIR += libaec
SUBDIR += libkml
SUBDIR += linux-foldingathome 
SUBDIR += netcdf
SUBDIR += openbabel
SUBDIR += paje
SUBDIR += py-scikit-sparse
SUBDIR += py-scipy
SUBDIR += szip

.include <bsd.port.subdir.mk>
