# New ports collection makefile for:	p5-Digest-SHA1
# Date created:				30 March 2001
# Whom:					Yen-Ming Lee <leeym@cae.ce.ntu.edu.tw>
#
# $MidnightBSD: mports/security/p5-Digest-SHA1/Makefile,v 1.1 2007/02/23 21:17:33 laffer1 Exp $
# $FreeBSD: ports/security/p5-Digest-SHA1/Makefile,v 1.13 2006/01/19 14:34:54 erwin Exp $
#

PORTNAME=	Digest-SHA1
PORTVERSION=	2.11
CATEGORIES=	security perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Perl interface to the SHA-1 Algorithm
LICENSE=	perl

PERL_CONFIGURE=	yes

MAN3=		Digest::SHA1.3

.include <bsd.port.mk>
