PORTNAME=	cmprsk
DISTVERSION=	2.2-12
CATEGORIES=	science
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Subdistribution Analysis of Competing Risks
WWW=		https://cran.r-project.org/web/packages/cmprsk/

LICENSE=	gpl2+

USES=		cran:auto-plist,compiles

.include <bsd.port.mk>
