PORTNAME=	equalizer
PORTVERSION=	0.0.11
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Ruby library to define equality methods
WWW=		https://github.com/dkubb/equalizer

LICENSE=	mit

NO_ARCH=	yes

USES=		gem

.include <bsd.port.mk>
