# $MidnightBSD$
# $FreeBSD: ports/devel/php5-json/Makefile,v 1.3 2008/12/11 08:54:19 ale Exp $

CATEGORIES=	devel

MASTERDIR=	${.CURDIR}/../../lang/php5

PKGNAMESUFFIX=	-json

.include "${MASTERDIR}/Makefile"
