# $MidnightBSD: mports/net-p2p/Makefile,v 1.7 2008/03/15 21:41:28 laffer1 Exp $
#

    COMMENT = peer-to-peer network applications

    SUBDIR += ctorrent
    SUBDIR += frostwire
    SUBDIR += gift
    SUBDIR += gift-fasttrack
    SUBDIR += gift-gnutella
    SUBDIR += giftcurs
    SUBDIR += libtorrent
    SUBDIR += limewire
    SUBDIR += mutella
    SUBDIR += rtorrent
    SUBDIR += transmission

.include <bsd.port.subdir.mk>
