COMMENT = peer-to-peer network applications

SUBDIR += ctorrent
SUBDIR += libktorrent
SUBDIR += libtorrent
SUBDIR += libtorrent-rasterbar
SUBDIR += libutp
SUBDIR += qbittorrent
SUBDIR += rtorrent
SUBDIR += shx
SUBDIR += transmission
SUBDIR += transmission-components
SUBDIR += transmission-remote-gui
SUBDIR += udpt
SUBDIR += uhub
SUBDIR += walletd
SUBDIR += warpinator
SUBDIR += xbt
SUBDIR += xmrig

.include <bsd.port.subdir.mk>
