# New ports collection makefile for:	p5-IO-String
# Date created:		13 March 2001
# Whom:	      		Johann Visagie <johann@egenetics.com>
#
# $FreeBSD: ports/devel/p5-IO-String/Makefile,v 1.12 2005/12/07 18:52:49 erwin Exp $
# $MidnightBSD$
#

PORTNAME=	IO-String
PORTVERSION=	1.08
CATEGORIES=	devel perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	IO
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Simplified Perl5 module to handle I/O on in-core strings
LICENSE=	perl

PERL_CONFIGURE=	yes

MAN3=		IO::String.3

.include <bsd.port.mk>
