# $MidnightBSD$

PORTNAME=	libfontenc
PORTVERSION=	1.1.3
CATEGORIES=	x11-fonts

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	The fontenc Library

LICENSE=	mit
LICENSE_FILE=	${WRKSRC}/COPYING

XORG_CAT=	lib
USE_XORG=	xproto

.include <bsd.port.mk>
