# $FreeBSD: head/graphics/php72-exif/Makefile 475229 2018-07-24 08:44:32Z tz $

CATEGORIES=	graphics

MASTERDIR=	${.CURDIR}/../../lang/php72

PKGNAMESUFFIX=	-exif

TEST_TARGET=    test

.include "${MASTERDIR}/Makefile"
