# $MidnightBSD: mports/security/Makefile,v 1.3 2006/09/21 14:19:06 laffer1 Exp $
# $FreeBSD: ports/security/Makefile,v 1.816 2006/09/07 21:40:37 acm Exp $
#

    COMMENT = Security tools

    SUBDIR += libgcrypt
    SUBDIR += libgpg-error
    SUBDIR += nss
    SUBDIR += sudo

.include <bsd.port.subdir.mk>
