# $MidnightBSD: mports/security/Makefile,v 1.11 2006/10/02 16:34:47 laffer1 Exp $
# $FreeBSD: ports/security/Makefile,v 1.816 2006/09/07 21:40:37 acm Exp $
#

    COMMENT = Security tools

    SUBDIR += ca-roots
    SUBDIR += clamav
    SUBDIR += cyrus-sasl
    SUBDIR += cyrus-sasl2
    SUBDIR += cyrus-sasl2-ldapdb
    SUBDIR += cyrus-sasl2-saslauthd
    SUBDIR += gnupg
    SUBDIR += gnutls
    SUBDIR += libgcrypt
    SUBDIR += libgpg-error
    SUBDIR += openvpn
    SUBDIR += nss
    SUBDIR += sudo

.include <bsd.port.subdir.mk>
