# Created by: Thierry Thomas (<thierry@pompo.net>)

PORTNAME=	Net_Socket
PORTVERSION=	1.0.14
CATEGORIES=	net www

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	PEAR Network Socket Interface

LICENSE=	php

USES=	pear
NO_ARCH=	yes

.include <bsd.port.mk>
