# New ports collection makefile for:	libtifiles
# Date created:		27 August 2003
# Whom:			Tijl Coosemans <tijl@ulyssis.org>
#
# $MidnightBSD: mports/devel/libtifiles/Makefile,v 1.2 2008/10/08 19:45:19 ctriv Exp $
# $FreeBSD: ports/devel/libtifiles/Makefile,v 1.14 2006/10/06 02:31:27 clsung Exp $
#

PORTNAME=	libtifiles
PORTVERSION=	0.6.5
PORTREVISION=	1
CATEGORIES=	devel
MASTER_SITES=		${MASTER_SITE_SOURCEFORGE}
MASTER_SITE_SUBDIR=	tilp

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	TI calculator file types library
LICENSE=	gpl2

USE_GETTEXT=	yes
USE_GNOME=	gnomehack pkgconfig
USE_AUTOTOOLS=	libtool:22
USE_GMAKE=	yes
USE_LDCONFIG=	yes

.include <bsd.port.mk>
