# New ports collection makefile for:	php5-iconv
# Date created:			7 Jul 2004
# Whom:				Alex Dupre <ale@FreeBSD.org>
#
# $MidnightBSD$
# $FreeBSD: ports/converters/php5-iconv/Makefile,v 1.1 2004/07/19 08:45:42 ale Exp $
#

CATEGORIES=	converters

MASTERDIR=	${.CURDIR}/../../lang/php5

PKGNAMESUFFIX=	-iconv

.include "${MASTERDIR}/Makefile"
