PORTNAME=	Net_SmartIRC
PORTVERSION=	1.1.14
CATEGORIES=	irc www pear

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	PEAR class for communication with IRC networks
WWW=		https://pear.php.net/package/Net_SmartIRC

LICENSE=	lgpl2.1
LICENSE_FILE=	${WRKSRC}/LICENSE

NO_ARCH=	yes
USES=		pear

.include <bsd.port.mk>
