    COMMENT = Internet Relay Chat utilities

SUBDIR += bitlbee
SUBDIR += bnc
SUBDIR += catgirl
SUBDIR += irssi
SUBDIR += irssi-scripts
SUBDIR += polari
SUBDIR += ngircd
SUBDIR += simpleirc
SUBDIR += sirc
SUBDIR += smartirc4net
SUBDIR += talksoup
SUBDIR += unreal
SUBDIR += weechat
SUBDIR += weechat-otr
SUBDIR += znc
SUBDIR += znc-clientbuffer
SUBDIR += znc-push

.include <bsd.port.subdir.mk>
