    COMMENT = Internet Relay Chat utilities

SUBDIR += bitlbee
SUBDIR += bnc
SUBDIR += irssi
SUBDIR += irssi-scripts
SUBDIR += ngircd
SUBDIR += simpleirc
SUBDIR += sirc
SUBDIR += talksoup
SUBDIR += znc

.include <bsd.port.subdir.mk>
