# $MidnightBSD: mports/irc/Makefile,v 1.8 2007/08/10 21:59:20 laffer1 Exp $
#

    COMMENT = Internet Relay Chat utilities

    SUBDIR += bitchx
    SUBDIR += bitlbee
    SUBDIR += bnc
    SUBDIR += irssi
    SUBDIR += irssi-scripts
    SUBDIR += ngircd
    SUBDIR += sirc
    SUBDIR += tirc
    SUBDIR += xchat

.include <bsd.port.subdir.mk>
