# New ports collection makefile for:	gstreamer-plugins-ogg
# Date created:			23 Nov 2007
# Whom:				Lucas Holt <luke@midnightbsd.org>
#
# $MidnightBSD$

CATEGORIES=	audio

COMMENT=	Gstreamer Ogg bitstream plugin
LICENSE=	lgpl

GST_PLUGIN=	ogg

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
