PORTNAME=	certifi
PORTVERSION=	2024.2.2
PORTREVISION=	1
CATEGORIES=	security python
MASTER_SITES=	PYPI
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Mozilla SSL certificates
WWW=		https://github.com/certifi/python-certifi

LICENSE=	MPL20

USES=		python
USE_PYTHON=	allflavors autoplist concurrent distutils

NO_ARCH=	yes

.include <bsd.port.mk>
