# New ports collection makefile for:	xditview
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11/xditview/Makefile,v 1.1 2007/05/19 20:27:45 flz Exp $
# $MidnightBSD$
#

PORTNAME=	xditview
PORTVERSION=	1.0.1
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Display ditroff output
LICENSE=	x11

XORG_CAT=	app
USE_XORG=	xt xaw

MAN1=		xditview.1

.include <bsd.port.mk>
