# New ports collection makefile for:   libXext
# Date Created:			29 Oct, 2003
# Whom:				Eric Anholt <anholt@FreeBSD.org>
#
# $FreeBSD: ports/x11/libXfixes/Makefile,v 1.14 2007/05/19 20:26:51 flz Exp $
# $MidnightBSD$
#

PORTNAME=	libXfixes
PORTVERSION=	4.0.3
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X Fixes extension library
LICENSE=	x11

XORG_CAT=	lib
USE_XORG=	x11 fixesproto:both xproto xextproto

MAN3=		Xfixes.3

.include <bsd.port.mk>
