# $MidnightBSD$
# $FreeBSD: ports/converters/p5-Encode-Locale/Makefile,v 1.3 2011/06/21 06:58:07 az Exp $

PORTNAME=	Encode-Locale
PORTVERSION=	1.02
CATEGORIES=	converters perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:GAAS
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Determine the locale encoding
LICENSE=	perl

PERL_CONFIGURE=	yes

MAN3=		Encode::Locale.3

.include <bsd.port.mk>
