# $MidnightBSD: mports/devel/p5-Test-Taint/Makefile,v 1.1 2011/07/17 19:47:29 laffer1 Exp $

PORTNAME=	Test-Taint
PORTVERSION=	1.06
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Tools to test taintedness
LICENSE=	perl

PERL_CONFIGURE=	yes

MAN3=		Test::Taint.3

.include <bsd.port.mk>
