# $MidnightBSD$

COMMENT = Network management tools

SUBDIR += aircrack-ng
SUBDIR += docsis
SUBDIR += kismet
SUBDIR += p5-Cflow
SUBDIR += p5-Cisco-Reconfig
SUBDIR += p5-Mon
SUBDIR += p5-Net-CIDR
SUBDIR += p5-Net-IP
SUBDIR += p5-Net-SNMP
SUBDIR += p5-NetAddr-IP
SUBDIR += p5-NSNMP
SUBDIR += p5-SNMP_Session
SUBDIR += php70-snmp
SUBDIR += php71-snmp
SUBDIR += net-snmp
SUBDIR += softflowd
SUBDIR += subcalc
SUBDIR += sysmon
SUBDIR += tcpreplay
SUBDIR += tcptrack
SUBDIR += weplab
SUBDIR += whatmask

.include <bsd.port.subdir.mk>
