# $MidnightBSD: mports/x11/xtrans/Makefile,v 1.3 2011/05/07 20:43:10 laffer1 Exp $

PORTNAME=	xtrans
PORTVERSION=	1.2.6
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Abstract network code for X
LICENSE=	x11

XORG_CAT=	lib

.include <bsd.port.mk>
