PORTNAME=	xtrans
PORTVERSION=	1.4.0
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Abstract network code for X

LICENSE=	mit

USES=		xorg xorg-cat:lib
CONFIGURE_ARGS+=--disable-docs --without-xmlto

.include <bsd.port.mk>
