PORTNAME=	net-pop
PORTVERSION=	0.1.2
CATEGORIES=	mail rubygems
MASTER_SITES=	RG

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Ruby client library for POP3
WWW=		https://github.com/ruby/net-pop

LICENSE=	bsd2 ruby
LICENSE_COMB=	dual
LICENSE_FILE_bsd2=${WRKSRC}/LICENSE.txt

RUN_DEPENDS=	rubygem-net-protocol>=0:net/rubygem-net-protocol

USES=		gem

NO_ARCH=	yes

.include <bsd.port.mk>
