# $MidnightBSD$

PORTNAME=	configparser
PORTVERSION=	3.5.0
PORTEPOCH=	1
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	INI style configuration file parser

LICENSE=	mit

USES=		python:2
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
