# $MidnightBSD: mports/x11-drivers/xf86-input-spaceorb/Makefile,v 1.2 2009/03/27 23:41:27 laffer1 Exp $

PORTNAME=	xf86-input-spaceorb
PORTVERSION=	1.1.1
PORTREVISION=	2
CATEGORIES=	x11-drivers

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X.Org spaceorb input driver
LICENSE=	x11

IGNORE=		Unmaintained upstream.

XORG_CAT=	driver

.include <bsd.port.mk>
