PORTNAME=	tty-cursor
PORTVERSION=	0.7.1
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Move terminal cursor around
WWW=		https://ttytoolkit.org/ \
		https://github.com/piotrmurach/tty-cursor

LICENSE=	mit
LICENSE_FILE=	${WRKSRC}/LICENSE.txt

USES=		gem

NO_ARCH=	yes

.include <bsd.port.mk>
