PORTNAME=	Horde_Group
PORTVERSION=	2.1.1
CATEGORIES=	security www pear

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Horde User Groups System
WWW=		https://pear.horde.org

LICENSE=	lgpl2.1

USES=	horde cpe
USE_HORDE_RUN=	Horde_Exception \
		Horde_Util

.include <bsd.port.mk>
