# New ports collection makefile for:   p5-DBD-mysql50
#
# $MidnightBSD: mports/databases/p5-DBD-mysql50/Makefile,v 1.1 2006/10/03 21:03:20 laffer1 Exp $
# $FreeBSD: ports/databases/p5-DBD-mysql50/Makefile,v 1.6 2006/02/05 10:13:54 ale Exp $

PKGNAMESUFFIX=	50

COMMENT=	MySQL 5.0 driver for the Perl5 Database Interface (DBI)

CONFLICTS=	p5-Mysql-modules-[0-9]* p5-DBD-mysql-[0-9]* p5-DBD-mysql4[0-9]-[0-9]* p5-DBD-mysql5[1-9]-[0-9]*

WANT_MYSQL_VER=	50

MASTERDIR=	${.CURDIR}/../p5-DBD-mysql

.include "${MASTERDIR}/Makefile"
