# $MidnightBSD$
# $FreeBSD: ports/x11-themes/linux-f10-qtcurve-gtk2/Makefile,v 1.2 2011/02/25 08:52:30 netchild Exp $

PORTNAME=	qtcurve-gtk2
PORTVERSION=	0.69.2
PORTREVISION?=	0
CATEGORIES=	x11-themes linux
PKGNAMEPREFIX=	linux-f10-
DISTNAME=	${PORTNAME}-${PORTVERSION}-${RPMVERSION}

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	QtCurve GTK2 Theme Engine (Linux Fedora 10)
LICENSE=	gpl2

USE_LINUX=	f10
USE_LINUX_RPM=	yes
USE_LINUX_APPS=	gtk2
RPMVERSION=	1.fc10

.include <bsd.port.mk>
