PORTNAME=	aes_key_wrap
PORTVERSION=	1.1.0
CATEGORIES=	security rubygems
MASTER_SITES=	RG

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Ruby implementation of AES Key Wrap
WWW=		https://github.com/tomdalling/aes_key_wrap

LICENSE=	mit
LICENSE_FILE=	${WRKSRC}/LICENSE.txt

USES=		gem shebangfix

NO_ARCH=	yes

SHEBANG_FILES=	bin/setup

.include <bsd.port.mk>
