# New ports collection makefile for:	xf86-input-keyboard
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11-drivers/xf86-input-keyboard/Makefile,v 1.2 2007/09/13 19:44:48 flz Exp $
# $MidnightBSD$
#

PORTNAME=	xf86-input-keyboard
PORTVERSION=	1.2.2
CATEGORIES=	x11-drivers

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X.Org keyboard input driver
LICENSE=	x11

XORG_CAT=	driver
USE_XORG=	kbproto
MAN4=		kbd.4x

.include <bsd.port.mk>
