# $MidnightBSD$

PORTNAME=	imageviewer
PORTVERSION=	0.6.3
CATEGORIES=	graphics gnustep
MASTER_SITES=	http://www.nice.ch/~phip/
DISTNAME=	ImageViewer-${PORTVERSION}

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	GNUstep Image Viewer
LICENSE=	gpl2

USE_GNUSTEP=	yes
USE_GNUSTEP_PREFIX=	yes
USE_GNUSTEP_BACK=	yes
USE_GNUSTEP_BUILD=	yes
USE_GNUSTEP_INSTALL=	yes

.include <bsd.port.mk>
