# $MidnightBSD$

PORTNAME=	gnuwash
PORTVERSION=	0.1
CATEGORIES=	deskutils gnustep
MASTER_SITES=	${MASTER_SITE_DEBIAN}
MASTER_SITE_SUBDIR=	pool/main/g/gnuwash.app
DISTNAME=	${PORTNAME}.app_${PORTVERSION}.orig

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Configurable GNUstep timer application
LICENSE=	gpl2

USE_GNUSTEP=	yes
USE_GNUSTEP_PREFIX=	yes
USE_GNUSTEP_BACK=	yes
USE_GNUSTEP_BUILD=	yes
USE_GNUSTEP_INSTALL=	yes

WRKSRC=		${WRKDIR}/${PORTNAME}-${PORTVERSION}

.include <bsd.port.mk>
