PORTNAME=	attic
PORTVERSION=	1.0.1
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Place to hide private instance variables in your Ruby objects
WWW=		https://github.com/delano/attic

LICENSE=	mit
LICENSE_FILE=	${WRKSRC}/LICENSE.txt

BUILD_DEPENDS=	rubygem-rake>=13.0.6:devel/rubygem-rake
RUN_DEPENDS=	rubygem-rake>=13.0.6:devel/rubygem-rake

USES=		gem

NO_ARCH=	yes

.include <bsd.port.mk>
