# $MidnightBSD$

PORTNAME=	xf86-video-vesa
PORTVERSION=	2.4.0
CATEGORIES=	x11-drivers

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X.Org vesa display driver

LICENSE=	mit

XORG_CAT=	driver
USE_XORG=	xextproto videoproto

.include <bsd.port.mk>
