# Created by: Adam Herzog <adam@herzogdesigns.com>

PORTNAME=	XML-Writer
PORTVERSION=	0.625
PORTREVISION=	1
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:JOSEPHW
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Simple Perl module for writing XML documents

LICENSE=	publicdom
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		perl5
USE_PERL5=	configure
NO_ARCH=	yes

.include <bsd.port.mk>
