# $MidnightBSD$

PORTNAME=	Email-Date-Format
PORTVERSION=	1.002
CATEGORIES=	mail perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	Email
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Produce RFC 2822 date strings
LICENSE=	perl

PERL_CONFIGURE=	yes

MAN3=	Email::Date::Format.3

.include <bsd.port.mk>
