# $MidnightBSD: mports/textproc/p5-XML-Writer/Makefile,v 1.1 2007/06/11 02:03:59 laffer1 Exp $

PORTNAME=	XML-Writer
PORTVERSION=	0.602
CATEGORIES=	textproc perl5
MASTER_SITES=	${MASTER_SITE_PERL_CPAN}
MASTER_SITE_SUBDIR=	XML
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	A simple Perl module for writing XML documents
LICENSE=	perl

PERL_CONFIGURE=	yes

MAN3=		XML::Writer.3

.include <bsd.port.mk>
