# $MidnightBSD: mports/security/p5-Crypt-OpenSSL-Bignum/Makefile,v 1.1 2007/03/21 01:35:11 laffer1 Exp $

PORTNAME=	Crypt-OpenSSL-Bignum
PORTVERSION=	0.04
CATEGORIES=	security perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	OpenSSL's multiprecision integer arithmetic
LICENSE=	perl

PERL_CONFIGURE=	yes

MAN3=		Crypt::OpenSSL::Bignum::CTX.3 Crypt::OpenSSL::Bignum.3

.include <bsd.port.mk>
