# $MidnightBSD: mports/net/Makefile,v 1.2 2006/10/01 16:30:58 laffer1 Exp $
#

    COMMENT = Networking tools

    SUBDIR += netcat
    SUBDIR += netclasses
    SUBDIR += rsync

.include <bsd.port.subdir.mk>
