# $MidnightBSD$

PORTNAME=	Net-CIDR-Lite
PORTVERSION=	0.21
PORTREVISION=	1
CATEGORIES=	net perl5 ipv6
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Perl extension for merging IPv4 or IPv6 CIDR addresses

LICENSE=	artistic gpl
LICENSE_COMB=	dual

PERL_CONFIGURE=	yes

.include <bsd.port.mk>
