# $MidnightBSD$

PORTNAME=	Parse-Yapp
PORTVERSION=	1.05
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Perl extension for generating and using LALR parsers
LICENSE=	perl

PERL_CONFIGURE=	yes

MAN1=		yapp.1
MAN3=		Parse::Yapp.3

.include <bsd.port.mk>
