# Created by: Kubilay Kocak <koobs@FreeBSD.org>

PORTNAME=	passlib
PORTVERSION=	1.7.2
CATEGORIES=	security python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Comprehensive password hashing framework supporting over 30 schemes

LICENSE=	bsd3
LICENSE_FILE=	${WRKSRC}/LICENSE

# Python 2.6,3.3-3.8
USES=		python:3.6+
USE_PYTHON=	autoplist distutils

NO_ARCH=	yes
NO_TEST=	yes

.include <bsd.port.mk>
