COMMENT = Emulators for other operating systems

SUBDIR += adamem
SUBDIR += advancemame
SUBDIR += aftp
SUBDIR += atari800
SUBDIR += bochs
SUBDIR += dgen-sdl
SUBDIR += dosbox
SUBDIR += extract-xiso
SUBDIR += i386-wine
SUBDIR += kqemu-kmod
SUBDIR += linux-c7
SUBDIR += linux_base-c7
SUBDIR += mtools
SUBDIR += open-vm-tools
SUBDIR += pcem
SUBDIR += qemu
SUBDIR += rtc
SUBDIR += tpm-emulator
SUBDIR += vba
SUBDIR += vice
SUBDIR += vxtools
SUBDIR += wine
SUBDIR += wine-gecko
SUBDIR += wine-mono
SUBDIR += xhomer
SUBDIR += zsnes

.include <bsd.port.subdir.mk>
