COMMENT = Emulators for other operating systems

SUBDIR += adamem
SUBDIR += aftp
SUBDIR += bochs
SUBDIR += dgen-sdl
SUBDIR += dosbox
SUBDIR += extract-xiso
SUBDIR += i386-wine
SUBDIR += kqemu-kmod
SUBDIR += linux-c6
SUBDIR += linux-c7
SUBDIR += linux_base-c6
SUBDIR += linux_base-c7
SUBDIR += mtools
SUBDIR += open-vm-tools
SUBDIR += open-vm-tools-nox11
SUBDIR += pearpc
SUBDIR += qemu
SUBDIR += rtc
SUBDIR += snes9x
SUBDIR += tpm-emulator
SUBDIR += vMac
SUBDIR += vba
SUBDIR += virtio-kmod
SUBDIR += virtualbox-ose-kmod
SUBDIR += vxtools
SUBDIR += wine
SUBDIR += wine-gecko
SUBDIR += wine-mono
SUBDIR += xhomer
SUBDIR += yabause
SUBDIR += yape

.include <bsd.port.subdir.mk>
