# $MidnightBSD: mports/emulators/Makefile,v 1.5 2007/02/19 21:07:21 laffer1 Exp $
#

    COMMENT = Emulators for other operating systems

    SUBDIR += bochs
    SUBDIR += linux_base-fc4
    SUBDIR += mtools
    SUBDIR += pearpc
    SUBDIR += qemu
    SUBDIR += wine

.include <bsd.port.subdir.mk>
