# New ports collection makefile for:	lndir
# Date Created:				16 Oct 2007
# Whom:					Lucas Holt <luke@MidnightBSD.org>
#
# $MidnightBSD$
#

PORTNAME=	lndir
PORTVERSION=	1.0.3
CATEGORIES=	devel

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Create a shadow directory of symbolic links to another directory tree

LICENSE=	unknown
# The license is not cleary stated.

XORG_CAT=	util
USE_XORG=	xproto
USE_PKGCONFIG=	yes

PLIST_FILES=	bin/lndir

MAN1=		lndir.1

.include <bsd.port.mk>
