PORTNAME=	more-itertools
PORTVERSION=	8.7.0
CATEGORIES=	devel python
MASTER_SITES=	PYPI
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	More routines for operating on iterables, beyond itertools

LICENSE=	mit
LICENSE_FILE=	${WRKSRC}/LICENSE


USES=		python
USE_PYTHON=	distutils concurrent autoplist

NO_TEST=	yes

.include <bsd.port.mk>
