# $FreeBSD: head/databases/php72-sqlite3/Makefile 475229 2018-07-24 08:44:32Z tz $

CATEGORIES=	databases

MASTERDIR=	${.CURDIR}/../../lang/php72

PKGNAMESUFFIX=	-sqlite3

TEST_TARGET=    test

.include "${MASTERDIR}/Makefile"
