PORTNAME=	png
DISTVERSION=	0.1-8
CATEGORIES=	graphics
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Read and write PNG images
WWW=		https://www.rforge.net/png/

LICENSE=	gpl2+

LIB_DEPENDS=	libpng.so:graphics/png

USES=		cran:auto-plist,compiles

.include <bsd.port.mk>
