# $MidnightBSD: mports/x11/glproto/Makefile,v 1.4 2013/03/23 16:37:27 laffer1 Exp $

PORTNAME=	glproto
PORTVERSION=	1.4.16
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	GLX extension headers
LICENSE=	sgi

XORG_CAT=	proto

.include <bsd.port.mk>
