# $MidnightBSD$

PORTNAME=	showfont
PORTVERSION=	1.0.4
CATEGORIES=	x11-fonts

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Font dumper for the X font server
LICENSE=	mit

XORG_CAT=	app
USE_XORG=	libfs

PLIST_FILES=	bin/showfont

MAN1=		showfont.1

.include <bsd.port.mk>
