# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/net/php56-sockets/Makefile 367268 2014-09-04 14:24:25Z ale $

CATEGORIES=	net

MASTERDIR=	${.CURDIR}/../../lang/php56

PKGNAMESUFFIX=	-sockets

.include "${MASTERDIR}/Makefile"
