# New ports collection makefile for:	hicolor-icon-theme
# Date created:        13 January 2003
# Whom:                marcus@FreeBSD.org
#
# $MidnightBSD: mports/misc/hicolor-icon-theme/Makefile,v 1.4 2007/08/24 05:13:12 laffer1 Exp $
# $FreeBSD: ports/misc/hicolor-icon-theme/Makefile,v 1.6 2004/11/21 22:13:08 kwm Exp $

PORTNAME=	hicolor-icon-theme
PORTVERSION=	0.10
CATEGORIES=	misc gnome
MASTER_SITES=	http://icon-theme.freedesktop.org/releases/

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	A high-color icon theme shell from the FreeDesktop project
LICENSE=	gpl2

USE_GNOME=	gnometarget
GNU_CONFIGURE=	yes

.include <bsd.port.mk>
