# $FreeBSD: head/multimedia/gstreamer1-plugins-x264/Makefile 391217 2015-07-03 07:02:44Z koobs $

PORTREVISION=	1
CATEGORIES=	multimedia

COMMENT=	Gstreamer x264 plugin

GST_PLUGIN=	x264
DIST=		ugly

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
