# $MidnightBSD$

PORTNAME=	ezjail
PORTVERSION=	3.4.1
CATEGORIES=	sysutils
MASTER_SITES=	http://erdgeist.org/arts/software/ezjail/

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Framework to easily create, manipulate, and run BSD jails

LICENSE=	other

USES=		tar:bzip2
FAKE_OPTS=	trueprefix

.include <bsd.port.mk>
