# $MidnightBSD$

PORTNAME=	xditview
PORTVERSION=	1.0.3
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Display ditroff output
LICENSE=	mit

XORG_CAT=	app
USE_XORG=	xt xaw

MAN1=		xditview.1

.include <bsd.port.mk>
