# $MidnightBSD: mports/mail/Makefile,v 1.9 2006/12/04 05:13:55 laffer1 Exp $
#

    COMMENT = Electronic mail utilities

    SUBDIR += addresses
    SUBDIR += dovecot
    SUBDIR += fetchmail
    SUBDIR += linux-thunderbird
    SUBDIR += msmtp
    SUBDIR += mutt
    SUBDIR += mutt-devel
    SUBDIR += p5-MIME-Types
    SUBDIR += pine-pgp-filters
    SUBDIR += pine4
    SUBDIR += spamd
    SUBDIR += squirrelmail
    SUBDIR += wmymail
    SUBDIR += wpop3d

.include <bsd.port.subdir.mk>
