# New ports collection makefile for:	xf86-video-i740
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11-drivers/xf86-video-i740/Makefile,v 1.2 2007/09/15 14:04:27 flz Exp $
# $MidnightBSD$
#

PORTNAME=	xf86-video-i740
PORTVERSION=	1.1.0
CATEGORIES=	x11-drivers

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X.Org i740 display driver
LICENSE=	x11

XORG_CAT=	driver
USE_XORG=	videoproto xextproto
MAN4=		i740.4x

.include <bsd.port.mk>
