PORTNAME=	cgi
PORTVERSION=	0.4.1
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Support for the Common Gateway Interface protocol
WWW=		https://github.com/ruby/cgi

LICENSE=	bsd2 ruby
LICENSE_COMB=	dual
LICENSE_FILE_BSD2CLAUSE=${WRKSRC}/LICENSE.txt

USES=		cpe gem

CPE_VENDOR=	ruby-lang

.include <bsd.port.mk>
