# Created by: Mathieu Arnold <m@absolight.net>

PORTNAME=	B-Keywords
PORTVERSION=	1.20
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Lists of reserved barewords and symbol names

LICENSE=	artistic gpl2
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

NO_ARCH=	yes

.include <bsd.port.mk>
