PORTNAME=	libXres
PORTVERSION=	1.2.2
CATEGORIES=	x11
DISTFILES=      ${PORTNAME}-${PORTVERSION}.tar.xz

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X Resource usage library

LICENSE=	mit

USE_XORG=	x11 xext xorgproto
INSTALL_TARGET=	install-strip
USES=		cpe xorg xorg-cat:lib tar:xz
CPE_PRODUCT=	libxres
CPE_VENDOR=	x

.include <bsd.port.mk>
