# $MidnightBSD$

PORTNAME=	libXres
PORTVERSION=	1.2.0
PORTREVISION=	1
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X Resource usage library

LICENSE=	mit

XORG_CAT=	lib
USE_XORG=	x11 xext xorgproto
INSTALL_TARGET=	install-strip
USES+=	cpe
CPE_PRODUCT=	libxres
CPE_VENDOR=	x

.include <bsd.port.mk>
