# $MidnightBSD$

PORTNAME=	gnome-common
PORTVERSION=	3.14.0
CATEGORIES=	devel
MASTER_SITES=	GNOME
DIST_SUBDIR=	gnome2

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Common automake macros for GNOME 3

LICENSE=	gpl2
LICENSE_FILE=	${WRKSRC}/COPYING

USES=		gmake pkgconfig tar:xz
GNU_CONFIGURE=	yes

.include <bsd.port.mk>
