# New ports collection makefile for:	php5-tokenizer
# Date created:			7 Jul 2004
# Whom:				Alex Dupre <ale@FreeBSD.org>
#
# $MidnightBSD$
# $FreeBSD: ports/devel/php5-tokenizer/Makefile,v 1.1 2004/07/19 09:08:13 ale Exp $
#

CATEGORIES=	devel

MASTERDIR=	${.CURDIR}/../../lang/php5

PKGNAMESUFFIX=	-tokenizer

.include "${MASTERDIR}/Makefile"
