# New ports collection makefile for:   libXpm
# Date Created:			25 Jan, 2003
# Whom:				Eric Anholt <anholt@FreeBSD.org>
#
# $FreeBSD: ports/x11/libXpm/Makefile,v 1.19 2007/09/13 19:44:59 flz Exp $
# $MidnightBSD$
#

PORTNAME=	libXpm
PORTVERSION=	3.5.7
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X Pixmap library
LICENSE=	x11

XORG_CAT=	lib
USE_XORG=	xproto x11 xext xextproto xt

MAN1=		cxpm.1 sxpm.1

.include <bsd.port.mk>
