PORTNAME=	hledger-ui
DISTVERSION=	1.52.4
CATEGORIES=	finance haskell

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	UI for hledger, the accounting software package
WWW=		https://hledger.org/ \
		https://hackage.haskell.org/package/hledger-ui

LICENSE=	gpl3
LICENSE_FILE=	${WRKSRC}/LICENSE

LIB_DEPENDS=	libinotify.so:devel/libinotify

USES=		cabal

.include <bsd.port.mk>
