# New ports collection makefile for:	p5-threads
# Date created:		2006-07-22
# Whom:			Gea-Suan Lin <gslin@gslin.org>
#
# $MidnightBSD: mports/devel/p5-threads/Makefile,v 1.4 2008/07/19 18:07:46 laffer1 Exp $
# $FreeBSD: ports/devel/p5-threads/Makefile,v 1.14 2007/06/09 02:35:37 clsung Exp $
#

PORTNAME=	threads
PORTVERSION=	1.75
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	../../authors/id/J/JD/JDHEDDEN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Perl interpreter-based threads
LICENSE=	perl

PERL_CONFIGURE=	yes

MAN3=		threads.3

.include <bsd.port.mk>
