PORTNAME=	xf86-video-neomagic
PORTVERSION=	1.3.0
PORTREVISION=	2
CATEGORIES=	x11-drivers

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X.Org neomagic display driver
WWW=		https://www.x.org/

USES=		xorg-cat:driver

.include <bsd.port.mk>
