# Created by: Pawel Worach

PORTNAME=	font-screen-cyrillic
PORTVERSION=	1.0.4
PORTREVISION=	4
CATEGORIES=	x11-fonts

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X.Org Screen Cyrillic font

LICENSE=	mit

USES=		xorg-cat:font

.include <bsd.port.mk>
