# $MidnightBSD$
# $FreeBSD: ports/www/p5-HTML-Strip/Makefile,v 1.8 2008/04/17 14:29:59 araujo Exp $

PORTNAME=	HTML-Strip
PORTVERSION=	1.06
CATEGORIES=	www perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Perl5 module for strip HTML tag
LICENSE=	perl

PERL_CONFIGURE=	yes

MAN3=		HTML::Strip.3

.include <bsd.port.mk>
