# $MidnightBSD$

PORTNAME=	PAR-Dist
PORTVERSION=	0.49
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Create and manipulate PAR distributions

LICENSE=	artistic gpl
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

PERL_CONFIGURE=	yes

.include <bsd.port.mk>
