# $MidnightBSD: mports/x11-themes/xcursor-themes/Makefile,v 1.2 2009/12/13 21:01:04 laffer1 Exp $
#

PORTNAME=	xcursor-themes
PORTVERSION=	1.0.2
PORTREVISION=	1
CATEGORIES=	x11-themes

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X.org cursors themes
LICENSE=	unknown

BUILD_DEPENDS=	xcursorgen:${PORTSDIR}/x11/xcursorgen

USE_XORG=	xextproto

XORG_CAT=	data

.include <bsd.port.mk>
