# Created by: Zach Thompson <hideo@lastamericanempire.com>

PORTNAME=	Test-Strict
PORTVERSION=	0.52
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Test and report on use strict/warnings coverage
WWW=		https://metacpan.org/release/Test-Strict

LICENSE=	artistic gpl
LICENSE_COMB=	dual
LICENSE_FILE=	${WRKSRC}/LICENSE

TEST_DEPENDS=	p5-IO-Stringy>=0:devel/p5-IO-Stringy

NO_ARCH=	yes
USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
