# $MidnightBSD$
# $FreeBSD: head/devel/py-setuptools_scm/Makefile 423782 2016-10-11 16:54:50Z wg $

PORTNAME=	setuptools_scm
PORTVERSION=	1.17.0
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Setuptools plugin to manage your versions by scm tags

LICENSE=	mit

USES?=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
