PORTNAME=	xf86-video-tdfx
PORTVERSION=	1.5.0
PORTREVISION=	2
CATEGORIES=	x11-drivers

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X.Org tdfx display driver
WWW=		https://www.x.org/

LICENSE=	mit

USES=		gl xorg-cat:driver
USE_GL=		gl

.include <bsd.port.mk>
