Avoid using vendored OpenSSL.

Dependency chain:

xwin -> native-tls -> openssl-sys -> openssl-src

--- cargo-crates/xwin-0.3.1/Cargo.toml.orig	1970-01-01 00:00:01 UTC
+++ cargo-crates/xwin-0.3.1/Cargo.toml
@@ -142,6 +142,5 @@ native-tls = [
 default = ["rustls-tls"]
 native-tls = [
     "ureq/native-tls",
-    "native-tls-crate/vendored",
 ]
 rustls-tls = ["ureq/tls"]
