# $MidnightBSD: mports/archivers/p5-Compress-Raw-Bzip2/Makefile,v 1.7 2011/09/18 20:11:18 laffer1 Exp $

PORTNAME=	Compress-Raw-Bzip2
PORTVERSION=	2.060
CATEGORIES=	archivers perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:PMQS
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Low-Level Interface to bzip2 compression library
LICENSE=	perl

PERL_CONFIGURE=	YES

MAN3=		Compress::Raw::Bzip2.3

.include <bsd.port.mk>
