# $MidnightBSD: mports/ports-mgmt/Makefile,v 1.5 2007/10/24 18:55:02 laffer1 Exp $
#

   COMMENT = Ports for managing, installing and developing MidnightBSD ports and packages

   SUBDIR += magus-utils
   SUBDIR += pib
   SUBDIR += pkg_search
   SUBDIR += portlint
   SUBDIR += portsearch
   SUBDIR += portupgrade
   SUBDIR += qtpkg

.include <bsd.port.subdir.mk>
