# New ports collection makefile for:    font-arabic-misc
# Date created:		28 Aug 2005
# Whom:			Pawel Worach
#
# $FreeBSD: ports/x11-fonts/font-arabic-misc/Makefile,v 1.1 2007/05/19 20:29:11 flz Exp $
# $MidnightBSD$
#

PORTNAME=	font-arabic-misc
PORTVERSION=	1.0.0
CATEGORIES=	x11-fonts

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X.Org miscellaneous Arabic fonts
LICENSE=	x11

XORG_CAT=	font

.include <bsd.port.mk>
