PORTNAME=	right_http_connection
PORTVERSION=	1.5.1
CATEGORIES=	net rubygems
MASTER_SITES=	RG

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Persistent HTTP/HTTPS connections with error retries
WWW=		https://github.com/rightscale/right_http_connection

LICENSE=	mit

USES=		gem

NO_ARCH=	yes

.include <bsd.port.mk>
