PORTNAME=	Rdpack
DISTVERSION=	2.6.4
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Update and Manipulate Rd Documentation Objects
WWW=		https://cran.r-project.org/web/packages/Rdpack/

LICENSE=	gpl2+
RUN_DEPENDS=	R-cran-rbibutils>=1.3:textproc/R-cran-rbibutils

USES=		cran:auto-plist

.include <bsd.port.mk>
