# Created by: Yuri Victorovich <yuri@rawbw.com>

PORTNAME=	hexdump
PORTVERSION=	3.3
CATEGORIES=	textproc python
MASTER_SITES=	PYPI
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Print binary in hex format

LICENSE=	publicdom

USES=		python zip
USE_PYTHON=	autoplist distutils

NO_ARCH=	yes
NO_WRKSUBDIR=	yes

.include <bsd.port.mk>
