# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/sysutils/php70-fileinfo/Makefile 408932 2016-02-15 14:34:26Z miwi $
# $MidnightBSD$

CATEGORIES=	sysutils

MASTERDIR=	${.CURDIR}/../../lang/php70

PKGNAMESUFFIX=	-fileinfo

.include "${MASTERDIR}/Makefile"
