# $MidnightBSD: mports/x11/xf86rushproto/Makefile,v 1.2 2012/03/03 01:52:55 laffer1 Exp $
#

PORTNAME=	xf86rushproto
PORTVERSION=	1.1.2
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	XFree86-Rush extension headers
LICENSE=	mit

XORG_CAT=	proto

.include <bsd.port.mk>
