PORTNAME=	abind
DISTVERSION=	1.4-8
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Combine Multidimensional Arrays
WWW=		https://cran.r-project.org/web/packages/abind/

LICENSE=	mit

USES=		cran:auto-plist

.include <bsd.port.mk>
