PORTNAME=	http-form_data
PORTVERSION=	2.3.0
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Build form data request bodies
WWW=		https://github.com/httprb/form_data

LICENSE=	mit
LICENSE_FILE=	${WRKSRC}/LICENSE.txt

USES=		gem

NO_ARCH=	yes

.include <bsd.port.mk>
