# New ports collection makefile for:   subcalc
# Date created:         24 August 2003
# Whom:                 Chris S.J. Peron <maneo@bsdpro.com>
#
# $FreeBSD: ports/net-mgmt/subcalc/Makefile,v 1.6 2004/12/10 05:50:16 csjp Exp $
# $MidnightBSD$
#

PORTNAME=	subcalc
PORTVERSION=	1.1
CATEGORIES=	net-mgmt ipv6
MASTER_SITES=	http://www.seccuris.com/documents/downloads/
MASTER_SITE_SUBDIR=	subcalc

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Advanced IP/IPv6 subnet calculation and discovery
LICENSE=	bsd3

MAN1=	subcalc.1
MANCOMPRESSED=	yes
PLIST_FILES=	bin/subcalc

.include <bsd.port.mk>
