# $MidnightBSD: mports/devel/Makefile,v 1.11 2006/09/20 16:42:35 laffer1 Exp $
# $FreeBSD: ports/devel/Makefile,v 1.2449 2006/09/11 18:06:11 vd Exp $
#

    COMMENT = Development utilities

    SUBDIR += autoconf213
    SUBDIR += automake14
    SUBDIR += bison
    SUBDIR += desktop-file-utils
    SUBDIR += ffcall
    SUBDIR += gettext
    SUBDIR += glib20
    SUBDIR += gmake
    SUBDIR += gnu-autoconf
    SUBDIR += gnu-automake
    SUBDIR += imake-6
    SUBDIR += libIDL
    SUBDIR += libtool15
    SUBDIR += m4
    SUBDIR += nspr
    SUBIDR += p5-Locale-gettext
    SUBDIR += pcre
    SUBDIR += pkg-config
    SUBDIR += pmk
    SUBDIR += popt

.include <bsd.port.subdir.mk>
