PORTNAME=	xf86-video-cirrus
PORTVERSION=	1.5.3
PORTREVISION=	4
CATEGORIES=	x11-drivers

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X.Org cirrus display driver

LICENSE=	mit

USES=		xorg-cat:driver

.include <bsd.port.mk>
