PORTNAME=	xf86-video-cirrus
PORTVERSION=	1.5.3
CATEGORIES=	x11-drivers

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X.Org cirrus display driver

LICENSE=	mit

XORG_CAT=	driver
USE_XORG=	xorgproto

.include <bsd.port.mk>
