# $MidnightBSD: mports/german/Makefile,v 1.8 2008/06/13 02:35:44 laffer1 Exp $
#

    COMMENT = German support

    SUBDIR += acroread
    SUBDIR += acroread8
    SUBDIR += alt-aspell
    SUBDIR += aspell
    SUBDIR += dict
    SUBDIR += ispell
    SUBDIR += ispell-alt
    SUBDIR += ispell-neu
    SUBDIR += kde-i18n-de
    SUBDIR += manpages
    SUBDIR += phone
    SUBDIR += selfhtml
    SUBDIR += staroffice70

.include <bsd.port.subdir.mk>
