PORTNAME=	gems
PORTVERSION=	1.3.0
PORTREVISION=	1
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Ruby wrapper for the RubyGems.org API
WWW=		https://github.com/rubygems/gems

LICENSE=	mit
LICENSE_FILE=	${WRKSRC}/LICENSE.md

USES=		gem
USES+=	cpe
CPE_PRODUCT=	rubygems
CPE_VENDOR=	rubygems

NO_ARCH=	yes

.include <bsd.port.mk>
