# $MidnightBSD$

PORTNAME=	Math-Round
PORTVERSION=	0.06
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Perl extension for rounding numbers
LICENSE=	perl

PERL_CONFIGURE=	yes

MAKE_JOBS_SAFE=	yes

MAN3=		Math::Round.3

.include <bsd.port.mk>
