--- Cargo.toml.orig	2025-12-24 14:16:03 UTC
+++ Cargo.toml
@@ -28 +28 @@
-mdns-sd = "0.17"
+mdns-sd = "0.20.3"
@@ -48,2 +47,0 @@
-glycin = { package = "libglycin-rebind", version = "0.0.1" }
-glycin-gtk4 = { package = "libglycin-gtk4-rebind", version = "0.0.1" }
@@ -50,2 +48,2 @@
-gstreamer = { version = "0.24" }
-gstreamer-audio = { version = "0.24" }
+gstreamer = { version = "=0.24.4" }
+gstreamer-audio = { version = "=0.24.4" }
@@ -53,0 +52,9 @@
+
+[target.'cfg(target_os = "linux")'.dependencies]
+glycin = { package = "libglycin-rebind", version = "0.0.1" }
+glycin-gtk4 = { package = "libglycin-gtk4-rebind", version = "0.0.1" }
+
+[profile.release]
+opt-level = 2
+debug = false
+strip = "symbols"
