# New ports collection Makefile for:	xdesktopwaves
# Date Created:				13 April 2007
# Whom:					wintellect <wintellect@bsdnexus.com>
#
# $MidnightBSD: mports/x11/xdesktopwaves/Makefile,v 1.3 2010/01/01 17:23:44 laffer1 Exp $
#

PORTNAME=	xdesktopwaves
PORTVERSION=	1.3
PORTREVISION=	3
CATEGORIES=	x11
MASTER_SITES=	SF

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Sets the background of your X desktop under water
LICENSE=	gpl2

USE_XORG=	x11 xext

MAN1=		xdesktopwaves.1

.include <bsd.port.mk>

