# $FreeBSD: head/devel/php74-gettext/Makefile 512406 2019-09-20 12:21:11Z tz $

CATEGORIES=	devel

MASTERDIR=	${.CURDIR}/../../lang/php74

PKGNAMESUFFIX=	-gettext

NO_TEST=	yes

.include "${MASTERDIR}/Makefile"
