# New ports collection makefile for:	xmodmap
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11/xmodmap/Makefile,v 1.2 2007/09/13 19:45:04 flz Exp $
# $MidnightBSD$
#

PORTNAME=	xmodmap
PORTVERSION=	1.0.3
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Utility for modifying keymaps and pointer button mappings in X
LICENSE=	x11

XORG_CAT=	app
USE_XORG=	x11

PLIST_FILES=	bin/xmodmap

MAN1=		xmodmap.1

.include <bsd.port.mk>
