# $MidnightBSD$
# $FreeBSD: head/textproc/p5-Regexp-Common/Makefile 373448 2014-11-26 13:08:24Z mat $

PORTNAME=	Regexp-Common
PORTVERSION=	2013031301
PORTREVISION=	1
CATEGORIES=	textproc perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Regexp::Common - Provide commonly requested regular expressions

LICENSE=	artistic mit bsd3
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure
PERL_CONFIGURE=	yes

.include <bsd.port.mk>
