# $MidnightBSD$
# $FreeBSD: head/www/php71-tidy/Makefile 432324 2017-01-24 11:54:20Z tz $

CATEGORIES=	www

MASTERDIR=	${.CURDIR}/../../lang/php71

PKGNAMESUFFIX=	-tidy

.include "${MASTERDIR}/Makefile"
