# $MidnightBSD: mports/comms/Makefile,v 1.20 2008/08/17 22:42:29 laffer1 Exp $
#

    COMMENT = Communication utilities

    SUBDIR += acfax
    SUBDIR += aldo
    SUBDIR += asmodem
    SUBDIR += atslog
    SUBDIR += bforce
    SUBDIR += bforce-kst
    SUBDIR += cdr_read
    SUBDIR += chu
    SUBDIR += comserv
    SUBDIR += efax
    SUBDIR += kermit
    SUBDIR += kmobiletools
    SUBDIR += libirman
    SUBDIR += libticables
    SUBDIR += lirc
    SUBDIR += lrzsz
    SUBDIR += ltmdm
    SUBDIR += minicom
    SUBDIR += p5-SMS-Send
    SUBDIR += pr
    SUBDIR += qfaxreader
    SUBDIR += tits

.include <bsd.port.subdir.mk>
