# $MidnightBSD: mports/comms/Makefile,v 1.6 2007/06/27 01:14:31 laffer1 Exp $
#

    COMMENT = Communication utilities

    SUBDIR += libirman
    SUBDIR += libticables
    SUBDIR += lirc
    SUBDIR += lrzsz
    SUBDIR += ltmdm
    SUBDIR += minicom
    SUBDIR += pr
    SUBDIR += tits

.include <bsd.port.subdir.mk>
