# $MidnightBSD: mports/comms/Makefile,v 1.18 2008/08/17 22:04:59 laffer1 Exp $
#

    COMMENT = Communication utilities

    SUBDIR += acfax
    SUBDIR += aldo
    SUBDIR += asmodem
    SUBDIR += atslog
    SUBDIR += bforce
    SUBDIR += bforce-kst
    SUBDIR += cdr_read
    SUBDIR += chu
    SUBDIR += comserv
    SUBDIR += efax
    SUBDIR += kermit
    SUBDIR += kmobiletools
    SUBDIR += libirman
    SUBDIR += libticables
    SUBDIR += lirc
    SUBDIR += lrzsz
    SUBDIR += ltmdm
    SUBDIR += minicom
    SUBDIR += pr
    SUBDIR += tits

.include <bsd.port.subdir.mk>
