# New ports collection makefile for:	php5-xmlreader
# Date created:			26 Nov 2005
# Whom:				Alex Dupre <ale@FreeBSD.org>
#
# $MidnightBSD$
# $FreeBSD: ports/textproc/php5-xmlreader/Makefile,v 1.1 2005/12/09 19:45:41 ale Exp $
#

CATEGORIES=	textproc

MASTERDIR=	${.CURDIR}/../../lang/php5

PKGNAMESUFFIX=	-xmlreader

.include "${MASTERDIR}/Makefile"
