PORTNAME=	Test-MockRandom
PORTVERSION=	1.01
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Replaces random number generation with non-random number generation

LICENSE=	Apache-2.0

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
