# $MidnightBSD$

PORTNAME=	libglade2
PORTVERSION=	2.6.4
CATEGORIES=	devel linux

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	GNOME glade library (Linux CentOS ${LINUX_DIST_VER})

LICENSE=	lgpl

DESCR=		${.CURDIR}/../${PORTNAME}/pkg-descr
RPMVERSION=	3.1.el6
USES=		linux:c6
USE_LDCONFIG=	yes
USE_LINUX_RPM=	yes

OPTIONS_DEFINE=	DOCS

.include <bsd.port.mk>
