PORTNAME=	citrus
PORTVERSION=	3.0.2
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Parsing Expressions for Ruby
WWW=		https://mjackson.github.io/citrus

BUILD_DEPENDS=	rubygem-rake>=0:devel/rubygem-rake

NO_ARCH=	yes
USES=		gem

.include <bsd.port.mk>
