# $MidnightBSD: mports/x11-themes/Makefile,v 1.12 2008/06/14 02:08:53 laffer1 Exp $
#
    COMMENT = X11 themes

    SUBDIR += clearlooks
    SUBDIR += clearlooks-metacity
    SUBDIR += clearlooks-themes
    SUBDIR += etoile-azbackground
    SUBDIR += etoile-camaelon
    SUBDIR += etoile-etoilemenus
    SUBDIR += etoile-iconkit
    SUBDIR += etoile-wildmenus
    SUBDIR += gnome-backgrounds
    SUBDIR += gnome-themes
    SUBDIR += gtk-engines2
    SUBDIR += icon-naming-utils
    SUBDIR += irssi-themes
    SUBDIR += kdeartwork3
    SUBDIR += linux-hicolor-icon-theme
    SUBDIR += xcursor-themes
.include <bsd.port.subdir.mk>
