# $MidnightBSD: mports/x11-themes/Makefile,v 1.20 2009/12/13 21:01:03 laffer1 Exp $
#
    COMMENT = X11 themes

SUBDIR += clearlooks
SUBDIR += clearlooks-metacity
SUBDIR += clearlooks-themes
SUBDIR += etoile-azbackground
SUBDIR += etoile-camaelon
SUBDIR += etoile-etoilemenus
SUBDIR += etoile-iconkit
SUBDIR += etoile-wildmenus
SUBDIR += gnome-backgrounds
SUBDIR += gnome-themes
SUBDIR += gtk-engines2
SUBDIR += gtk-xfce-engine
SUBDIR += icon-naming-utils
SUBDIR += irssi-themes
SUBDIR += kdeartwork3
SUBDIR += kdeartwork4
SUBDIR += linux-gtk-bluecurve-theme
SUBDIR += linux-hicolor-icon-theme
SUBDIR += midnightbsd-backgrounds
SUBDIR += ubuntulooks
SUBDIR += xcursor-themes

.include <bsd.port.subdir.mk>
