PORTNAME=	kiwisolver
PORTVERSION=	1.1.0
PORTEPOCH=	1
CATEGORIES=	math python
MASTER_SITES=	PYPI
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Fast implementation of the Cassowary constraint solver

LICENSE=	bsd3

USES=		compiler:c++11-lang python
USE_PYTHON=	autoplist concurrent distutils

.include <bsd.port.mk>
