# $MidnightBSD: mports/multimedia/Makefile,v 1.9 2006/10/05 01:12:45 laffer1 Exp $
#

    COMMENT = Multimedia software

    SUBDIR += libdts
    SUBDIR += libdvdcss
    SUBDIR += libdvdread
    SUBDIR += libfame
    SUBDIR += libtheora
    SUBDIR += libxine
    SUBDIR += linux-realplayer
    SUBDIR += smpeg
    SUBDIR += vcdimager
    SUBDIR += win32-codecs
    SUBDIR += xmms
    SUBDIR += xmms-skins

.include <bsd.port.subdir.mk>
