# $MidnightBSD: mports/multimedia/Makefile,v 1.14 2006/12/13 20:12:24 laffer1 Exp $
#

    COMMENT = Multimedia software

    SUBDIR += libdts
    SUBDIR += libdvdcss
    SUBDIR += libdvdread
    SUBDIR += libfame
    SUBDIR += libmpeg2
    SUBDIR += libtheora
    SUBDIR += libxine
    SUBDIR += linux-realplayer
    SUBDIR += mplayer
    SUBDIR += mplayer-skins
    SUBDIR += ogle
    SUBDIR += smpeg
    SUBDIR += vcdimager
    SUBDIR += win32-codecs
    SUBDIR += xine
    SUBDIR += xmms
    SUBDIR += xmms-skins
    SUBDIR += xvid

.include <bsd.port.subdir.mk>
