# Created by: Aaron Dalton <aaron@FreeBSD.org>

PORTNAME=	Font-TTFMetrics
PORTVERSION=	0.1
CATEGORIES=	x11-fonts perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Parser for the TTF file

LICENSE=	artistic gpl
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
