# New ports collection Makefile for:	xdesktopwaves
# Date Created:				13 April 2007
# Whom:					wintellect <wintellect@bsdnexus.com>
#
# $MidnightBSD: mports/x11/xdesktopwaves/Makefile,v 1.1 2007/04/13 13:49:05 wintellect Exp $
#

PORTNAME=	xdesktopwaves
PORTVERSION=	1.3
PORTREVISION=	1
CATEGORIES=	x11
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE}
MASTER_SITE_SUBDIR=	${PORTNAME}

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Sets the background of your X desktop under water
LICENSE=	gpl2

USE_XLIB=	yes

MAN1=		xdesktopwaves.1

.include <bsd.port.mk>

