# $MidnightBSD: mports/x11/xeyes/Makefile,v 1.3 2012/03/03 01:52:55 laffer1 Exp $

PORTNAME=	xeyes
PORTVERSION=	1.1.1
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	A follow the mouse X demo
LICENSE=	mit

XORG_CAT=	app
USE_XORG=	x11 xt xext xmu xrender

PLIST_FILES=	bin/xeyes

MAN1=		xeyes.1

.include <bsd.port.mk>
