# $MidnightBSD: mports/x11-drivers/xf86-input-void/Makefile,v 1.1 2007/10/12 00:18:53 ctriv Exp $

PORTNAME=	xf86-input-void
PORTVERSION=	1.1.1
PORTREVISION=	1
CATEGORIES=	x11-drivers

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X.Org void input driver
LICENSE=	x11

XORG_CAT=	driver
MAN4=		void.4x

.include <bsd.port.mk>
