PORTNAME=	Encode-ISO2022
PORTVERSION=	0.04
CATEGORIES=	japanese perl5
MASTER_SITES=	CPAN

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Perl extension for ISO/IEC 2022 character encoding scheme
WWW=		https://metacpan.org/release/Encode-ISO2022

LICENSE=	artistic gpl+
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.pre.mk>

PKGNAMEPREFIX:=	${PKGNAMEPREFIX}p5-

.include <bsd.port.post.mk>
