# $MidnightBSD$

PORTNAME=	Net-CIDR
PORTVERSION=	0.17
CATEGORIES=	net-mgmt perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@MidnightSD.org
COMMENT=	Perl module to manipulate IPv4/IPv6 netblocks in CIDR notation
LICENSE=	perl

PERL_CONFIGURE=	yes

MAN3=		Net::CIDR.3

.include <bsd.port.mk>
