# $MidnightBSD: mports/devel/Makefile,v 1.38 2006/10/31 20:27:40 laffer1 Exp $
#

    COMMENT = Development utilities

    SUBDIR += ORBit
    SUBDIR += apache-ant
    SUBDIR += autoconf213
    SUBDIR += autoconf253
    SUBDIR += autoconf259
    SUBDIR += automake14
    SUBDIR += automake15
    SUBDIR += automake19
    SUBDIR += bison
    SUBDIR += desktop-file-utils
    SUBDIR += ffcall
    SUBDIR += gettext
    SUBDIR += glib12
    SUBDIR += glib20
    SUBDIR += glibmm
    SUBDIR += gmake
    SUBDIR += gnu-autoconf
    SUBDIR += gnu-automake
    SUBDIR += gnustep
    SUBDIR += gnustep-make
    SUBDIR += gorm
    SUBDIR += icu
    SUBDIR += imake-6
    SUBDIR += libIDL
    SUBDIR += libltdl15
    SUBDIR += libsigc++
    SUBDIR += libsigc++12
    SUBDIR += libsigc++20
    SUBDIR += libslang
    SUBDIR += libtool15
    SUBDIR += linux-allegro
    SUBDIR += linux-glib2
    SUBDIR += linux-libglade
    SUBDIR += linux-sdl12
    SUBDIR += linuxthreads
    SUBDIR += m4
    SUBDIR += nasm
    SUBDIR += ncurses
    SUBDIR += nspr
    SUBIDR += p5-Locale-gettext
    SUBDIR += p5-Storable
    SUBDIR += pcre
    SUBDIR += pcre-utf8
    SUBDIR += pkg-config
    SUBDIR += pmk
    SUBDIR += popt
    SUBDIR += portlint
    SUBDIR += projectcenter.app
    SUBDIR += sdl12
    SUBDIR += silc-toolkit
    SUBDIR += splint
    SUBDIR += t1lib
    SUBDIR += zthread
    SUBDIR += zziplib

.include <bsd.port.subdir.mk>
