# New ports collection makefile for:	php5-exif
# Date created:			7 Jul 2004
# Whom:				Alex Dupre <ale@FreeBSD.org>
#
# $MidnightBSD$
# $FreeBSD: ports/graphics/php5-exif/Makefile,v 1.1 2004/07/19 09:10:26 ale Exp $
#

CATEGORIES=	graphics

MASTERDIR=	${.CURDIR}/../../lang/php5

PKGNAMESUFFIX=	-exif

.include "${MASTERDIR}/Makefile"
