PORTNAME=	tomlrb
PORTVERSION=	2.0.4
CATEGORIES=	textproc rubygems
MASTER_SITES=	RG

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Racc-based TOML parser
WWW=		https://github.com/fbernier/tomlrb

LICENSE=	mit
LICENSE_FILE=	${WRKSRC}/LICENSE.txt

USES=		gem

NO_ARCH=	yes

.include <bsd.port.mk>
