# New ports collection makefile for:	xtrans
# Date Created:				08 Aug 2005
# Whom:					Dejan Lesjak <lesi@FreeBSD.org>
#
# $FreeBSD: ports/x11/xtrans/Makefile,v 1.2 2007/09/13 19:45:07 flz Exp $
# $MidnightBSD$
#

PORTNAME=	xtrans
PORTVERSION=	1.0.4
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Abstract network code for X
LICENSE=	x11

XORG_CAT=	lib

.include <bsd.port.mk>
