# $MidnightBSD: mports/x11/libXpm/Makefile,v 1.2 2012/03/03 01:52:53 laffer1 Exp $

PORTNAME=	libXpm
PORTVERSION=	3.5.10
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X Pixmap library
LICENSE=	mit

XORG_CAT=	lib
USE_XORG=	xproto x11 xext xextproto xt

MAN1=		cxpm.1 sxpm.1

.include <bsd.port.mk>
