--- pyproject.toml.orig	2024-02-05 09:16:01 UTC
+++ pyproject.toml
@@ -1,5 +1,5 @@
 [build-system]
-requires = ["setuptools >= 61.0", "setuptools-scm>=8.0"]
+requires = ["setuptools >= 61.0", "setuptools-scm>=6.0"]
 build-backend = "setuptools.build_meta"
 
 [tool.setuptools_scm]
