# $MidnightBSD$

PORTNAME=	libxkbui
PORTVERSION=	1.0.2
PORTREVISION=	3
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	The xkbui library

LICENSE=	mit

XORG_CAT=	lib
USE_XORG=	x11 xt xkbfile xorgproto

.include <bsd.port.mk>
