# $MidnightBSD$
# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/databases/php55-sqlite3/Makefile 389655 2015-06-14 20:23:09Z ale $

CATEGORIES=	databases

MASTERDIR=	${.CURDIR}/../../lang/php55

PKGNAMESUFFIX=	-sqlite3

.include "${MASTERDIR}/Makefile"
