# $MidnightBSD: mports/accessibility/Makefile,v 1.3 2006/09/23 22:41:47 laffer1 Exp $
# $FreeBSD: ports/accessibility/Makefile,v 1.11 2006/05/28 00:57:23 mezz Exp $
#

    COMMENT = Ports to help disabled users

    SUBDIR += atk
    SUBDIR += kdeaccessibility
    SUBDIR += linux-atk

.include <bsd.port.subdir.mk>
