# $MidnightBSD: mports/accessibility/Makefile,v 1.13 2008/01/04 21:47:22 laffer1 Exp $
#
    COMMENT = Ports to help disabled users

    SUBDIR += at-poke
    SUBDIR += at-spi
    SUBDIR += at-spi-reference
    SUBDIR += atk
    SUBDIR += atk-reference
    SUBDIR += gail
    SUBDIR += gail-reference
    SUBDIR += gnome-mag
    SUBDIR += gnome-speech
    SUBDIR += gok
    SUBDIR += kdeaccessibility
    SUBDIR += linux-atk
    SUBDIR += orca
    SUBDIR += qt4-accessible

.include <bsd.port.subdir.mk>
