--- xed/xed-plugins-engine.c.orig
+++ xed/xed-plugins-engine.c
@@ -35 +35 @@
-#if PYGOBJECT_MAJOR_VERSION > 3 || (PYGOBJECT_MAJOR_VERSION == 3 && PYGOBJECT_MINOR_VERSION > 50)
+#if GLIB_CHECK_VERSION(2, 80, 0)
@@ -74 +74 @@
-#if PYGOBJECT_MAJOR_VERSION > 3 || (PYGOBJECT_MAJOR_VERSION == 3 && PYGOBJECT_MINOR_VERSION > 50)
+#if GLIB_CHECK_VERSION(2, 80, 0)
@@ -87 +87 @@
-#if PYGOBJECT_MAJOR_VERSION > 3 || (PYGOBJECT_MAJOR_VERSION == 3 && PYGOBJECT_MINOR_VERSION > 50)
+#if GLIB_CHECK_VERSION(2, 80, 0)
@@ -98 +98 @@
-#if PYGOBJECT_MAJOR_VERSION > 3 || (PYGOBJECT_MAJOR_VERSION == 3 && PYGOBJECT_MINOR_VERSION > 50)
+#if GLIB_CHECK_VERSION(2, 80, 0)
