# $MidnightBSD$

PORTNAME=	xf86-video-r128
PORTVERSION=	6.11.0
PORTREVISION=	1
CATEGORIES=	x11-drivers

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X.Org r128 display driver

LICENSE=	mit
LICENSE_FILE=	${WRKSRC}/COPYING

USE_GL=		gl
XORG_CAT=	driver

.include <bsd.port.mk>
