# $MidnightBSD: mports/x11/xcb/Makefile,v 1.5 2009/09/20 03:01:10 laffer1 Exp $

PORTNAME=	xcb
PORTVERSION=	2.4
PORTREVISION=	1
CATEGORIES=	x11
MASTER_SITES=	http://www.goof.com/pcg/marc/data/

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	A tool for managing x11 cut-buffers
LICENSE=	other

USE_IMAKE=	yes
USE_XORG=	ice sm x11 xaw xext xmu xt
MAN1=		xcb.1

.include <bsd.port.mk>
