# Created by: Palle Girgensohn <girgen@pingpong.net>
# $FreeBSD: head/databases/postgresql95-docs/Makefile 405482 2016-01-07 19:58:47Z girgen $

WANT_PGSQL_VER=9.5

.include "${.CURDIR}/../postgresql91-docs/Makefile"
