# $MidnightBSD: mports/converters/Makefile,v 1.3 2006/11/24 22:33:08 laffer1 Exp $
#

    COMMENT = Character code converters

    SUBDIR += libiconv
    SUBDIR += p5-MIME-Base64
    SUBDIR += php5-mbstring
    SUBDIR += unix2dos

.include <bsd.port.subdir.mk>
