# $MidnightBSD: mports/converters/Makefile,v 1.25 2011/05/13 13:05:58 laffer1 Exp $

COMMENT = Character code converters

SUBDIR += fribidi
SUBDIR += libiconv
SUBDIR += mpack
SUBDIR += p5-Convert-ASN1
SUBDIR += p5-Convert-BinHex
SUBDIR += p5-Encode
SUBDIR += p5-Encode-Detect
SUBDIR += p5-Encode-Locale
SUBDIR += p5-JSON
SUBDIR += p5-JSON-Any
SUBDIR += p5-JSON-XS
SUBDIR += p5-JSON1
SUBDIR += p5-Jcode
SUBDIR += p5-MIME-Base32
SUBDIR += p5-MIME-Base64
SUBDIR += p5-Text-Iconv
SUBDIR += p5-Unicode-Map
SUBDIR += p5-Unicode-Map8
SUBDIR += p5-Unicode-MapUTF8
SUBDIR += p5-Unicode-String
SUBDIR += pecl-fribidi
SUBDIR += php5-iconv
SUBDIR += php5-mbstring
SUBDIR += php5-recode
SUBDIR += psiconv
SUBDIR += recode
SUBDIR += ruby-dump.rb
SUBDIR += ruby-iconv
SUBDIR += unix2dos
SUBDIR += uulib

.include <bsd.port.subdir.mk>
