# New ports collection makefile for:	xkill
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11/xkill/Makefile,v 1.1 2007/05/19 20:27:58 flz Exp $
# $MidnightBSD$
#

PORTNAME=	xkill
PORTVERSION=	1.0.1
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Utility for killing a client by its X resource
LICENSE=	x11

XORG_CAT=	app
USE_XORG=	x11 xmuu

PLIST_FILES=	bin/xkill

MAN1=		xkill.1

.include <bsd.port.mk>
