PORTNAME=	fastimage
PORTVERSION=	2.4.0
CATEGORIES=	graphics rubygems
MASTER_SITES=	RG

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	FastImage finds the size or type of an image
WWW=		https://github.com/sdsykes/fastimage

LICENSE=	mit
LICENSE_FILE=	${WRKSRC}/MIT-LICENSE

USES=		gem

NO_ARCH=	yes

.include <bsd.port.mk>
