# $MidnightBSD: mports/devel/p5-AppConfig/Makefile,v 1.2 2008/04/29 04:24:01 laffer1 Exp $

PORTNAME=	AppConfig
PORTVERSION=	1.66
CATEGORIES=	devel perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	A Perl module for reading configuration files
LICENSE=	perl

PERL_CONFIGURE=	YES

MAN3=		AppConfig.3 \
		AppConfig::Args.3 \
		AppConfig::CGI.3 \
		AppConfig::File.3 \
		AppConfig::Getopt.3 \
		AppConfig::State.3 \
		AppConfig::Sys.3

.include <bsd.port.mk>
