# $MidnightBSD: mports/textproc/Makefile,v 1.6 2006/09/22 23:56:45 laffer1 Exp $
# $FreeBSD: ports/textproc/Makefile,v 1.1058 2006/09/12 21:11:30 miwi Exp $
#

    COMMENT = Text processing utilities (does not include desktop publishing)

    SUBDIR += aspell
    SUBDIR += expat2
    SUBDIR += intltool
    SUBDIR += libxml2
    SUBDIR += libxslt
    SUBDIR += linux-expat
    SUBDIR += p5-XML-Parser

.include <bsd.port.subdir.mk>
