# $MidnightBSD: mports/textproc/Makefile,v 1.4 2006/09/20 03:56:35 archite Exp $
# $FreeBSD: ports/textproc/Makefile,v 1.1058 2006/09/12 21:11:30 miwi Exp $
#

    COMMENT = Text processing utilities (does not include desktop publishing)

    SUBDIR += expat2
    SUBDIR += intltool
    SUBDIR += libxml2
    SUBDIR += libxslt
    SUBDIR += p5-XML-Parser

.include <bsd.port.subdir.mk>
