# $MidnightBSD: mports/x11-drivers/xf86-input-hyperpen/Makefile,v 1.3 2009/05/08 14:26:02 laffer1 Exp $

PORTNAME=	xf86-input-hyperpen
PORTVERSION=	1.3.0
PORTREVISION=	2
CATEGORIES=	x11-drivers

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X.Org hyperpen input driver
LICENSE=	x11

XORG_CAT=	driver

.include <bsd.port.mk>
