# $MidnightBSD: mports/x11/sessreg/Makefile,v 1.5 2013/03/24 19:44:44 laffer1 Exp $

PORTNAME=	sessreg
PORTVERSION=	1.0.8
PORTREVISION=	2
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Manage utmp/wtmp entries for non-init X clients
LICENSE=	mit

XORG_CAT=	app
USE_XORG=	x11

PLIST_FILES=	bin/sessreg

MAN1=		sessreg.1

.include <bsd.port.mk>
