# $MidnightBSD: mports/multimedia/gstreamer-plugins-dvd/Makefile,v 1.2 2011/02/02 21:11:11 laffer1 Exp $
# $FreeBSD: ports/multimedia/gstreamer-plugins-dvd/Makefile,v 1.11 2007/05/19 20:17:24 flz Exp $

PORTREVISION=	0
CATEGORIES=	multimedia

COMMENT=	Gstreamer dvd plugin set

GST_PLUGIN=	dvd

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
