# $MidnightBSD: mports/x11/xclipboard/Makefile,v 1.4 2011/09/20 23:38:53 laffer1 Exp $

PORTNAME=	xclipboard
PORTVERSION=	1.1.2
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X clipboard client
LICENSE=	mit

XORG_CAT=	app
USE_XORG=	xt xaw

MAN1=		xclipboard.1 xcutsel.1

.include <bsd.port.mk>
