# $FreeBSD: ports/x11/xkbcomp/Makefile,v 1.1 2007/05/19 20:27:55 flz Exp $
# $MidnightBSD: mports/x11/xkbcomp/Makefile,v 1.1 2007/10/08 05:27:42 ctriv Exp $

PORTNAME=	xkbcomp
PORTVERSION=	1.1.0
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Compile XKB keyboard description
LICENSE=	sgi

XORG_CAT=	app
USE_XORG=	x11 xkbfile

PLIST_FILES=	bin/xkbcomp

MAN1=		xkbcomp.1

.include <bsd.port.mk>
