# $MidnightBSD$
# $FreeBSD: head/dns/bind-tools/Makefile 397807 2015-09-25 10:05:48Z mat $

# Define PORTREVISION in ${MASTERDIR}
MASTERDIR=	${.CURDIR}/../../dns/bind910

DESCR=		${.CURDIR}/pkg-descr
PLIST=		${.CURDIR}/pkg-plist
PKGINSTALL=	/nonexistent

BIND_TOOLS_SLAVE=	YES

INSTALL_WRKSRC=	${WRKSRC}/bin

.include "${MASTERDIR}/Makefile"
