PORTNAME=	Horde_CssMinify
PORTVERSION=	1.0.4
CATEGORIES=	textproc www pear

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Horde CSS Minification
WWW=		https://pear.horde.org

LICENSE=	lgpl2.1

USES=	horde cpe

.include <bsd.port.mk>
