# $MidnightBSD: mports/net-p2p/Makefile,v 1.8 2009/01/04 22:53:42 laffer1 Exp $
#

    COMMENT = peer-to-peer network applications

    SUBDIR += ctorrent
    SUBDIR += frostwire
    SUBDIR += gift
    SUBDIR += gift-fasttrack
    SUBDIR += gift-gnutella
    SUBDIR += giftcurs
    SUBDIR += libtorrent
    SUBDIR += mutella
    SUBDIR += rtorrent
    SUBDIR += transmission

.include <bsd.port.subdir.mk>
