# $MidnightBSD: mports/sysutils/Makefile,v 1.5 2006/10/04 20:52:54 laffer1 Exp $
#

    COMMENT = System utilities

    SUBDIR += cdrtools
    SUBDIR += coreutils
    SUBDIR += fusefs-kmod 
    SUBDIR += fusefs-libs 
    SUBDIR += fusefs-sshfs
    SUBDIR += libcdio
    SUBDIR += screen
    SUBDIR += timemon

.include <bsd.port.subdir.mk>
