# New ports collection makefile for:	secpwgen
# Date Created:				12 April 2007
# Whom:					wintellect <wintellect@bsdnexus.com>
#
# $MidnightBSD: mports/security/secpwgen/Makefile,v 1.1 2007/04/12 14:06:16 wintellect Exp $
#

PORTNAME=	secpwgen
PORTVERSION=	1.3
PORTREVISION=	1
CATEGORIES=	security
MASTER_SITES=	http://zvrba.net/software/

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	A utility for generating secure passphrases
LICENSE=	unknown

MAN1=		secpwgen.1

.include <bsd.port.mk>
