# $MidnightBSD: mports/net/Makefile,v 1.6 2006/10/02 06:36:05 laffer1 Exp $
#

    COMMENT = Networking tools

    SUBDIR += 44bsd-rdist
    SUBDIR += libdnet
    SUBDIR += netcat
    SUBDIR += netclasses
    SUBDIR += openldap23-client
    SUBDIR += openldap23-server
    SUBDIR += rsync
    SUBDIR += samba3

.include <bsd.port.subdir.mk>
