PORTNAME=	retryable
PORTVERSION=	3.0.5
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Allow for retrying of code blocks
WWW=		https://github.com/nfedyashev/retryable

LICENSE=	mit
LICENSE_FILE=	${WRKSRC}/LICENSE.md

USES=		gem

NO_ARCH=	yes

.include <bsd.port.mk>
