# $MidnightBSD: mports/x11/xvidtune/Makefile,v 1.2 2009/03/25 01:21:59 laffer1 Exp $

PORTNAME=	xvidtune
PORTVERSION=	1.0.2
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Video mode tuner for X
LICENSE=	x11

XORG_CAT=	app
USE_XORG=	xxf86vm xt xaw

MAN1=		xvidtune.1

.include <bsd.port.mk>
