PORTNAME=	xvidtune
DISTVERSION=	1.0.4
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Video mode tuner for X

LICENSE=	mit

USES=		tar:xz xorg xorg-cat:app
USE_XORG=	xxf86vm xt xaw

.include <bsd.port.mk>
