# New ports collection makefile for:	php5-sybase_ct
# Date created:			7 Jul 2004
# Whom:				Alex Dupre <ale@FreeBSD.org>
#
# $MidnightBSD$
# $FreeBSD: ports/databases/php5-sybase_ct/Makefile,v 1.1 2004/07/19 08:59:47 ale Exp $
#

CATEGORIES=	databases

MASTERDIR=	${.CURDIR}/../../lang/php5

PKGNAMESUFFIX=	-sybase_ct

.include "${MASTERDIR}/Makefile"
