# $MidnightBSD: mports/accessibility/at-spi-reference/Makefile,v 1.3 2008/06/14 14:33:06 laffer1 Exp $

PORTREVISION=	1
LICENSE=	lgpl
# the source distirbution is lgpl
BOOKS=		cspi idl

.include "${.CURDIR}/../../devel/glib20-reference/bsd.gnome-reference.mk"
