PORTNAME=	lumina-themes
PORTVERSION=	201710311100
PORTREVISION=	1
CATEGORIES=	x11-themes

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Lumina desktop wallpapers/colors
WWW=		https://github.com/trueos/lumina-themes

LICENSE=	bsd2 CC0-1.0
LICENSE_COMB=	multi

USES=	qmake qt:5
USE_QT=		qmake:build

USE_GITHUB=	yes
GH_ACCOUNT=	trueos
GH_PROJECT=	lumina-themes
GH_TAGNAME=	1b395f36674ba4aad193fd6e4eed0ddb40f1738e

.include <bsd.port.mk>
