# New ports collection makefile for:	lang/p5-Scalar-List-Utils
# Date created:				19 December 2001
# Whom:					Anton Berezin <tobez@FreeBSD.org>
#
# $FreeBSD: ports/lang/p5-Scalar-List-Utils/Makefile,v 1.9 2005/12/04 15:56:04 tobez Exp $
# $MidnightBSD$
#

PORTNAME=	Scalar-List-Utils
PORTVERSION=	1.23
PORTEPOCH=	1
CATEGORIES=	lang perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	Perl subroutines that would be nice to have in the perl core
LICENSE=	perl

PERL_CONFIGURE=	yes

MAN3=		List::Util.3 Scalar::Util.3 List::Util::XS.3

.include <bsd.port.mk>
