# $MidnightBSD: mports/x11/libXres/Makefile,v 1.1 2007/10/05 15:13:37 ctriv Exp $

PORTNAME=	libXres
PORTVERSION=	1.0.3
PORTREVISION=	1
CATEGORIES=	x11

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X Resource usage library
LICENSE=	x11

XORG_CAT=	lib
USE_XORG=	x11 xext xextproto resourceproto xproto

MAN3=		XRes.3 \
		XResQueryClients.3 \
		XResQueryClientPixmapBytes.3 \
		XResQueryClientResources.3 \
		XResQueryExtension.3 \
		XResQueryVersion.3

.include <bsd.port.mk>
