# $MidnightBSD: mports/x11-drivers/xf86-video-trident/Makefile,v 1.3 2011/05/07 21:54:53 laffer1 Exp $
#

PORTNAME=	xf86-video-trident
PORTVERSION=	1.3.4
CATEGORIES=	x11-drivers

MAINTAINER=	ports@MidnightBSD.org
COMMENT=	X.Org trident display driver
LICENSE=	mit

XORG_CAT=	driver
USE_XORG=	videoproto xextproto xf86dgaproto
MAN4=		trident.4x

.include <bsd.port.mk>
