# New ports collection makefile for:	gstreamer-plugins-pango
# Date created:			23 Nov 2007
# Whom:				Lucas Holt <luke@midnightbsd.org>
#
# $MidnightBSD: mports/x11-toolkits/gstreamer-plugins-pango/Makefile,v 1.1 2007/11/24 03:14:23 laffer1 Exp $
#

CATEGORIES=	x11-toolkits

COMMENT=	Gstreamer pango textoverlay plugin
LICENSE=	agg

GST_PLUGIN=	pango

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
