# New ports collection makefile for:	php5-dom
# Date created:			7 Jul 2004
# Whom:				Alex Dupre <ale@FreeBSD.org>
#
# $MidnightBSD$
# $FreeBSD: ports/textproc/php5-dom/Makefile,v 1.1 2004/07/19 09:21:32 ale Exp $
#

CATEGORIES=	textproc

MASTERDIR=	${.CURDIR}/../../lang/php5

PKGNAMESUFFIX=	-dom

.include "${MASTERDIR}/Makefile"
